### ISSUE TITLE
Hiding time ranges on timeline

### ISSUE THREAD

**Issue by ScarlettCode** [fullcalendar/fullcalendar-scheduler#1]
Is it possible to hide time ranges on the timeline view. For example midnight - 6 am and then 8 pm to midnight is time that events are hardly ever scheduled so it would be nice to have a way to dynamically show/hide these times. Maybe a call back to reload the timeline view with the times showing or without them showing.

**Comment by arshaw** [comment]
minTime and maxTime options can do this:
http://fullcalendar.io/docs/timeline/minTime_maxTime/

However, you can only set them for initialization. If you'd like to be able to dynamically change them after initialization, here is a ticket for that:
https://github.com/fullcalendar/fullcalendar/issues/564

**Comment by arulraj711** [comment]
@arshaw , Can we hide the whole timeline? So that we can get the horizontal resourceDayGrid👍 
Whats your thoughts on this horizontal resourceDayGrid?
