### ISSUE TITLE
refetchResources does not update columns properly in vertical resource view

### ISSUE THREAD

**Issue by caseyjhol** [fullcalendar/fullcalendar-scheduler#100]
It doesn't appear this was resolved by commit 7896125, although I'm sure it's related.

Demo: http://jsbin.com/natuxu/edit?js,output

In this demo, to simulate new resources every time the "refetchResources" button is clicked, the resources are now generated by a function that randomly selects one of 7 resources, and then removes it, only showing 6 resources.

The visible resources are updated every time the "refetchResources" button is clicked. You'll see this works fine in timeline view, but in vertical resource view, the correct columns are always "behind" where they should be, even if the correct events are being displayed. I've also named the events according to the resource they belong to, to make it easier to spot the issue (e.g. event A is in Auditorium A).

**Comment by arshaw** [comment]
Ah yes, I was able to reproduce this while making the most recent release. I made acceptance tests here: https://github.com/fullcalendar/fullcalendar-scheduler/blob/v1.2.0/tests/column-rerendering.coffee#L20-L33

will get this fixed

**Comment by Efiware** [comment]
I experience this error too in more or less same scenario. Any idea when this will be fixed?

**Comment by arshaw** [comment]
will be fixed in the next release. my goal is to have it released by monday

**Comment by arshaw** [comment]
updated jsbin to newest version, fixed the problem: http://jsbin.com/cavoxojiwe/1/edit?js,output

**Comment by arshaw** [comment]
fix just released in [v1.2.1](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.2.1)

**Comment by caseyjhol** [comment]
Awesome - thanks!
