### ISSUE TITLE
Enhance eventOrder to sort by 'other' properties first before sorting by date/time

### ISSUE THREAD

**Issue by sboele** [fullcalendar/fullcalendar-scheduler#106]
The current eventOrder funcionality: "Determines the vertical ordering events that have the same dates / times." according to the docs. It would be nice if you could change the order of the events by sorting by other properties first before sorting date/time. Now it only uses this option when events have the same date/time and duration. This way you can 'group' events together in a day view. For example: open and closing timewindows that are on the same day but you want them grouped together.

**Comment by arshaw** [comment]
I actually found an existing ticket for this in the main repo (where it should more appropriately live). Can you please subscribe to it? https://github.com/fullcalendar/fullcalendar/issues/2907

I'll be closing this one.

**Comment by Charoday** [comment]
Hello! 
I want to implement the order of events as in the screenshot. To purple events are always located on the bottom edge, despite the time of the beginning of the event. I tried to specify the sort order in the form of an array, as a function, but the order does not change.

![image](https://user-images.githubusercontent.com/17511259/32266119-bf9ad7d0-bf18-11e7-832b-b40688cb8e7b.png)

**Comment by archemedia** [comment]
I think that's currently impossible. See https://stackoverflow.com/questions/46684181/fullcalendar-timeline-vertical-stacking
I would like this feature too, maybe you can post a feature request for this?

**Comment by Charoday** [comment]
I'll try to find the fullcalendar command contact form
