### ISSUE TITLE
refine multiple resource event dragging

### ISSUE THREAD

**Issue by alan1o** [fullcalendar/fullcalendar-scheduler#111]
If you have an event which is allocated to several resources, say there are resources A,B and C and the event is allocated to resource A and C. If you move the event from resource A to resource B it no longer appears in resource C. The expected behaviour would be that you now see it in resource B and C

**Comment by arshaw** [comment]
i agree. another question, if one instance of the event was dragged to have its dates changed, what you expect to happen to the other event?

**Comment by alan1o** [comment]
Well they should both update to show the same time as they're essentially the same event.

**Comment by arshaw** [comment]
that's what i thought as well. just checking

**Comment by atilleul** [comment]
Hi. Also awaiting a fix

**Comment by rob3c** [comment]
Hi, I just wanted to mention a related problem with event resizing even when the start time doesn't change. It currently only lets you see the event under the mouse change size while dragging the end time, and the siblings are lost as soon as the resize starts. (I originally responded to #155, but it was suggested that this issue is more relevant.)

**Comment by arshaw** [comment]
@rob3c after rereading this issue, my mistake, #155 is more relevant to what you request. sorry for the runaround. 155 deals with what happens under your mouse during the drag.

**Comment by micbenner** [comment]
Hi @arshaw - wondering if you've got any sort of time frame on this?

Cheers!

**Comment by toxaq** [comment]
Here's the link from my duplicate #208 to an example of the issue

http://jsbin.com/noliye/edit?html,output

The question around the date changing is interesting. At the moment the drag handler doesn't provide what the resource ids were before the drop, I manually add these, so I can then compare before and after and warn appropriately. That might be a useful change here too (unless I've already missed something).

**Comment by arshaw** [comment]
Released in [v1.5.1](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.5.1)

demo: http://jsbin.com/dizuhaginu/1/edit?js,output

This is the new default behavior. No configuration necessary.

**Comment by sboele** [comment]
Is it correct that it only shows the current event you're dragging while moving? The same event on the other resource dissapears while dragging and reappears when dropping it.

**Comment by yoh** [comment]
@sboele @arshaw on my patch, the same event on the other resource not disappears

**Comment by arshaw** [comment]
@sboele , that's what this issue is all about: https://github.com/fullcalendar/fullcalendar-scheduler/issues/155
