### ISSUE TITLE
minTime/maxTime behaviour differentiates from calendar minTime/maxTime behaviour

### ISSUE THREAD

**Issue by MartijnWelker** [fullcalendar/fullcalendar-scheduler#112]
In the `calendarDay` view it is possible to set the `minTime` to `"04:00:00"` and the `maxTime` to `"28:00:00"`, this results in a view from 4AM to 4AM the next day. Doing the same in the scheduler results in a view from 4AM to midnight the same day, is this intended behaviour ?

**Comment by arshaw** [comment]
maxTime is currently not designed to work with values beyond `24:00:00`. this would need to be taken into account. keeping this open to see if others are interested

**Comment by arshaw** [comment]
oh, my the "calendarDay" view, do you mean "agendaDay" ? i didn't realize this was possible in agendaDay

**Comment by MartijnWelker** [comment]
Yes I meant agendaDay, I'll provide a plunkr but I'm on mobile now

**Comment by MartijnWelker** [comment]
Plunkr here: http://plnkr.co/edit/roaxD33NgyKHrOvSgbGE?p=preview

**Comment by fredhannouche** [comment]
I have exactly the same need, for a timeline view from 8am to 8am the next day.
Thanks

**Comment by arshaw** [comment]
a workaround might involve [customizing the view's duration](http://fullcalendar.io/docs/timeline/customizing_duration/) to `24:00` and having its `defaultDate` be a date with time `04:00:00`

**Comment by arshaw** [comment]
but i see what u mean about difference in behavior. again, this is leveraging somewhat undefined API behavior. i'd rather have this done via some other view-customization settings.

**Comment by fredhannouche** [comment]
thanks for your answer, and actually, your proposal does not match with what I want to do.
do you think you can change the API in the coming days?

**Comment by arshaw** [comment]
I can try to make this behavior match what is in agenda views. I would like to get it into the next Scheduler minor release, but I cannot guarantee when that'll be.

**Comment by mlaufer** [comment]
+1

Would also appreciate this behaviour. I'm currently working with my own implementation where i calculate offsets to stay inside the 00:00-24:00 timespan and change the labels in the scheduler on my own

**Comment by arshaw** [comment]
just released in [v1.2.1](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.2.1)

minTime/maxTime's that are negative or beyond 24:00 should work well now
