### ISSUE TITLE
unbindGlobalHandlers is not called on .fullCalendar('destroy');

### ISSUE THREAD

**Issue by MartijnWelker** [fullcalendar/fullcalendar-scheduler#117]
After calling `<element>.fullCalendar('destroy');` the drag handlers don't get removed, this will cause the following error when you drag something else (such as a jQuery sortable) 

    Uncaught TypeError: Cannot read property 'ownerDocument' of undefined

The error is thrown in `getScrollParent @fullcalendar.js:306`, this happens because fullCalendar is still listening to `externalDragStart`

**Comment by arshaw** [comment]
Hmm, I'm it seems like `Grid.js :: unbindGlobalHandlers` should be called from `TimelineView :: unrenderSkeleton` but maybe it's not for some reason. I haven't had the time to recreate this.

Could you please rig up a JSBin for this? http://fullcalendar.io/wiki/Reporting-Bugs/
It'd be great if your JSBin called the destroy method, followed by manually simulating a `dragstart` event on the `document` if you think that makes sense

**Comment by MartijnWelker** [comment]
[Here is the JSBin](http://jsbin.com/foxopagate/edit?html,js,output), how to reproduce:

1. Drag an element to verify no error occurs
2. Press the "Click to destroy" button
3. Drag an element, see the error appear in the console

This bug affects the functionalities of other draggables on the page (I'm using ui-draggable in Angular and it prevents draggable from ordering/moving the draggables) rendering them useless.

**Comment by arshaw** [comment]
thanks for the recreation. i can reproduce now

**Comment by arshaw** [comment]
updated jsbin to latest version, fixed: http://jsbin.com/xarexakuso/1/edit?html,output

**Comment by arshaw** [comment]
fix just released in [v1.2.1](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.2.1)
