### ISSUE TITLE
Changing view from timeline and agenda breaks external drop

### ISSUE THREAD

**Issue by mlaufer** [fullcalendar/fullcalendar-scheduler#118]
Hello,

there seems to be a significant bug when changing views from timeline to agenda and using the external drop component to create new events.

The issue seems to be with the **HitDragListener**, since the **component** variable used by the constructor remains an instance of **ResourceTimelineGrid**, when it should be an instance of **FC.TimeGrid.Grid**. This results in wrong behaviour and a javascript error: Uncaught TypeError: Cannot read property 'ownerDocument' of undefined

A example can be found here: http://fullcalendar.io/js/fullcalendar-scheduler-1.2.0/demos/external-dragging.html

Just change to week and try to drop any event.

Best regards and thanks again for your awesome work with the fullcalendar and scheduler!

**Comment by arshaw** [comment]
I was able to reproduce the JS error, thanks. Will try to get this fixed soon.

FYI, if you close your JS console and let the JS error fire, the user is still able to complete the drop action it seems.

**Comment by mlaufer** [comment]
Yeah, the calendar still works. But we are using it inside an angular application and the $digest cicle fired after the js calendar does not continue to update our other directives, which are directly involved in the drop process.

**Comment by arshaw** [comment]
fix just released in [v1.2.1](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.2.1)
