### ISSUE TITLE
Dynamically refetch resources upon navigation

### ISSUE THREAD

**Issue by nikkyb8** [fullcalendar/fullcalendar-scheduler#12]
Hello and congratulations for the good work :)
I have a small problem on resource recovery as for retrieving data, I the period concerned but not for gold resources the January resources are not necessarily the same as that of February ...
So should the start date and end during calls to resource functions.

Is it possible to put this?
If it's good on my side I buy ;) and congratulations !

**Comment by nikkyb8** [comment]
Hello,

Are you able to have a solution or difinitivement this is not possible?
I wish to recall:
have the start and end for the research resource.
at each change of view or period again a resource search

Best regards

**Comment by arshaw** [comment]
i understand the need for this. thanks for the feature request

**Comment by invisiblefunnel** [comment]
:+1:

**Comment by gcheema** [comment]
:+1:

**Comment by lephleg** [comment]
+1

**Comment by duetempi** [comment]
:+1:
when it is released the change?More or less ;)

**Comment by arshaw** [comment]
This will be a Q4 initiative, but I can't give you precise release date. It's on my radar as a demanded feature 😄

**Comment by arshaw** [comment]
implemented and released in [v1.5.0](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.5.0)

https://fullcalendar.io/docs/resource_data/refetchResourcesOnNavigate/

**Comment by kpollardsprypoint** [comment]
Even with this new _refetchResourcesOnNavigate_ flag set to _true_, I am not seeing _start_ and _end_ parameters in the HTTP request for resources.  Is the workaround described by woodburn8 still required?

**Comment by arshaw** [comment]
@kpollardsprypoint, the innovation with `refetchResourcesOnNavigate` is that the resources are queried for every time the users navigates, but the parameters that the `resources` function and json feed receive are still the same.

what you are requesting is an obvious improvement for the next iterative. i've made a ticket:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/246
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

That ticket contains workarounds that will help you (without modifying the source code).

**Comment by duetempi** [comment]
Thanks very much to the contributors here.
I have a view with the resources, for example the view day (but it could also be the view week or the view month) and (using the property groupByDateAndResource:true ).
Is it possible to hide one resource for a single day (in view with two days or in week)?

As in the example (like in the image)

DAY RESOURCES ENABLED

Monday A,B,C
Tuesday A,B
Wednesday A,B,C
Thurday B,C
Friday A,C
Saturday A,B,C
Sunday C

Thank you
![76cc9ac2-80b5-11e6-83e6-bf43b0841519 1](https://cloud.githubusercontent.com/assets/22366073/25042897/ff23e9dc-211b-11e7-9e52-60c7bec6b3a8.png)

**Comment by arshaw** [comment]
@duetempi, no, could you make a separate feature request ticket for this?

**Comment by KonnectSalon** [comment]
Still no update on this?
