### ISSUE TITLE
No events when setting resourceIds array

### ISSUE THREAD

**Issue by dannemanNov** [fullcalendar/fullcalendar-scheduler#120]
Hi.

After update fullcalendar to 2.6.0 and scheduler 1.2.0 the events is not shown with agendaDay and having multiple resources and attaching an event to multiple resources:

{
resourceIds: [1, 2....]
}

when setting single resource to event there is no problem.

{
resourceId: 1
}

/Daniel

**Comment by arshaw** [comment]
Would you mind posting a  JSBin demonstration of the bug? http://fullcalendar.io/wiki/Reporting-Bugs/

**Comment by dannemanNov** [comment]
https://jsfiddle.net/pap24g7b/1/

I found my own solution. If i set the id of the resource as a String it will work, In this example above I am using integer as id and as you can see it is not working.

**Comment by arshaw** [comment]
thanks for the JSBin. even still, Schedule should be smart enough to know to associate this, especially if all are integers. will consider this a bug. thanks

**Comment by arshaw** [comment]
this problem is now fixed. number and string ids should not resolve to the same thing

just released in [v1.2.1](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.2.1)
