### ISSUE TITLE
Feature: Sort Vertical Resources

### ISSUE THREAD

**Issue by daniel-nagy** [fullcalendar/fullcalendar-scheduler#126]
It would be nice to order vertical resources by an arbitrary property. The motivation for this is when resources (columns) are added dynamically they are always appended to the end of the header.

**Comment by arshaw** [comment]
can be achieved by `resourceOrder`: http://fullcalendar.io/docs/resource_rendering/resourceOrder/

**Comment by daniel-nagy** [comment]
I don't know how I didn't see the `resourceOrder` documentation. It is exactly what I needed, thanks!
