### ISSUE TITLE
Multiple resources for one event

### ISSUE THREAD

**Issue by Flofie** [fullcalendar/fullcalendar-scheduler#13]
Today its only possible to assign one resource to an event. We need the possibility to assign multiple resources like:

`events: [
{ 
id: '1', 
resources: ['b','a','c'], 
start: '2015-06-07T02:00:00', 
end: '2015-06-07T07:00:00', 
title: 'event 1' 
}
]`

**Comment by nikkyb8** [comment]
Ok but I would like for the data, with the current period for the resource that is all :) is it possible

Thank's

**Comment by dingzj** [comment]
same questions here. can you @arshaw add this feature?

**Comment by sboele** [comment]
Hello! Is there any ETA when this feature will be added?

**Comment by gordonk** [comment]
+1

**Comment by alan1o** [comment]
+1 . Waiting on this and the vertical resource view before we can upgrade to FullCalendar scheduler.

**Comment by dingzj** [comment]
+1 This will be a great feature.

**Comment by dingzj** [comment]
+1 or @arshaw can you give some hints on how to do that? I am cracking this feature too... 
thanks.

**Comment by arshaw** [comment]
this shouldn't be too difficult. i am planning on tackling this in the next minor release

**Comment by dingzj** [comment]
@arshaw  that's great news, thanks a lot!

**Comment by sboele** [comment]
Any chance this minor release will be ready before the end of this year?

**Comment by arshaw** [comment]
yes, the minor release should be before the end of the year

**Comment by pratikdhaboo** [comment]
Hi, has this feature been added ?

**Comment by contrilabs** [comment]
+1 I need it because in my case multiple resources are working on same task at a time

**Comment by arshaw** [comment]
I am actively working on this. I'm sorry for the delay. Should be done on or before Wednesday.

**Comment by atilleul** [comment]
@arshaw Hi, would it be possible to generate this morning a new official release so that I can integrate all your fixes and features (mainly this one) in our projet? Last release is quite old now. Thanks in advance.

**Comment by arshaw** [comment]
yes! this has just been released in Scheduler 1.2.0

PS- i forgot to put this in the changelog

**Comment by arshaw** [comment]
http://fullcalendar.io/docs/resource_data/associating_events/
"Multiple Resources"

**Comment by atilleul** [comment]
@arshaw Great, thanks!

**Comment by alan1o** [comment]
I've only just started playing around with the scheduler so apologies if this has already been answered. But what happens when a resource which has been allocated some styling has multiple events associated with it ?

**Comment by arshaw** [comment]
the event will be rendered however each resource wants, even if that means having it render with different colors on each resource row

**Comment by gregskh** [comment]
Hello, @arshaw

I would like to create function for the calendar to select multiple rows and columns (multiple resources and days). But I didn't understand how to do it. If possible, please help. 

Thank you
