### ISSUE TITLE
Events spanning minTime or maxTime render incorrectly

### ISSUE THREAD

**Issue by Brandan** [fullcalendar/fullcalendar-scheduler#132]
On the timelineWeek view I have two events, one that starts before minTime and one that ends after maxTime. Both events are rendered incorrectly. The event that starts before minTime shows up as starting the previous day. The event that ends after maxTime looks like it ends well before the end of the day.

I have put together a minimalistic jsfiddle showing the problem.

http://jsbin.com/biyinu/edit?js,output

**Comment by Brandan** [comment]
Your most recent fix in fullcalendar 2.6.1 and fullcalendar-scheduler 1.2.1 has fixed this issue. Thank you.

**Comment by arshaw** [comment]
awesome
