### ISSUE TITLE
eventOverlap: false not working with multiple resources

### ISSUE THREAD

**Issue by huanaku** [fullcalendar/fullcalendar-scheduler#133]
This is a different scenario but seems similar to https://github.com/fullcalendar/fullcalendar-scheduler/pull/103

If an event has been scheduled across multiple resources using resourceIds, the user is not able to drop on any open slot that is within the time range specified by the multi resource event.

Scenario demonstrated at http://jsbin.com/zecijizasu/edit?js,output
 - event 4 is scheduled for auditorium E and F from 3 to 8. 
 - no event can be dropped to any resource between 3 and 8

I haven't had time to step through the code in depth yet, but maybe getPeerEvents is looking at a single resource id (which is blank) instead of resource ids, similar to 103.

**Comment by arshaw** [comment]
this issue was fixed in 1.2.1/2.6.1 . updated jsbin to demonstrate:
http://jsbin.com/qenacasoru/1/edit?js,output

**Comment by huanaku** [comment]
thanks very much
