### ISSUE TITLE
eventResourceField different from "resourceId", event resize and drag/drop not working

### ISSUE THREAD

**Issue by ciregia** [fullcalendar/fullcalendar-scheduler#134]
If i have a set of resources (for example rooms) and a set of events with a field "roomId" that i configure as "eventResourceField", the drag/drop operation and resize operation fails.
Also, i can overlaps events even if i had configured eventOverlap:false.
In the previous version (fullcalendar 2.4.0 and scheduler 1.0.0) all warks fine!

Scenario demonstrated at: http://jsbin.com/haxirozapa/edit?js,output
 - event "event 3" is scheduled for Auditorium D from Th6 to Fr 7
 - none of the other events can overlaps event "event 3"

I attach a screenshot of the error printed in console when i resize one event.
![image](https://cloud.githubusercontent.com/assets/16154413/13024045/0acf8d80-d1f0-11e5-90ca-6297055b9384.png)

**Comment by arshaw** [comment]
this has been fixed in 1.2.1/2.6.1 . i updated your jsbin to demonstrate the working version:
http://jsbin.com/dofezopobu/1/edit?html,output

**Comment by ciregia** [comment]
thank!
