### ISSUE TITLE
Is it possible to add custom buttons to each resource's cell?

### ISSUE THREAD

**Issue by xiaotian91** [fullcalendar/fullcalendar-scheduler#135]
We wanted to add delete buttons to each resource. Basically, when the user clicks on the button, the resource will be removed from the column. I used a compromised method which was not exactly what I want. 
```javascript
resourceRender: function(resource, cellEls) {
    cellEls.on('click', function() {
        if (confirm('Are you sure to delete ' + resource.building + resource.title + '?')) {
		$('#calendar').fullCalendar('removeResource', resource);
	}
    });
}
```
I was trying to add buttons to the header section using jquery dom manipulation <code>$("#calendar .fc-toolbar").after($('.fc-add'));</code> and it worked as expected. However, I was not able to add buttons to the resources' cells (say I was trying to append a div to each <code>$('.fc-cell-content')</code>)using the same technique. 
Hopefully, this question can get some attentions
thanks.

**Comment by arshaw** [comment]
Can you post a JSBin demo of what you're trying to do?
http://fullcalendar.io/support/

the technique you describe *should* work

**Comment by samersarhan** [comment]
Add like this  
resourceRender: function(resourceObj, labelTds, bodyTds) {
               belTds.append(" <button>Delete</button>")
            },
