### ISSUE TITLE
Separate business hours per resource?

### ISSUE THREAD

**Issue by movostudios** [fullcalendar/fullcalendar-scheduler#14]
Hi ya folks. I am wondering if anyone has been able to manipulate the rendering of cells to display a business hours type effect on a 'per-resource basis?

I can globally set business hours in fullcalendar which trickles down to the scheduler plugin. However the goal here is to define separate 'availability' for a given resource.

I haven't got any code to show at the moment as I have just started to look into this problem and don't know if it is even possible.

Any advice would be greatfully recieved.

Cheers

**Comment by espen** [comment]
Another alternative: I haven't started using the Scheduler yet but what I do in Fullcalendar is using background events. I guess this should work with specifying a resourceId for the Scheduler?

**Comment by movostudios** [comment]
Dude... Legend. Thanks @espen - Thats exactly what I'm after. Many thanks.
