### ISSUE TITLE
eventResourceEditable, control if events' resources can change/DnD

### ISSUE THREAD

**Issue by nikkyb8** [fullcalendar/fullcalendar-scheduler#140]
Hello,

Is it possible to be able to prevent an event from being moved to another resource ( timeline) but can still be moved on the line ?

Thank you in advance for your answers and congratulations for your work ;)

**Comment by arshaw** [comment]
this is theoretically possible by providing a custom function to eventOverlap:
http://fullcalendar.io/docs/event_ui/eventOverlap/

However, that's very cumbersome. This should be an easy-to-use setting.

**Comment by arshaw** [comment]
This should probably be implemented as a `eventResourceEditable` flag that further fleshes out `editable`.

**Comment by JalalSordo** [comment]
I'm looking for the same exact feature.

**Comment by arshaw** [comment]
If `editable` is `false`, but `eventResourceEditable` is set to `true`, then the event should be draggable between resources, but its start/end time should be frozen.

**Comment by toxaq** [comment]
I'm looking for the inverse of this, I want to drag between resources without the starttime being changed...

**Comment by arshaw** [comment]
This has been implemented in v1.4.0!
https://fullcalendar.io/blog/2016/09/feature-packed-releases/

[eventResourceEditable](https://fullcalendar.io/docs/resource_events/eventResourceEditable/) - should address all the usecases requested in this ticket
