### ISSUE TITLE
timeline slot appearance

### ISSUE THREAD

**Issue by iamkoby** [fullcalendar/fullcalendar-scheduler#142]
Currently the only ability is to edit `slotLabelFormat`. 
Let's say the format is "dd DD", I would love the option to edit css of that column but I can't separate classes of the "dd" and the "DD". The desired result is:
![screenshot 2016-02-24 12 03 02](https://cloud.githubusercontent.com/assets/2076259/13281819/94c4d458-daee-11e5-9edb-05f3e741ec35.png)

I am now patching this with editing the html in the viewRender function:
viewRender: function(view, element){
                        element.find('.fc-head .fc-time-area th.fc-widget-header .fc-cell-text').each(function(i, col){
                            var content = $(col).text().trim().split(',');
                            $(col).html('<span class="day-name">' + content[0] + '</span><span class="day-num">' + content[1] + '</span>');
                        });
                    },

**Comment by mattdanna** [comment]
Header styling and time format is also something I patched.
![image](https://cloud.githubusercontent.com/assets/1121110/13315478/c289c828-db5f-11e5-971a-9ecd0275c698.png)

**Comment by iamkoby** [comment]
@mattdanna yours is pretty. good job!

**Comment by arshaw** [comment]
moving this to core. could you please subscribe to this new ticket i created?
https://github.com/fullcalendar/fullcalendar/issues/3078

**Comment by arshaw** [comment]
fullcalendar/fullcalendar#3078
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
