### ISSUE TITLE
Scheduler Custom Views (docs)

### ISSUE THREAD

**Issue by CodyMorris** [fullcalendar/fullcalendar-scheduler#143]
Arshaw,

I love your add-on, recently purchased it a license.  I'm looking to build custom views from scratch, similar to whats discussed here: http://fullcalendar.io/docs/views/Custom_Views/, and I was curious if theres anything drastically different with writing custom views for your add-on.  I'm new to coffeescript but dont mind diving in.  Would love advice about good source to study

I want to keep it backwards compatibable so any advice would be much appreciated

Thanks!

**Comment by arshaw** [comment]
Hi @CodyMorris sorry for the delay. I don't monitor this issue tracker with the same diligence as the email support. The principals in the "Custom Views" article still apply, however, peeking at Scheduler's source code will give you a much greater understanding.

One difference I can point out is that Views/Grids that support resources should do the following:
https://github.com/fullcalendar/fullcalendar-scheduler/blob/master/src/resource-timeline/ResourceTimelineView.coffee#L4
https://github.com/fullcalendar/fullcalendar-scheduler/blob/master/src/resource-timeline/ResourceTimelineGrid.coffee#L4

**Comment by CodyMorris** [comment]
hey @arshaw , no problem at all and thanks for the response.  Does that mean email support is the best way to get in touch with you for other one-off questions?  It felt a little weird opening an issue for this since its not a true bug

**Comment by arshaw** [comment]
I appreciate you opening it as a issue tracker ticket so that other developers can benefit from it

**Comment by CodyMorris** [comment]
hey @arshaw , sorry to necro this thread, but do you have any advice as to how I can implement custom views without breaking future upgrading of the core library?  Trying to figure out if theres a proper way to inject or include my add-on views without modifying your source directly

**Comment by arshaw** [comment]
hopefully this is good enough: http://fullcalendar.io/docs/views/Custom_Views/ > "Coding a View From Scratch"

**Comment by CodyMorris** [comment]
Adam, I'm all set man!  I have my views and everything uve given me has
been a great help.  Thanks!
