### ISSUE TITLE
Vertical Agenda Scheduler Integration with Oracle APEX

### ISSUE THREAD

**Issue by James1742** [fullcalendar/fullcalendar-scheduler#144]
Hi,

Is there any way to incorporate the vertical agenda view now into Oracle Apex 5 shown in the link below?  

https://github.com/fullcalendar/fullcalendar-scheduler/issues/5

Paying for it is not an issue but, was just curious if anyone has any hints on how/if it can be done now versus waiting to see if Oracle adds it in.

Thanks,
James

**Comment by espen** [comment]
1) Please don't use issues for questions: http://fullcalendar.io/support/. Btw it probably helps to clarify your question as many people don't know what Oracle Apex is and thus wouldn't know what you are trying to accomplish.

2) Vertical resource view has been released. See http://fullcalendar.io/docs/vertical_resource_view/getting_started/

3) If you need to adjust the view see http://fullcalendar.io/docs/views/Custom_Views/
