### ISSUE TITLE
rightclick function

### ISSUE THREAD

**Issue by ajaybairagi** [fullcalendar/fullcalendar-scheduler#146]
I want to set some parameters with right click on calendar  events.
have any option ?
like: https://github.com/mherrmann/fullcalendar-rightclick

**Comment by arshaw** [comment]
Hi Ajay,

You can attach any sort of handlers to event DOM elements via this hook:
http://fullcalendar.io/docs/event_rendering/eventRender/

In the future, please reference the "Getting Help" section of the [the Support page](http://fullcalendar.io/support/). This will be the last time will answer a question for you on the issue tracker.
