### ISSUE TITLE
EventSource resourceId should alter JSON feed events resourceId

### ISSUE THREAD

**Issue by rupertbg** [fullcalendar/fullcalendar-scheduler#147]
Consider the following eventSource object:
`{ id: 'C03', resourceId: 'a', url: '/eventfeed' }`

Events that have no resourceId in the JSON array /eventfeed load without a resourceId.

The eventSource object's resourceId should mean all events from that feed go to that resourceId, as they do from Google Calendar sources.

**Comment by arshaw** [comment]
would you mind subscribing to #124 ?
