### ISSUE TITLE
hide unused columns

### ISSUE THREAD

**Issue by arilishu** [fullcalendar/fullcalendar-scheduler#148]
I am not sure if it exists, so, sorry if i didn't found this!

When i load resources and events, not always the resources has events.
Is there anyway, to hide the columns, without events?
![print](https://cloud.githubusercontent.com/assets/1785576/13922731/5a97ee82-ef5c-11e5-904b-68c405a3659a.png)

Thanks!

**Comment by arshaw** [comment]
can you please subscribe to #98 ?

**Comment by thusila** [comment]
I also have this issue.Have you got a solution for that?
