### ISSUE TITLE
Timeline indicators

### ISSUE THREAD

**Issue by antoinebrault** [fullcalendar/fullcalendar-scheduler#149]
Is there any ways to do custom indicators like nowIndicator ?

It could be useful for a "roadmap" timeline view.
Something like:
http://cdn.productplan.com/wp-content/uploads/2016/02/timeline-based-roadmap.png
http://3.bp.blogspot.com/-2HXMxNaKlko/T1pSIVDlGGI/AAAAAAAAAOM/0b2-lR7UJ6Y/s1600/Roadmap.jpg
```
{
	title: 'test indicator',
	start: '2014-11-10T10:00:00',
	rendering: 'indicator'
}
```

**Comment by arshaw** [comment]
hmm this could be interesting. moving to core. could you please subscribe to this?
https://github.com/fullcalendar/fullcalendar/issues/3102
