### ISSUE TITLE
Events do not wrap correctly when start and end time crosses midnight into the next day, when "timezone: 'local'" is specified

### ISSUE THREAD

**Issue by woodburn8** [fullcalendar/fullcalendar-scheduler#15]
Events do not wrap correctly when start and end time crosses midnight into the next day, when "timezone: 'local'" is specified.  You can see the event on the day it starts on, but when you move forward to the day it ends on, it either doesn't show up at all, or it shows up at the start of the local timezone offset.

It seems to work fine when "timezone: false" is configured.  It only appears to be a problem when "timezone: 'local'" is configured.

Thanks

**Comment by arshaw** [comment]
@woodburn8 would you be able to create a JSBin for this when you get a chance? It is easier now with a debugging template: http://fullcalendar.io/wiki/Reporting-Bugs/ ("Scheduler Add-on > simple template")

**Comment by woodburn8** [comment]
Hi @arshaw, you can find it here:  http://jsbin.com/muwewejite/edit?js,output

Because "timezone local" is specified, please change your own computer's timezone to something greater than GMT to observe the problem.  I tested myself with GMT+8.  Thanks.

**Comment by arshaw** [comment]
thank you so much

**Comment by arshaw** [comment]
released in v1.0.1
jsbin updated with latest version to show the fix: http://jsbin.com/korijo/edit?js,output

**Comment by woodburn8** [comment]
The initially reported problem looks fixed, but now events are displayed as if "timezone: false" was specified, instead of local.  I'll debug some more, but wanted to report it first.

**Comment by arshaw** [comment]
this is because (at least within the jsbin demo) the events' dates do not have any timezone parts, which means they will be processed as if they are the local time. if you add an explicit timezone (`+0000`) you will see that it changes the rendering and should currently display:

http://jsbin.com/korijo/2/edit?js,output

**Comment by woodburn8** [comment]
Hm, can you check again?  I added the timezone (+0800), then tested with timezone false, and timezone local, and the events render the same in both cases.

**Comment by woodburn8** [comment]
Never mind, that should be expected for the case given, when the event timezone is same as the computer's timezone.

**Comment by arshaw** [comment]
Yeah. If you make them, +0900 you should see them show up an hour later

**Comment by woodburn8** [comment]
I have confirmed functionality is working as expected.  Thanks for the help and the fix.
