### ISSUE TITLE
scheduler, width problem with too much resources

### ISSUE THREAD

**Issue by arilishu** [fullcalendar/fullcalendar-scheduler#152]
Hi all.
This is my situation.
I need to show the scheduler from monday to friday.
And each day has lot of resources and events.
But i can't make the calendar width longer
is there any solution?
I have tried with slotWidth, and resourceAreaWidth but nothing.
one trick:
i can make slot longer with:

                eventAfterRender: function(event, element, view) 
                {
                   $(element).css('width','50');
                },

but the resource doesn't grow as the event

http://jsbin.com/tonuco/edit?js,output

**Comment by arshaw** [comment]
until [this feature is implemented](https://github.com/fullcalendar/fullcalendar-scheduler/issues/110) (horizontal scrolling), your best bet is to use Timeline view, which is much better at displaying lots of resources because it does it vertically and allows for scrolling.

**Comment by gansky-alexander** [comment]
Hello, @arilishu. Did you resolved your issue?

**Comment by arilishu** [comment]
no... i couldn't!

2016-05-17 7:03 GMT-03:00 Alexander Gansky <notifications@github.com>:
