### ISSUE TITLE
When eventDurationEditable and eventStartEditable are false

### ISSUE THREAD

**Issue by KrunchMuffin** [fullcalendar/fullcalendar-scheduler#153]
You should still be able to move to a different auditorium at same time. Doesn't let you.

http://jsbin.com/qukuyavofe/edit?js,output

**Comment by KrunchMuffin** [comment]
Any info on this? Need to be able to do this in order to purchase a license.

**Comment by arshaw** [comment]
your lines:
```
            eventDurationEditable: false,
            eventStartEditable: false,
```
are preventing any event from being resizable/drag-n-droppable

**Comment by KrunchMuffin** [comment]
doesn't make sense. Why can't I move the event to another auditorium at the same time? That doesn't affect the duration nor the event start.

**Comment by arshaw** [comment]
apologies @KrunchMuffin. i just saw this. this other feature requests for a new `eventResourceEditable` settings, which will override any `editable:false` directives, should achieve what you want:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/140#issuecomment-236481642
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

sorry for misinterpreting your issue at first.
