### ISSUE TITLE
Move event between certain resources

### ISSUE THREAD

**Issue by NiklasKamenisch** [fullcalendar/fullcalendar-scheduler#158]
Move Event only between certain resources

Example:
In my case I have 2 groups of resources. Once, for example, the rooms and even the staff. now for an appointment I need a room and an employee. To optimize utilization, I would like to shift the dates. It should remain at a Resource Group "rooms" and always at a Resource Group employees.

When this function is integrated and the error #155 was corrected , optimal planning can be created with the program.

**Comment by arshaw** [comment]
I could see this being something like `eventOverlap: function` (http://fullcalendar.io/docs/event_ui/eventOverlap/) but with a resource.

So maybe something like
```
eventResourceOverlap: function(event, resource) {
    return false; // or true
}
```

**Comment by kferrio** [comment]
That would create interesting possibilities!

**Comment by arshaw** [comment]
Could you please subscribe to #50 ? I've decided to have that pre-existing ticket represent this solution. thank you
