### ISSUE TITLE
bower.json ignores src files

### ISSUE THREAD

**Issue by Efiware** [fullcalendar/fullcalendar-scheduler#16]
Hi

The current bower.json ignores almost anything not in the dist folder. The dist folder this folder is not there, so while fetching via Bower, the source code files is not downloaded.

**Comment by arshaw** [comment]
just curious, why do you want the source files anyway? If you want the source files so that you can modify and then subsequently compile the project into a new build, maybe simply cloning the whole github repo yourself might be the best option. trying to understand

**Comment by Efiware** [comment]
I'm just evaluating fullcalendar-scheduler as a normal user, but tried to fetch it using bower install .., which fails. as descriped

**Comment by arshaw** [comment]
what does your `bower install blablabla` statement look like? maybe you are targeting an invalid version

**Comment by Efiware** [comment]
Hm - just did a 'bower install fullcalendar-scheduler' and back then, i didn't get a dist/ folder. I do know, so everything is working. Have no idea why.

**Comment by Efiware** [comment]
Fyi: I was using the composer-asset-plugin to pull this bower component via Composer. when using Bower manually, everything works, but via this plugin, the dist folder is not there.

**Comment by Efiware** [comment]
See https://github.com/fullcalendar/fullcalendar-scheduler/issues/21
