### ISSUE TITLE
unexpected behavior of 'removeResource'

### ISSUE THREAD

**Issue by kferrio** [fullcalendar/fullcalendar-scheduler#160]
Calling `removeResource` iteratively does not behave as expected based on the [API documentation](http://fullcalendar.io/docs/resource_data/removeResource/) retrieved today. Iterating `removeResource` over an array of resources obtained from `getResources` actually removes *every other* resource, such that *1 + log*2*(n)* complete loops would be required to remove an array of *n* resources. [JSBin here](http://jsbin.com/nahisu/edit?js,output)

**Comment by arshaw** [comment]
thanks, i reproduced this with your jsbin. seems like it's related to the successive calling. calling `removeResource` with timeouts in between works as expected.

**Comment by arshaw** [comment]
release in [v1.3.2](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.3.2)

was actually a problem with getResources, not removeResource

**Comment by kferrio** [comment]
Thanks!
