### ISSUE TITLE
WCAG 2.0 AA/AAA support in the timeline?

### ISSUE THREAD

**Issue by mmikitka** [fullcalendar/fullcalendar-scheduler#161]
Hello,

First of all, well done on this project.

I am working on a project for a publicly-funded University which is required to deploy all new web services with minimal WCAG 2.0 AA compliance, and AAA compliance in a few years. Are you considering the integration of accessibility-related constructs, notably WAI-ARIA?

Thanks for considering,
matt

**Comment by arshaw** [comment]
it is not currently in roadmap

**Comment by arshaw** [comment]
@mmikitka could you follow this issue to track progress on Aria? (on the core project issue tracker)
https://github.com/fullcalendar/fullcalendar/issues/2536
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
