### ISSUE TITLE
Missing bottom border of last resource

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar-scheduler#162]
when there aren't enough resources to fill the scroll area...

![screen shot 2016-04-23 at 5 13 33 pm](https://cloud.githubusercontent.com/assets/56520/14764703/d78bb1d8-0976-11e6-919a-81c6783874f6.png)

**Comment by J3QQ4** [comment]
Temporary fix: 

```
tr[data-resource-id]:last-child > td > div {
    border-bottom: 1px solid #ddd;
}
```

**Comment by arshaw** [comment]
that causes a slight visual glitch where there ARE enough resources to cause scrolling. there will be a double grey line at the very bottom near the bottom scrollbars. not major tho

**Comment by J3QQ4** [comment]
Indeed. margin-bottom: -1px seems to fix this. I've updated my temporary solution above.

**Comment by arshaw** [comment]
released in [v1.5.0](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.5.0)

**Comment by carter-dewey** [comment]
Still seeing this in version v5.

![image](https://user-images.githubusercontent.com/42411782/93286853-c11c3980-f79d-11ea-9b09-1fe7ba9cfa4b.png)

**Comment by stri8ed** [comment]
> Still seeing this in version v5.
> 
> ![image](https://user-images.githubusercontent.com/42411782/93286853-c11c3980-f79d-11ea-9b09-1fe7ba9cfa4b.png)

Temporary fix:

```
.fc-scrollgrid tr:last-of-type > td {
    box-shadow: 0 -1px 0px inset #ddd;
}
```
