### ISSUE TITLE
Events are no longer draggable with 1.3.0

### ISSUE THREAD

**Issue by KrunchMuffin** [fullcalendar/fullcalendar-scheduler#163]
1.2.1/1.6.1
http://jsbin.com/lihacipepi/1/edit?html,js,output

1.3.0/1.7.0
http://jsbin.com/zinopaxice/1/edit?js,output

**Comment by arshaw** [comment]
I'm able to drag events with your demos. Updated JSBin's, output directly:
http://output.jsbin.com/mixiyodoqa/1
http://output.jsbin.com/fubifisupu/1
(might expire due to JSBin's payment model)

What device/browser are you using? Or are you in a desktop browser's emulation mode?

**Comment by KrunchMuffin** [comment]
The links you have both are using the new code 1.3.0/1.7.0. I'll see if I can update them.

Chrome 49 and 50 1.3.0/1.7.0
http://screencast.com/t/6VJA2dqv0r

Chrome 49 and 50  1.2.1/1.6.1
http://screencast.com/t/fgtuexQlTCC

**Comment by KrunchMuffin** [comment]
ok, this is weird. 2 different computers, exact same OS and same chrome profile, one works other doesn't. gonna have to track this down some how.

**Comment by KrunchMuffin** [comment]
Finally figured it out and not sure what you can do about it. My laptop has a touchscreen and I also have 2 external monitors attached that are not touch and I am using external mouse/keyboard. So dragging works on the touchscreen when I touch, but not click and drag, and on the external screens click and drag does not work either. 
Are you overriding the click+drag event if a touch device is detected?

**Comment by KrunchMuffin** [comment]
Any update with this?

**Comment by arshaw** [comment]
I understand the problem now, thanks. Will fix in the next release.

**Comment by arshaw** [comment]
This is the issue in the core project's tracker:
https://github.com/fullcalendar/fullcalendar/issues/3154

**Comment by arshaw** [comment]
this was fixed:
https://github.com/fullcalendar/fullcalendar/issues/3154#issuecomment-220538096
