### ISSUE TITLE
Problem of loading data to resources and events from database

### ISSUE THREAD

**Issue by ayoub17** [fullcalendar/fullcalendar-scheduler#167]
I tried to load data to resources and events from database, I used the following instructions

			resources: { 
				url: 'cal_ressources.php',
				error: function() {
					$('#script-warning').show();
				}
			},

			eventSources: [{url: 'cal_events.php'}],

but I have got nothing, even the calendar could not display, I would like to know if I must include other options, because eventSources:[{url: 'cal_events.php'}] worked so well with fullcalendar, I don't know why it is not working on fullcalendar-scheduler. I was wondering if you would mind giving me any indication to solve that problem. Thank you so much.

**Comment by arshaw** [comment]
please look at your network tab to see if your scripts are being requested by the browser. something tells me its the misspelling in `cal_ressources.php`
