### ISSUE TITLE
On timeline/day view, lock day/time column headings to prevent scrolling out of view

### ISSUE THREAD

**Issue by rstoeber** [fullcalendar/fullcalendar-scheduler#168]
When there are a lot of resources listed it requires scrolling down, and the header lines containing the date/time scrolls off the screen. This makes it difficult to accurately drop an event into the correct date/time slot. Likewise, when looking at a 2 or 3-day timeline, it is impossible to tell which day you are looking at if the top of the page has scrolled off the screen.

If possible, there should be an option to make vertical scrolling behave like the horizontal scrolling where the events can scroll left-right, without moving the resource list. There should be an option to make headers act the same way.

**Comment by rstoeber** [comment]
Just realized this may be similar to issue #141 (timeline resource pagination)

Maybe a different solution to the same problem?

**Comment by rstoeber** [comment]
One possible solution, that might be really easy to implement, would be to optionally repeat the header row in timeline view after every 20 resource rows.

In other words, in the timeline view, provide an option to repeat the resourceLabelText and time header row, after every 20 (or some specified number) of resources.

This way, if the entire page scrolls up there will always be a "header row" in view to see the vertical slot times.

**Comment by arshaw** [comment]
reached out to Robert to get a demo of this. don't understand the behavior

**Comment by rstoeber** [comment]
Problem solved by specifying a fixed contentHeight. I had misunderstood the meaning of that parameter so I originally had it set on auto. By changing it to a fixed number the timeline area now has vertical scroll bars and the header of the page stays in place while scrolling a long list of resources.

Many thanks to Adam Shaw for looking at my problem, and developing this great code.

**Comment by arshaw** [comment]
thank you!
