### ISSUE TITLE
Ability to customize event rendering

### ISSUE THREAD

**Issue by dzeitman** [fullcalendar/fullcalendar-scheduler#169]
I'd like to be able to further customize how the event renders:
Example 1:
Single event with rendered with different titles:
<img width="1262" alt="single-event-different-titles" src="https://cloud.githubusercontent.com/assets/510636/15191638/668b6e0e-176a-11e6-8c2d-5cc6145a718a.png">

In this example:  Adams is meeting Oscar -  On Adams Timeline, the event should render Oscar as the title,  on Oscar's Timeline the event should render Adams as the title.   Is there a method or way to override the default behavior of setting the title and event body?

Example 2:
date/time display:   If an event duration is the same size as slot time - only the start time is shown.   I'd like to be able to display and format both start and stop times.

**Comment by arshaw** [comment]
Yup, you can use http://fullcalendar.io/docs/event_rendering/eventRender/

that callback will receive an event object. u can use that in combo with these methods to do things based on the resource:
http://fullcalendar.io/docs/resource_data/getResourceById/

**Comment by dzeitman** [comment]
Currently eventRender doesn't return any info about the current row:
I tried using:  $('#calendar').fullCalendar( 'getEventResource', event.id );
this returns the top most parent resource. 
See Image:
<img width="1256" alt="event-example" src="https://cloud.githubusercontent.com/assets/510636/15265136/68beed9e-1932-11e6-86a6-2f2b386c6cd3.png">
 
I was hoping the method was looking at the current event and resource row.

How can I get a handle on the current resource row from the eventRender method? 
In this use case:  
my event object has extra properties:   applicantId, interviewerId  
$('#calendar').fullCalendar( 'getEventResource', event.id )   returns the parent row (adams) each time eventRender is called,   I would have assumed that the resource would be (adams, hanson, curtis, curtis)  in this example.  

The row data for each resource has a resource-id: 
data-resource-id="56eb54273a340fa366748dd8"
But since the dom isn't yet rendered, when eventRender is being called;   $(element) doesn't have any parent nodes yet.  

Seems like the timeline view should also include the resourceObj in eventRender?

Your thoughts on how to accomplish the task of getting the row's resource id or object?

**Comment by arshaw** [comment]
it would be `$('#calendar').fullCalendar( 'getEventResource', event.resourceId )` does that work?

**Comment by dzeitman** [comment]
In this example:
each event has a applicantId and interviewId  -  I'm checking that against the method call: getEventResource

Row1 is an applicant,   child rows are interviewers:
expecting the console log to be  (adams, hanson, curtis, curtis) 
getting (adams,adams,adams,adams)

```
 var applicantResource = $('#calendar').fullCalendar( 'getEventResource', event.id );

if (applicantResource) {
	console.log(applicantResource.displayName);

	if (applicantResource.id === event.applicationId) {
	// this is a match it's the applicant row
	var interviewer = _.where( allInterviewers, {id:event.interviewerId} )[0];
	event.title = interviewer.displayName;
	}else{
		// show the applicant name
		event.title = applicantResource.displayName;
	};
};

```

**Comment by dzeitman** [comment]
In the above example;  the rows I"m rendering are child rows of the resource. 
resource.children is an array of interviewers.   I just assumed these are identified in the api as child resources -  Perhaps that's a wrong assumption.  
So circling back to the original task:   
How do I get the resource-data-id from the current row if the eventRender 's $(element) doesn't yet show up in the DOM?

is there a view method?

**Comment by arshaw** [comment]
I see this line in your demo:
```
var applicantResource = $('#calendar').fullCalendar( 'getEventResource', event.id );
```

Did you try my suggestion about using `.fullCalendar( 'getEventResource', event.resourceId )` instead? Passing in an event ID to the getEventResource method doesn't make any sense.

**Comment by victorkonen** [comment]
I have a similar use case as described in this issue. Your last suggestion was not working for me if an event is rendered for multiple resources. I found a way to achieve using a combination of the eventRender and eventAfterRender callbacks.

(Note: using ES6)
First, I add elements representing each resource object (stored as extra property on my events) for an event in the eventRender callback:
`const contentElement = element.find('.fc-content');`
`event.resources.forEach(resource => {`
`contentElement.append('<div id="#' +resource.id + '">' + resource.title + '</div>');`
`}`

Then, I remove the resource that the event is rendered under within the eventAfterRender callback by retrieving the data stored on the element:
`const contentElement = element.find('.fc-content');`
`const resource = element.data().fcSeg.resource;`
`const resourceElement = contentElement.find('#' + resource.id);`
`resourceElement.remove();`

Probably not the intended use, but it works for me. Hopefully this helps somebody else, it took some time to figure out.

**Comment by prologicPavi** [comment]
tedghgghjh
