### ISSUE TITLE
Can you Support Ummalqura Hijiri Date

### ISSUE THREAD

**Issue by hatem1975** [fullcalendar/fullcalendar-scheduler#17]
Dear Sir
we are in KSA and other Arabian Gulf Country use Umm Al Qura Hijri Date , can it supported with Arabic Language .

**Comment by espen** [comment]
Are you sure it is not supported?
1) FullCalendar uses moment.js which have support for all regional formats. See http://momentjs.com. Also I found https://github.com/xsoh/moment-hijri which might be of interest.
2) You can use RTL languages: http://fullcalendar.io/docs/display/isRTL/
3) You can customize all text, check out the docs.

**Comment by arshaw** [comment]
Duplicate of this issue: https://github.com/fullcalendar/fullcalendar/issues/2105
(main fullcalendar project)
