### ISSUE TITLE
System.JS modules export is missing

### ISSUE THREAD

**Issue by migajek** [fullcalendar/fullcalendar-scheduler#172]
Both fullcalendar and fullcalendar-scheduler require moment.js

While fhe first includes the following module initialization code

```
if (typeof define === 'function' && define.amd) {
      define(['jquery', 'moment'], factory);
    } else if (typeof exports === 'object') {
      module.exports = factory(require('jquery'), require('moment'));
    }else {
      factory(jQuery, moment);
    }
```

the latter one is missing the "else if" part, making it unusable with SystemJS loader
adding the ``else if `` part manually fixes the problem

**Comment by atilleul** [comment]
By the way, fullcalendar should be defined before using Scheduler:
define([ 'jquery', 'moment'**, 'fullcalendar'** ], factory);

**Comment by arshaw** [comment]
release in [v1.3.2](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.3.2)
