### ISSUE TITLE
removeResources is very slow

### ISSUE THREAD

**Issue by arturoperezgarcia** [fullcalendar/fullcalendar-scheduler#174]
Hi all,

I have 17 resources in timeline. And to refresh windows I apply the next code
`$.each(allResourcesIds, function (index, value) {
                $('#calendar').fullCalendar('removeResource', value);
            });`
           
But it takes more than 10 seconds to delete all resources to reload the following. Any chance you can lose time erased?

![image](https://cloud.githubusercontent.com/assets/3727437/15365820/f56389ce-1d21-11e6-9301-6f6d5b617800.png)

**Comment by MartijnWelker** [comment]
It's probably faster to destroy the calendar instance and rerender it with the new resources all at once, could you try that ?

**Comment by arshaw** [comment]
https://github.com/fullcalendar/fullcalendar/issues/2938 will solve this problem
&uarr;
Visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

@MartijnWelker suggestion would be a good stopgap solution
