### ISSUE TITLE
Problem with resources as function

### ISSUE THREAD

**Issue by nico51** [fullcalendar/fullcalendar-scheduler#175]
Hi,

I try to filter resources following issue #7 (using resources as function), but I meet a problem of display.

It works well, but, when I change the display view, sometimes resources are lost. It seems to happen when I filter for a second time.

In my code, when I write rendered resource to console on resourceRender callback, I see it's called too many times.

I create following JSBin:
http://jsbin.com/yixiyamabe/edit?html,js,output

Initial display
![01](https://cloud.githubusercontent.com/assets/3626770/15409984/ad79adf4-1e17-11e6-80ac-0e0064043864.png)

Filter with 'a'
![02](https://cloud.githubusercontent.com/assets/3626770/15409985/ad9a1abc-1e17-11e6-817e-abe30da5a86b.png)

Changing display
![03](https://cloud.githubusercontent.com/assets/3626770/15409987/adccb990-1e17-11e6-8865-8591c2a22d62.png)

Add 'n' to filter
![04](https://cloud.githubusercontent.com/assets/3626770/15409986/adb78b74-1e17-11e6-8bd1-5c96d9722f0b.png)

Changing display (resources lost)
![05](https://cloud.githubusercontent.com/assets/3626770/15409988/addd684e-1e17-11e6-8d0b-95186929455b.png)

After multiples display changes
![06](https://cloud.githubusercontent.com/assets/3626770/15409989/ade21830-1e17-11e6-9e61-8630e36bad43.png)

**Comment by arshaw** [comment]
Glancing at your code, it seems to be a problem with having setTimeout in your event fetching function. shouldnt be there; it should be in the keydown handler. Anyway, I don't have the bandwidth to debug much further, apologies

**Comment by arshaw** [comment]
actually, this is almost definitely related to
#179
&uarr;
Could you please the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
