### ISSUE TITLE
resourceRender causes misalignment of resource and event columns

### ISSUE THREAD

**Issue by scheduledapp** [fullcalendar/fullcalendar-scheduler#177]
Hi there, 

I'm using resoruceRender to add image to each resource.

When using the resourceRender function, if you modify the labelTds with anything other than css it causes a misalignment between resources and events. 

`resourceRender: function(resourceObj, labelTds) {
var name = resourceObj.title 
labelTds.html("<p>" + name)}`

<img width="712" alt="screen shot 2016-05-24 at 10 31 07 pm" src="https://cloud.githubusercontent.com/assets/11036739/15503919/bda4252e-21ff-11e6-9b2f-722f4c4ce31f.png">

I create following JSBin:
http://jsbin.com/tohuxequyo/edit?js,output

**Comment by arshaw** [comment]
unfortunately the DOM is a little overly complicated, so you'll need to target a more inner element `labelTds.find('.fc-cell-content')`. updated jsbin that works:

http://jsbin.com/nuhulurifa/1/edit?js,output
