### ISSUE TITLE
RESOURCE BUG

### ISSUE THREAD

**Issue by zirius666** [fullcalendar/fullcalendar-scheduler#178]
When i use the resource like a function in timelineweek view with a callback the resources are showing overlapping but when use an array of objects is running good

Thats an image of the error:
![captura](https://cloud.githubusercontent.com/assets/15053407/15585686/3d67c698-2346-11e6-9777-0cfe84fad831.PNG)

**Comment by arshaw** [comment]
could you please post a JSBin demo of your problem? http://fullcalendar.io/wiki/Reporting-Bugs/
will be invaluable for debugging.
