### ISSUE TITLE
refetchResources causes blank screen in version 1.3.1, works fine in 1.2.1

### ISSUE THREAD

**Issue by J3QQ4** [fullcalendar/fullcalendar-scheduler#179]
Steps to reproduce: 

1) Go to demo at http://fullcalendar.io/js/fullcalendar-scheduler-1.3.1/demos/dynamic-add-remove.html
(I didn't put it into a JSfiddle because the bug can be reproduced on a stock version in the demo)

2) Switch from 1-day view to 3-day view

3) Open the console and type:
$("#calendar").fullCalendar('refetchResources')

4) Switch back from 3-day view into 1-day view. 

Result: the screen will be blank.

Workaround: switch to another view and then switch back again. 

If you go to the version 1.2.1's demo, the same works fine: 
http://fullcalendar.io/js/fullcalendar-scheduler-1.2.1/demos/dynamic-add-remove.html

Why I'm using this:
I am implementing a custom filtering function, and when I reset the filter using refetchResources, the view goes blank until you switch to another view and back again.

**Comment by arshaw** [comment]
release in [v1.3.2](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.3.2)
