### ISSUE TITLE
EventDrop doesn't update eventResourceField

### ISSUE THREAD

**Issue by espen** [fullcalendar/fullcalendar-scheduler#18]
eventResourceField: 'my_resource_id'

EventDrop to new resource will not update my_resource_id with new id.

**Comment by arshaw** [comment]
i'm actually getting the correct resourceId for the event passed into `eventDrop`, but it's not persisting afterwards. demo: http://jsbin.com/kalefi/edit?js,output

**Comment by arshaw** [comment]
released in v1.0.1
http://jsbin.com/kalefi/4/edit?html,output
