### ISSUE TITLE
Set Duration - external events

### ISSUE THREAD

**Issue by srivch** [fullcalendar/fullcalendar-scheduler#183]
### Feature Requests
Is there a way i can set custom end time when i drag and drop an external event (i need to calculate travel time between two locations)?

**Comment by arshaw** [comment]
http://fullcalendar.io/docs/dropping/eventReceive/
http://fullcalendar.io/docs/event_ui/eventDrop/

for further questions
http://fullcalendar.io/support/
"Getting Help"
