### ISSUE TITLE
Externally dropped events sets timezone to GMT/UTC instead of calendar timezone

### ISSUE THREAD

**Issue by micfai** [fullcalendar/fullcalendar-scheduler#184]
I have a dropdown for a user to be able to select what timezone to view the scheduler in. When they select a timezone and drop an event, it sets the timezone of that event to GMT instead of the calendar timezone.

For example, if I drop an event at 16:00 Australia/Sydney the event.start is set to 16:00 GMT instead.

Here is an example of this happening. The timezone of the calendar is set to Australia/Sydney but the alert shows it as GMT.

http://jsbin.com/cuzebogote/edit?js,output

To work around this issue, I have to manually add the offset in minutes to get it to schedule correctly.

```javascript
var zone = moment.tz.zone('Australia/Sydney'); //_currentTimeZone is my var that holds this string
var offset = zone.parse(new Date()); //when using Date.UTC() it would calculate it an hour earlier

var start = moment(meeting.start).add(offset,"minutes").format("ddd, DD MMM YYYY HH:mm:ss ZZ");
var end = moment(meeting.end).add(offset,"minutes").format("ddd, DD MMM YYYY HH:mm:ss ZZ");
```

**Comment by arshaw** [comment]
FC doesn't do any timezone offset computations based off the given timezone. that's the server-side's job. see http://fullcalendar.io/docs/timezone/timezone/ : 
> 2) Your server-side script is then expected to use the timezone parameter to calculate the timezone offset of the returned ISO8601 dates!
