### ISSUE TITLE
When printing scheduler's timeline view, table header containing time is not showing

### ISSUE THREAD

**Issue by J3QQ4** [fullcalendar/fullcalendar-scheduler#185]
Bug can be reproduced with this demo; tested in Firefox and Chrome: 

* http://fullcalendar.io/js/fullcalendar-scheduler-1.3.2/demos/grouping.html

1. When in 1-day or 3-day view, go to print preview or switch to emulated print media. 
2. The column headers that show the time, such as "5am", will not show. Expected: they would show. 

#### Cause: 

There is a margin of -17px applied inline to fc-scroller: 

    <div class="fc-scroller" style="overflow-x: scroll; overflow-y: hidden; margin: 0px 0px -17px;">

#### Possible solution:

In fullcalendar.print.css, add:

    .fc-scroller {
        margin: 0px !important;
    }

**Comment by arshaw** [comment]
thanks for the code pointers. i will reference this when attacking this issue. but this is a duplicate:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/83
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by arshaw** [comment]
could you please post a screenshot in #83?
