### ISSUE TITLE
Scheduler: Events are not rendered in iPad (Chrome or Safari). 

### ISSUE THREAD

**Issue by rongxike** [fullcalendar/fullcalendar-scheduler#188]
### Bug Reports
Actually, I cannot get the bugs because it only happened in iPad, Android (Chrome) is working fine.

There are 10 days and 40 resources = 400 cells
About 20 events

I'm using this code to update the events for each resource, and I'm afraid that it makes the memory overload.

```
setTimeout(function () {
                var cal = $('#calendar');
                if (cal.fullCalendar('getResources').length == 0) {
                    for (d in areas) {
                        cal.fullCalendar('addResource', areas[d]);
                    }
                }
                cal.fullCalendar('removeEvents');
                cal.fullCalendar('addEventSource', bookings);
                cal.fullCalendar('rerenderEvents');
            }, 1000)
```

I hate iPad very much because everything works well in Android and Windows but iPad. The problem is everyone wants to use iPad. ;)

**Comment by arshaw** [comment]
hmm it's impossible to know whether it's a memory issue without some profiling in place. Could you [create a runnable JSBin](http://fullcalendar.io/wiki/Reduced-Test-Cases/) with the exact code that is running improperly.

That calendar should easily handle that... 10 days and 40 cells will equate do only 50 dom nodes with the way the code renders, and 20 events is pretty small.

**Comment by rongxike** [comment]
i will create a jsbin a.s.a.p. 10 days x 40 resources = 400 cells. approx. 20 events

**Comment by rongxike** [comment]
I found the error:

{ text: 'start', value: function (row) { return moment(row.arrival_date).format('YYYY-MM-DD') + 'T00:00:00' } },

in iPad, moment.js doesn't understand this format '01/Jan/2016' when I tried to convert using above script

**Comment by arshaw** [comment]
ah ok, glad you figured it out
