### ISSUE TITLE
RANGES features not working

### ISSUE THREAD

**Issue by flaracca** [fullcalendar/fullcalendar-scheduler#189]
Hello,
I am using the recurring events features but unfortunately RANGES do not work.

In the followin bin: [http://jsbin.com/xijeqi/1]

the event on the 13th of June should not be displayed but it is.

Can you help?

Thanks.

**Comment by arshaw** [comment]
Can you point me to some documentation on this "RANGES" feature? I'm not aware of it.

**Comment by flaracca** [comment]
Good to know. I thought I was being utterly stupid... :)
Have a look at this JSfiddle: [http://jsfiddle.net/duu0dx2t/415/]

Honestly I looked for bu didn't find any docs about it

**Comment by arshaw** [comment]
i honestly don't know if/how that example is working

**Comment by flaracca** [comment]
Alright then. May I trouble you for my issue, please?
I need to add exceptions to recurring events. Example:
I am available every monday of the year from 10 to 18. I am not available the 20th and 27th of June.
How can this be done?

**Comment by arshaw** [comment]
no problem @flaracca. Recurring events is currently not supported. Here is the feature request ticket:
https://github.com/fullcalendar/fullcalendar/issues/387
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by flaracca** [comment]
Hi Adam, I am actually using BusinessHours features to manage availability. Is there a way to add exceptions to it?

**Comment by arshaw** [comment]
@flaracca, no that's currently not possible. My best recommendation is to compute the date/times of your business hours and send them down as [Background Events](http://fullcalendar.io/docs/event_rendering/Background_Events/) via a [custom events functions](http://fullcalendar.io/docs/event_data/events_function/).
