### ISSUE TITLE
Is there any way to hide non-business hours on the scheduler?

### ISSUE THREAD

**Issue by cavneb** [fullcalendar/fullcalendar-scheduler#19]
It would be wonderful if we were able to hide non-business hours from the scheduler. Is this possible? If not, can you point me in the right direction?

**Comment by espen** [comment]
1) This is for issues, not questions. Please see http://fullcalendar.io/support/

2) See http://fullcalendar.io/docs/agenda/minTime/ and http://fullcalendar.io/docs/agenda/maxTime/
