### ISSUE TITLE
Selection triggered on scrollbars after valid selection

### ISSUE THREAD

**Issue by Tol1** [fullcalendar/fullcalendar-scheduler#192]
After first valid selection, select callback is triggered on scrollbars with old data.
Steps to reproduce:

1. http://jsbin.com/bedocigesu/edit?js,console,output
1. Trigger valid selection on some resource
  - Console outputs data from selection
1. Without clicking anywhere else, click or scroll on either scrollbars
  - Console outputs same data as after valid click

**Comment by arshaw** [comment]
I can confirm this. thanks

**Comment by arshaw** [comment]
this has been fixed and released in [v1.3.3](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.3.3)
