### ISSUE TITLE
Settings to disallow event changing of resources

### ISSUE THREAD

**Issue by JalalSordo** [fullcalendar/fullcalendar-scheduler#193]
There should be a setting which disallows events from changing resource (via drag-n-drop)

**Comment by arshaw** [comment]
Issue #50 deals with more complex logic of which resources are available to which events, but it seems like we neglected to thoroughly discuss the most simple case, the case of prevent events from changing resources altogether.

There should be a very simple flag setting for this. Thanks for your feature request.

**Comment by arshaw** [comment]
my apologies. seems you already found the dup ticket:
#140
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
