### ISSUE TITLE
Cannot read property 'clone' of undefined.

### ISSUE THREAD

**Issue by alannaidon** [fullcalendar/fullcalendar-scheduler#197]
I'm getting this error while trying to update an event inside a `Success ajax callback`.  
In this example I just tried to edit it's background. What I'll really do is change it's ID/ClassName then refresh the calendar.  

Just click in the button.
[JsBin](https://output.jsbin.com/suyako)  

This is what I'm getting with `clientEvents`:   

https://postimg.org/delete/6zf1f8xl2/

**Comment by arshaw** [comment]
you have a bunch of problems with this part:

```
    var evento = $('#calendar').fullCalendar('clientEvents', function(event){
      return event.nameClass == "abc";
    });
```

misspelling of "nameClass"

also, the clientEvents method returns an *array*, NOT an individual event
