### ISSUE TITLE
Use 'background' instead of 'background-color'

### ISSUE THREAD

**Issue by MartijnWelker** [fullcalendar/fullcalendar-scheduler#199]
By using `background` instead of `backgroundColor` things such as linear-gradients will become possible. This is useful for when you want to display a time before/after the event in a different color (such as travel time).

Example with start time: 
![screen shot 2016-07-22 at 16 02 25](https://cloud.githubusercontent.com/assets/6674662/17059495/bece93cc-5025-11e6-9d9b-a138b1a42e26.png)

Example with start and end time:
![screen shot 2016-07-22 at 16 05 08](https://cloud.githubusercontent.com/assets/6674662/17059563/222511bc-5026-11e6-9d00-3c3b4b64b2f7.png)

**Comment by arshaw** [comment]
you want this to be a new property on an [Event Object](http://fullcalendar.io/docs/event_data/Event_Object/) ?

**Comment by MartijnWelker** [comment]
The Event object currently has the property `backgroundColor`, in the actual code this will be set as `background-color` we could either use the current `backgroundColor` property to set `background` behind the scenes (which might cause confusion), or as you stated use a new property (which I like more)

**Comment by arshaw** [comment]
in the meantime, you can achieve this with: http://fullcalendar.io/docs/event_rendering/eventRender/

**Comment by arshaw** [comment]
this is a job for `eventRender`
