### ISSUE TITLE
Add an event with "renderEvent" does not work with FullCalendar Scheduler on timelineDay

### ISSUE THREAD

**Issue by Ch0uk** [fullcalendar/fullcalendar-scheduler#2]
Hi everyone !

First, I would like to thank all of you for this amazing plugin !
However, I noticed a small bug on the new version... or maybe I 'm doing wrong :-/

I need to add an event when I select a slot time in a timelineDay view. So, I do this : 
* I add `selectable` option for this view :
```javascript
views: {
    timelineDay: {
        selectable: true
    }
}
```
* and in the `select` callback, I create an event and I want to add and **display immediately** on my fullcalendar. I use ajax to save in my database, and it works, but the event is not displayed, I must do `refetchEvents` for that the event appears. Here's how I created my event (in the `success`) :
```javascript
select: function(start, end, jsEvent, view, resource) {
...
var newevent;
$.ajax({
    url: Routing.generate('...'),
    data: {
        event_id: id,
        event_title: resource.title,
        event_start: start,
        event_end: end,
        event_agent: resource.id
    },
    type: 'POST',
    dataType: 'json',
    success: function(response){
        newevent = 
        {
            id: response.eventid,
            _id: response.eventid,
            title: resource.title,
            start: start,
            _start: start,
            end: end,
            _end: end,
            allDay: false,
            editable: true,
            agent: resource.id,
            constraint: 'businessHours',
            color: resource.eventColor
        };
        $('#calendar').fullCalendar('renderEvent', newevent, true);
        $('#calendar').fullCalendar('addEventSource', newevent);
        $('#calendar').fullCalendar('refetchEvents');
    },
    error: function(e){
        console.log(e.responseText);
    }
});
$('#calendar').fullCalendar('unselect');
return true;
}
```
I tested `renderEvent` in agendaWeek and it works, the event is directly displayed (just using renderEvent) ! So I suppose this is a bug of scheduler ?

Thanks in advance ! And sorry for my english, I'm french...
Regards

**Comment by Ch0uk** [comment]
Shame on me ! This is a rookie mistake...

As I do not use `resourceId`, I added the option `eventResourceField: 'idAgent'` , but in the creation of my event, I wrote 'agent' and not 'idAgent' !

Sorry for the useless post...
And thanks again for this great plugin that does not cease to amaze me !

**Comment by mmouracarvalho** [comment]
In results of your ajax request you need to pass event array with different attributs lets a exemple:

$('#calendar').fullCalendar('renderEvent', {
                id: retorno['id'],
                title: retorno['title'],
                start: moment(retorno['start']),
                end: moment(retorno['end']),
                allDay: retorno['allday']
            });

you wrote event_id its wrong, the correctly is only id 

Refer
https://fullcalendar.io/docs/event-object
