### ISSUE TITLE
dd and tt do not work for slotLabelFormat

### ISSUE THREAD

**Issue by woodburn8** [fullcalendar/fullcalendar-scheduler#20]
dd and tt do not work for slotLabelFormat.  d and t work fine. 
Reference:  http://fullcalendar.io/docs1/utilities/formatDate/

I have not tested all possible formats, so there may be others not working.

**Comment by arshaw** [comment]
are you sure it's not because you are using the outdated format? the docs you have posted are for fullcalendar 1.x.

fullcalendar 2.x and scheduler use this:
http://fullcalendar.io/docs/utilities/date_formatting_string/
(a superset of MomentJS's formatting characters)
