### ISSUE TITLE
[Request/Help] Able/Disable resource button

### ISSUE THREAD

**Issue by arca223** [fullcalendar/fullcalendar-scheduler#200]
Hello !

My problem is to give the user two views : with Resource and without.
Before I had agendaWeek and agendaDay without resource, working perfectly. I implemented the timeline + resource and now, my agendaDay is showing with resource. This is not what I expectµ

I'd need to show the normal agendaDay (without resource) and the timeline (with resource)

Came to me this idea : A way to able/disable the resources. Some kind of checkbox

(Is there also a way to switch between two resources ?)

Thanks for your answers. I did not find much info on the docs and find myself many questions around this

**Comment by arshaw** [comment]
there is a poorly documented trick to achieve what you want. please read: https://github.com/fullcalendar/fullcalendar-scheduler/issues/115
