### ISSUE TITLE
Resources businessHours leak in other views.

### ISSUE THREAD

**Issue by Tirke** [fullcalendar/fullcalendar-scheduler#204]
JsBin showing issue : http://jsbin.com/mekefuvube/edit?js,output

Really simple, if you switch from the vertical Resource view (agendaDay) to the agendaWeek view, the resources business hours will be shown instead of the normal businessHours object.
Issue is also visible when you set defaultView to agendaWeek and then switch to agendaDay and back again to agendaWeek.

I think I have narrowed the issue in this part of the logic : 

```
getCurrentBusinessHourEvents: (wholeDay) ->
        flatResources = @resourceManager.getFlatResources()

        # any per-resource business hours? or will one global businessHours suffice?
        anyCustomBusinessHours = false
        for resource in flatResources
            if resource.businessHours
                anyCustomBusinessHours = true

        if anyCustomBusinessHours
            # if there are any custom business hours, all business hours must be sliced per-resources
            allEvents = []
            for resource in flatResources
                events = @computeBusinessHourEvents(wholeDay, resource.businessHours or @options.businessHours)
                for event in events
                    event.resourceId = resource.id
                    allEvents.push(event)
            allEvents
        else
            super
```

Currently, you are not checking the view anywhere.
So anyCustomBusinessHours is always true, and the else block is never executed after the user switch to a Resource view for the first time.
Quick fix is to check view type && anyCustomBusinessHours, but I don't think you'll resolve it this way, it's too specific and dirty ...

**Comment by arshaw** [comment]
Got it. So you'd expect no resource-derived business hours to display in a non-resource view? Makes sense.

**Comment by Tirke** [comment]
Yes, I think it’s more right and consistent to rely on the global business hours Object when we switch to a non-resource view.

**Comment by arshaw** [comment]
this has already been fixed in a recent version since you reported the bug (probably scheduler 1.7.0 and core 3.5.0)
working jsbin:
http://jsbin.com/fihefeliwu/1/edit?html,output
