### ISSUE TITLE
External events can be dropped outside fc-time-area

### ISSUE THREAD

**Issue by rvenk** [fullcalendar/fullcalendar-scheduler#205]
Dropping an external event on the invisible part of the time-area (ie. the whole scroller-canvas) now also creates this event in the scheduler.

This is easily reproducible in the demo: 
http://fullcalendar.io/js/fullcalendar-scheduler-1.3.3/demos/external-dragging.html
1. Scroll the time-area all the way to the end.
2. Drag **event 2** 2px to the right. (To trigger JQuery draggable)
3. Release **event 2**.

**Event 2** is now added to **Auditorium A** at 7:30am. (on full resolution that is)

My scheduler also has the events next to the time-area, so I am constantly planning invisible events by error.

The version I upgraded from: v1.1.0
The version I upgraded to: v1.3.3

**Comment by arshaw** [comment]
reproduced, thanks.

note to self, problem happening here:
https://github.com/fullcalendar/fullcalendar-scheduler/blob/v1.3.3/src/timeline/TimelineGrid.coffee#L241
`containerCoordCache` needs to resemble the scroller (not the canvas), and needs to check for both horizontal and vertical bounds.

**Comment by rvenk** [comment]
This is fixed in 1.6.0
