### ISSUE TITLE
Scheduler not showing future events after certain date

### ISSUE THREAD

**Issue by gdolenc** [fullcalendar/fullcalendar-scheduler#206]
I have implemented scheduler few months ago and everything was working fine until a week ago, when some future events after certain date are not displayed on the calendar. 

I use MySQL db as background for data feed. Everything is fine with data, it is just not displayed.

I have not changed the code recently, so I wonder what could be the problem.

Here is the link of implemented calendar: http://www.slotenis.si/rezervacije/?lid=2

**Comment by arshaw** [comment]
![screen shot 2016-08-15 at 9 47 48 pm](https://cloud.githubusercontent.com/assets/56520/17688201/edf97cce-6331-11e6-9025-805250c2e6c1.png)

look like your ajax request is limiting to 500 events, preventing the events past 2016-08-15 from being received.
