### ISSUE TITLE
Image for resources

### ISSUE THREAD

**Issue by Dalton-James** [fullcalendar/fullcalendar-scheduler#207]
It would be great for us if we could pass an image with the resource object and have that displayed next to the resource name. 
We are using this to schedule employees and seeing faces can be much easier than finding names.

**Comment by arshaw** [comment]
@Dalton-James I might implement an icon feature, but probably not the near-terms. however, you can achieve what you describe by using the `resourceRender` hook:
http://fullcalendar.io/docs/resource_rendering/resourceRender/
