### ISSUE TITLE
Add 'dist' folder to allow installation with Composer-Asset-Plugin

### ISSUE THREAD

**Issue by holtkamp** [fullcalendar/fullcalendar-scheduler#21]
We currently rely on [https://github.com/francoispluchino/composer-asset-plugin](the Composer-Asset-Plugin) to install bower assets using [https://getcomposer.org](Composer). Unfortunately this tool seems not to be able to 'build' the FullCalendar Scheduler package.

The result is that the FullCalendar asset IS installed properly (a 'dist' folder already exists in the repository with all the required files), but the FullCalendar-Scheduler asset can NOT be installed (no 'dist'). [I filed an issue for this](https://github.com/francoispluchino/composer-asset-plugin/issues/147), a temporal solution might be to include a 'dist' folder in the tagged repo of FullCalendar-Scheduler?

Might be slightly related to https://github.com/fullcalendar/fullcalendar-scheduler/issues/16

**Comment by arshaw** [comment]
when fetching fullcalendar-scheduler via bower, whether through composter-asset-plugin or not, nothing should need to be build. it should come pre-loaded with the build .js file in the dist/ directory. If you are not receiving those files, it seems that you are probably targeting an incorrect semver version number, and thusly not getting the dist files (regardless of what bower.json says).

i'm also trying to understand if and why composer-asset-plugin processes the bower.json differently. if this is the case, it is the responsibility of the composer-asset-plugin to fix it. I am hesitant to adjust fullcalendar-scheduler's code in order to work around another project's issues.

**Comment by holtkamp** [comment]
Indeed, the source of the problem is in the way of how composer-asset-plugin uses Symfony Finder to determine which files to remove as indicated in the ```ignore``` section. I understand the hesitation, but in terms of consistency, would it "hurt" to streamline the ```ignore``` section of the two projects by making them the same? And by doing so allowing more people to easily adopt them in their projects, thereby increasing the probability of adoption, increasing the probability for using the premium version of the FullCalendar Scheduler ;), just my 2 cents.

- https://github.com/fullcalendar/fullcalendar/blob/2f5476944b67f74e8d5cf7a660b228122f255ee6/bower.json#L45-L52
- https://github.com/fullcalendar/fullcalendar-scheduler/blob/fafb4d739987ed974eb4b6253ef2793f36a98fcf/bower.json#L28-L35

**Comment by arshaw** [comment]
hmm, i didn't realize that the core fullcalendar project was using `dist/**`. i assumed i did what i did in fullcalendar-scheduler for real reasons but i guess not. okat

**Comment by arshaw** [comment]
released in v1.0.1. please let me know if it doesnt work for some reason

**Comment by holtkamp** [comment]
Great, thanks for taking the effort to dive into this. 

The following dependency now results in a complete checkout when using https://github.com/francoispluchino/composer-asset-plugin with: ```"bower-asset/fullcalendar-scheduler": "~1.0",```

```
 Installing bower-asset/fullcalendar (v2.4.0)
    Loading from cache
    Extracting archive

    REASON: bower-asset/fullcalendar-scheduler v1.0.1 requires bower-asset/fullcalendar >=2.4.0 -> satisfiable by bower-asset/fullcalendar[v2.4.0, dev-master].

  - Installing bower-asset/fullcalendar-scheduler (v1.0.1)
    Downloading: 100%         
    Extracting archive

```

Resulting file structure:
![screen shot 2015-10-13 at 10 45 16](https://cloud.githubusercontent.com/assets/776405/10450003/913cba3c-7197-11e5-8d58-62314c04b83b.png)

**Comment by arshaw** [comment]
great. so looks good, right?

**Comment by holtkamp** [comment]
perfecto, thanks!

**Comment by Efiware** [comment]
Fantastic - thank you for solving this.
