### ISSUE TITLE
Filter resources based on user input

### ISSUE THREAD

**Issue by harohl** [fullcalendar/fullcalendar-scheduler#211]
I am trying to filter the resources in the calendar based on a user input.  Ideally I would read an array or JSON of resources upon page load.  Then, a client function would filter the rows based on a multi-select of resources.  I am thinking it might be best to just show or hide the rows (columns if a Vertical Resource view).  A second best solution would be to re-render the grid.

I'm not sure if this is possible with this type of code.  I could use an example of how to implement this.
resources: function(callback) {
    somethingAsynchonous(function(resourceObjects) {
        callback(resourceObjects);
    });
}
And, if I was able to filter the resources, I am not sure if I would need to re-fetch the events or if the extra ones would just be hidden due to the missing or hidden resource rows.

If we need to do this on the server side, I am not sure how to pass a parameter to the Resource object function.  The data property work when sending it to the events URL, but gets an error when trying to send to the resource URL.

There seem to be a variety of requests related to this type of requirement, but I have not found a solid example of how to do this with existing functionality.  And, I did not find any solid expectations on when this feature would be available.

**Comment by arshaw** [comment]
communicated over email. pseudocode to workaround:

```
resources: function(callback) {
	var filteredResources = filterResources(resJSON);
	callback(filteredResources);
}
```
