### ISSUE TITLE
Multiple businessHours for each resource

### ISSUE THREAD

**Issue by RicardoEmpre** [fullcalendar/fullcalendar-scheduler#212]
Is it possible to have multiple businessHours for each resource?

The problem I have is, for some resources, they change their businessHours like once every 1 or 2 months:
for example, resource 1 works, from 2016-01-01 to 2016-03-31 on mondays and tuesdays from 8 - 13, and then from 2016-04-01 to 2016-06-15 on other daysOfWeek/hours and so on. (This app will work with agendaDay/agendaWeek as in [this example](https://fullcalendar.io/js/fullcalendar-scheduler-1.3.3/demos/vertical-resource-view.html) from the docs).

So it would be great to have an array of arrays of businessHours like this:

```javascript
$('#calendar').fullCalendar({
    // not showing other options for brevity
    resources: [
        {
            id: 'a', 
            title: 'Jhon Doe' ,
            businessHours: [
                [ 
                    start: '2016-01-01',
                    end: '2016-03-31',
                    hours: [
                        {
                            dow: [ 1, 2], 
                            start: '08:00' 
                            end: '13:00' 
                        },
                        {
                            dow: [4]
                            start: '10:00',
                            end: '16:00'
                        }
                    ]
                ],
                [ 
                    start: '2016-04-01',
                    end: '2016-06-15',
                    hours: [
                        {
                            dow: [ 1, 2], 
                            start: '09:30' 
                            end: '12:30' 
                        },
                        {
                            dow: [4,5,6]
                            start: '10:00',
                            end: '12:00'
                        }
                    ]
                ],
                [ 
                    start: '2016-06-16',
                    end: 'infinity',
                    hours: [
                        {
                            dow: [1, 2], 
                            start: '10:00' 
                            end: '13:00' 
                        },
                        {
                            dow: [3,4]
                            start: '10:00',
                            end: '16:00'
                        }
                    ]
                ],            
            ]
        }
    ];
});
```

**Comment by arshaw** [comment]
i should document this better, but yes, now possible as of a recent version:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/61#issuecomment-236464468

**Comment by RicardoEmpre** [comment]
Maybe I'm not being clear, **sorry**, I'm asking for something like #61 but with a twist, a little more complicated. (I'm not seing nothing in [the](https://fullcalendar.io/docs/resource_data/businessHours-per-resource/) [docs ](https://fullcalendar.io/docs/display/businessHours/) that says it's possible what i'm asking).

What I'm asking is if it is some way to have an array of the actual businessHours array, **with start/end dates in which each businessHour array are valid**, to model something like, for resource a, he works from 2016-01-01 to 2016-02-15 in some days/hours, from 2016-02-16 to 2016-05-30 in some other hours, and so on and so on.

Now, the only way I found to do this, is check the date on ViewRender, and call to refetchResources with new businessHours for the resource if its necesary, but its kinda convoluted.

**Comment by arshaw** [comment]
It's possible to [specify multiple definitions](https://github.com/fullcalendar/fullcalendar/issues/2686) in an array, but unfortunately it is not yet possible to specify beginning/ending time ranges for the recurrence rule, which is what you want.

Once recurring events have more proper support, you will get this behavior for free in businessHours. The ticket:
https://github.com/fullcalendar/fullcalendar/issues/387
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
