### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by MrChoclate** [fullcalendar/fullcalendar-scheduler#213]
fullcalendar has types hosted at DefinitelyTyped (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/fullCalendar/fullCalendar.d.ts).

It will be great if fullcalendar-scheduler could provide the same feature.

**Comment by arshaw** [comment]
Wow I didn't realize there was a contributor-based project for such a thing. There is probably not enough bandwidth to tackle this in the near-term. Would be great if someone else could handle this.

**Comment by arshaw** [comment]
related: https://github.com/fullcalendar/fullcalendar/issues/3889

**Comment by arshaw** [comment]
fyi, looks like some of this is already written in definitelytyped: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/fullcalendar/index.d.ts#L142-L147

**Comment by arshaw** [comment]
as of v1.9.1, a typescript definition file is automatically generated.
https://github.com/fullcalendar/fullcalendar-scheduler/blob/v1.9.1/dist/scheduler.d.ts
