### ISSUE TITLE
v1.4.0 of FullCalendar Scheduler is incompatible with v<%= meta.version %> of the core.

### ISSUE THREAD

**Issue by HemantRana09** [fullcalendar/fullcalendar-scheduler#215]
### Bug Reports
You MUST have a JSBin recreation, or else your issue will be CLOSED without explanation.
Instructions: http://fullcalendar.io/wiki/Reporting-Bugs/

### Feature Requests
Search the issue tracker for an existing ticket before creating a new one.
Instructions: http://fullcalendar.io/wiki/Requesting-Features/

(Please erase the above text and begin typing. Thanks!)

**Comment by HemantRana09** [comment]
I am new in Jquery and also in Github. Sorry if posted in wrong place.
I am using the Full calendar feature and it's really awesome everything is working perfect. Thanks for the awesome functionality Arshaw. 
Now i want to show the vertical timeline view. When reading the doc i cam to know it's licensed but by reading more i found i can use it for free trial so i started using it the scheduler library but every time i am adding resource i am getting this error- "v1.4.0 of FullCalendar Scheduler is incompatible with v<%= meta.version %> of the core."
Can you please help me in that and also can you please tell me what should my company do to access the full feature of Vertical View of full Calendar.
Thanks, in advance.

**Comment by arshaw** [comment]
If you upgrade to [v3.0.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.0.0) of the core project, that error should go away.

**Comment by HemantRana09** [comment]
So if i upgrade to V3.0.0 will i be able to see the timeline view?
If yes then what's more in the License version.

**Comment by arshaw** [comment]
Scheduler is the add-on that is required for timeline view (latest is v1.4.0)

Scheduler requires the *core fullcalendar code* to be on the page at the same time (v3.0.0 is the latest)

they are separate packages that are related.

**Comment by HemantRana09** [comment]
Ok cool.... Got your point thanks a lot for the quick reply.
Sorry,  but just a last question.
If i use both the v1.4.0 and v3.0.0 at the same time will i be able to
create this view without buying the license-

[image: Inline image 1]

**Comment by arshaw** [comment]
I can't see the image. I don't think github allows images via email. you'll need to comment on the issue in the github interface

**Comment by HemantRana09** [comment]
I was talking about this image on this link---

https://fullcalendar.io/scheduler/

**Comment by arshaw** [comment]
Oh ok. No, that is timeline resource view, and is only available via the "premium" plugin. More about license info: https://fullcalendar.io/scheduler/license/

**Comment by HemantRana09** [comment]
Thanks a lot Adam for the response.
Your calendar is awesome.
