### ISSUE TITLE
scheduler - bottom row gridline missing

### ISSUE THREAD

**Issue by harohl** [fullcalendar/fullcalendar-scheduler#216]
The lower gridline of my last resource schedule row is missing when the number of resources does not fill the entire div.  I attached a print screen.  Is this a known issue?

![fcschedule_rowlinemissing](https://cloud.githubusercontent.com/assets/19411389/18319709/e13f9520-74f4-11e6-971b-049ca571aa90.jpg)

**Comment by arshaw** [comment]
thanks. this is a dup of:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/162
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by harohl** [comment]
Thanks.  I looked to see if it was in the list.  I’m not sure how I missed that.
