### ISSUE TITLE
Resource different by date

### ISSUE THREAD

**Issue by steveboulay** [fullcalendar/fullcalendar-scheduler#217]
Hello,
Is it possible to have differents resources by date ?
Maybe have a new data in Resource Object that would be a date and if not present resource will be for all days like today.

Best regards
Steve Boulay

**Comment by arshaw** [comment]
hi @steveboulay , this ticket, when implemented, will allow for requerying resources based on date:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/12
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
