### ISSUE TITLE
Clickable day headers in scheduler views (navLinks) 

### ISSUE THREAD

**Issue by darioseidl** [fullcalendar/fullcalendar-scheduler#218]
Hello!
First off, great job on the scheduler! It will be a central piece to our web app, and it's working really well for us so far.
I was checking out the new fullcalendar 3.0.0 and the [navLinks](https://fullcalendar.io/docs/mouse/navLinks/) are neat.
However, it seems they are not implemented for the timeline views in fullcalendar-scheduler (1.4.0). They are working in the list views, for example.
I was wondering if you're planning to implement them, or if you have any hints on how I could add that myself?

**Comment by SirDre** [comment]
You could try this quick fix however, other modifications are required to make it more seamless.

FIND THIS:
`html += '<th class="' + this.view.widgetHeaderClass + ' ' + (cell.weekStart ? 'fc-em-cell' : '') + '"' + ' data-date="' + cell.dateData + '"' + (cell.colspan > 1 ? ' colspan="' + cell.colspan + '"' : '') + '>' + '<div class="fc-cell-content">' + '<span class="fc-cell-text">' + htmlEscape(cell.text) + '</span>' + '</div>' + '</th>';`


REPLACE WITH THIS:
`html += '<th class="' + this.view.widgetHeaderClass + ' ' + (cell.weekStart ? 'fc-em-cell' : '') + '"' + ' data-date="' + cell.dateData + '"' + (cell.colspan > 1 ? ' colspan="' + cell.colspan + '"' : '') + '>' + '<div class="fc-cell-content">' + '<span class="fc-cell-text">' +
 
					this.view.buildGotoAnchorHtml(  
						{ date: cell.dateData, type: 'week' },
						htmlEscape(cell.text) 
					)  

		 + '</span>' + '</div>' + '</th>';
` 

Hope this helps for now.

**Comment by darioseidl** [comment]
Awesome, thank you very much!

I ended up modifying the src instead of dist, so that I could install the changed version with npm.
In TimelineGrid.coffee, line 445, I replaced `htmlEscape(cell.text) +` with
`(if @opt('navLinks') then @view.buildGotoAnchorHtml({ date: cell.dateData }, htmlEscape(cell.text)) else htmlEscape(cell.text)) +`.

**Comment by arshaw** [comment]
impressive workarounds. i will try to get this is an a real feature.

**Comment by arshaw** [comment]
released in [v1.5.0](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.5.0)
