### ISSUE TITLE
Resource state resets on changing option

### ISSUE THREAD

**Issue by MartijnWelker** [fullcalendar/fullcalendar-scheduler#219]
JSBin: http://jsbin.com/daxatunori/1/edit?js,console,output

Close the resource and press the `Set slot duration` button, you will see that the resource opens again, it would be desired behaviour to keep the closed state of resources when settings options.

It would be also nice to have the state as a property on the resource so you can extract it with `getResources`

**Comment by arshaw** [comment]
hi @MartijnWelker, the first issue you bring up is best captured in this ticket:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/42
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
