### ISSUE TITLE
Doesn't use scrollTime from default settings

### ISSUE THREAD

**Issue by espen** [fullcalendar/fullcalendar-scheduler#22]
Have to specify scrollTime in timelineDay view specific option. Should use default scrollTime just like for example agendaDay does.

**Comment by arshaw** [comment]
you sure? i made a recreation, and when the calendar-wide scrollTime is not specified, both timelineDay and agendaWeek assume the default (6am), and when a calendar-wide value is specified, it seems to apply to both views (to 2am in the example). can you double check?

http://jsbin.com/jilago/edit?js,output

**Comment by arshaw** [comment]
it could be related to this issue: https://github.com/fullcalendar/fullcalendar-scheduler/issues/25
