### ISSUE TITLE
Selection always triggered on vertical scrollbars

### ISSUE THREAD

**Issue by kimpixel** [fullcalendar/fullcalendar-scheduler#220]
select callback is triggered on scrollbars

Fullcalendar Version 3.0.0
Scheduler Version 1.4.0

Testet in FF and Chome

http://jsbin.com/burorivaqe/edit?html,js,console,output

click on the vertical scrollars always trigger "select" callback

**Comment by arshaw** [comment]
recreated. thanks

**Comment by arshaw** [comment]
this looks fixed with the latest releases:
http://jsbin.com/kufemixayi/edit?html,output
