### ISSUE TITLE
Multiple events with shared ID reschedule together

### ISSUE THREAD

**Issue by breaker1055** [fullcalendar/fullcalendar-scheduler#226]
http://jsbin.com/ninozecewe/edit?js,console,output

With multiple events that share an ID:
When changing start or end time, or moving one of the events, all events that share an id get the same update. Expected behavior would be that only the event being changed should be effected. It could be a setting on individual events: sharedIdEventsResheduleTogether:false

When moving an event to a different resource, they all move to the new resource; this behavior is probably correct for the default case.  It should probably be a setting whether all events that share an id will move together or allow them to split on resources. sharedIdEventsMoveToResourceTogether:true

**Comment by breaker1055** [comment]
Just some thoughts on this.
I'm also interested in issue #111 and I've been thinking about these similar problems.
Maybe a structure of multiple start/end times with a single resourceId could replace both resourceIds as an array and multiple events that share a single ID field.

So perhaps an event would require either a start and a resourceId or some number of this structure.
complexSchedule:[{ start:moment, end:moment, resourceId:'rId' }, ... ]

**Comment by arshaw** [comment]
#111 probably encompasses the bulk of this discussion, yeah
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

We'll discuss proposed API changes in ticket. A flag might be the solution. Or maybe a more complex object, not sure. Can you continue the discussion on #111 ?
