### ISSUE TITLE
Drag and drop question - allow droping only on specific resource group or resource ID

### ISSUE THREAD

**Issue by roulendz** [fullcalendar/fullcalendar-scheduler#227]
Hello, awesome people!
I was wondering and thinking
Is it possible to specify, if specific event can be dropped on specific resource group or specific resource id?

When I am using drag and drop.

Thanls

**Comment by sparh** [comment]
Hi there,
you can have a look here https://fullcalendar.io/docs/resource_events/eventConstraint/

**Comment by roulendz** [comment]
@sparh 
This far I got, 
But I can not figure out how I implement this inside my html, because i am dragging html element on to calendar

```
<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 col-xl-3 fc-event ui-draggable ui-draggable-handle draggable" data-backgroundcolor="blue" data-duration="06:00:00" data-lesson-id="5" data-eventcolor="rgb(255,0,0)">
				Test
			</div>
```

I have 
```
data-backgroundcolor="blue"
```
to set color

I have
```
data-duration="06:00:00"
```
to set durration

I have
```
data-lesson-id="5"
```
To set correct id of event from database

and how would I go with eventConstraint

```
constraint: {
                resourceIds: [ 'a', 'b', 'c' ] // constrain dragging to these
            }
```

Thanks

**Comment by arshaw** [comment]
if you need something more programmatic, you can use eventAllow:

https://fullcalendar.io/docs/resource_events/eventAllow/
