### ISSUE TITLE
Provide the created Event object in the dropAccept callback

### ISSUE THREAD

**Issue by breaker1055** [fullcalendar/fullcalendar-scheduler#228]
Requesting some way to modify external events after they're accepted and before they're added to the calendars cache.

My use case is to force events to have an ID but I'm sure there would be others.
Using the event callback, drop: is too late, the calendar already has the event created.
Using dropAccept: is not great, If you modify the $(element).data('event') it changes the external element and will create duplicate IDs on subsequent drops.

I think two options would be a decent solution
Provide the Event object the calendar will add to the dropAccept callback, it would be modifiable ahead of being added.
Or
Add an event that fires in between dropAccept and the calendar getting a hold of the new event object. providing the created event object that is about to be added to the calendar, available for modification. beforeDropEventAdded: function(event){}

My janky workaround is to use a setTimeout and reset the dropped elements event.id after 200ms.
dropAccept : function( element ){
	var event = $(element).data("event");
	if( !event.id ){
		event.id = ++idIndex;
		$(element).data( "event", event );
		setTimeout( function(elem){
			var event = $(elem).data("event");
			event.id = null;
			$(elem).data("event", event);
		}, 200, element);
	}
	return true;
}

**Comment by arshaw** [comment]
I would leverage `dropAccept` like you're doing, but make sure your DOM elements DON'T have the `event` data, which ill prevent the event from automatically being created upon drop. Put your event data in some other property. Then, have your `dropAccept` callback call `renderEvent` ([docs](https://fullcalendar.io/docs/event_rendering/renderEvent/)]. That way you'll have complete control.
