### ISSUE TITLE
How to add two days event in scheduler?

### ISSUE THREAD

**Issue by shahzadthathal** [fullcalendar/fullcalendar-scheduler#23]
Hi,

I have tried add two days event into scheduler but it is not showing this event! 
Can you help me please how is it possible?

I did this too!
e.g
start date = 2015-09-10 00:00:00 (today date)
end date =  2015-9-11 23:59:59
it shows the event in 2015-09-10 00:00:00 but when I clicked on left top arrow for next day, event disappeared there! 

Any solution?

**Comment by espen** [comment]
See http://fullcalendar.io/docs/timeline/customizing_duration/

Also see regarding support/questions: http://fullcalendar.io/support/

**Comment by arshaw** [comment]
would you mind posting a jsbin recreation? instructions here:
http://fullcalendar.io/wiki/Reporting-Bugs/

will allow me to debug

**Comment by arshaw** [comment]
will keep closed until i see the recreation. thanks!
