### ISSUE TITLE
 Problem with Performance in Calendar of Resources

### ISSUE THREAD

**Issue by rodrigofieldeas** [fullcalendar/fullcalendar-scheduler#234]
Hi

We have a project with your library and we have a problem with performance when library paint components Resources, Jobs and Work Shifts.

In our solution now it spents between 8 and 15 seconds drawing this data.

Code example
http://jsbin.com/nijiza

**Comment by espen** [comment]
That renders in about 2,5 seconds here. That's a lot of resources btw. There might be some areas of improvement in FC for this but you might want to consider doing some filtering yourself (do you really need to show everything?)

**Comment by arshaw** [comment]
@rodrigofieldeas, to handle that number of resource, one of these two techniques would ideally be employed:
[timeline continuous scroll](https://github.com/fullcalendar/fullcalendar-scheduler/issues/129)
[timeline resources pagination](https://github.com/fullcalendar/fullcalendar-scheduler/issues/141)
&uarr;
Please pick the issue(s) that seem most appropriate, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by rodrigofieldeas** [comment]
Yes I need show all resources, because is a big bussiness team.

Resource pagination is not a good solution for me because app user hasn’t the visibility.

For the continuous scroll solution do you have a code example?

Best regards


De: Espen Antonsen [mailto:notifications@github.com]
Enviado el: jueves, 17 de noviembre de 2016 7:19
Para: fullcalendar/fullcalendar-scheduler <fullcalendar-scheduler@noreply.github.com>
CC: Rodrigo Martín Saiz <rodrigo.martin@fieldeas.com>; Author <author@noreply.github.com>
Asunto: Re: [fullcalendar/fullcalendar-scheduler] Problem with Performance in Calendar of Resources (#234)


That renders in about 2,5 seconds here. That's a lot of resources btw. There might be some areas of improvement in FC for this but you might want to consider doing some filtering yourself (do you really need to show everything?)

**Comment by arshaw** [comment]
@rodrigofieldeas sounds like continuous scroll is what you'd want. It's a feature that is not yet implemented, and thus I don't have any code to show you, sorry.
