### ISSUE TITLE
Keep vertical scrolling on navigation

### ISSUE THREAD

**Issue by sparh** [fullcalendar/fullcalendar-scheduler#238]
Hello
when we click on Prev/Next button the Vertical scroll is reset to 0.
Would it be possible to keep the vertical scroll value when navigating between days.

To reproduce go to https://fullcalendar.io/scheduler/
Scroll the calendar to the bottom to see "Auditorium Z", then click on the Prev or Next button.
The scroll value is lost.

Thanks in adavnce

**Comment by arshaw** [comment]
Thanks for this report. This used to work. Is a regression. I've poinpointed the version...

works: https://fullcalendar.io/js/fullcalendar-scheduler-1.3.2/demos/simple.html
doesn't work: https://fullcalendar.io/js/fullcalendar-scheduler-1.3.3/demos/simple.html

**Comment by arshaw** [comment]
will be fixed in the next version

**Comment by arshaw** [comment]
fixed and released in [v1.5.0](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.5.0)

**Comment by arshaw** [comment]
works: https://fullcalendar.io/js/fullcalendar-scheduler-1.5.0/demos/simple.html
