### ISSUE TITLE
Remove Day name in timelineMonth

### ISSUE THREAD

**Issue by aroon9002ahmed** [fullcalendar/fullcalendar-scheduler#241]
Hello 
how i can remove Day name in timelineMonth, i need to show 30 days on the screen ( without scroll ) or i can make day cell smaller
![vcv](https://cloud.githubusercontent.com/assets/7735634/20930906/e7530f58-bbd7-11e6-8ec0-1868ec4851ce.png)

Thank you

**Comment by aroon9002ahmed** [comment]
oky i done with this , i just wont to disable day click

**Comment by arvenmanalo** [comment]
Hi aroon and arshaw, May I know how to solve this problem. thanks in advance
