### ISSUE TITLE
Show Resource Names in Week View

### ISSUE THREAD

**Issue by garyhalb** [fullcalendar/fullcalendar-scheduler#243]
It would be great if the vertical resource rendering supported rendering the resource names even in the Week view. I know this would get cramped with multiple resources, but most of the commercial Schedulers support this view and a large portion of my clients use it too.

Something along these lines:
![scheduler](https://cloud.githubusercontent.com/assets/24471279/21041123/c2c3e7a4-bdf1-11e6-93b3-21005b6e342d.jpg)

**Comment by arshaw** [comment]
is this not possible with [groupByResource](https://fullcalendar.io/docs/vertical_resource_view/groupByResource/)?

it might be cramped, and if so, you'll be responsible for making sure the container has enough width.

ps- [this ticket](https://github.com/fullcalendar/fullcalendar-scheduler/issues/110) requests scrolling
pps- will reopen this ticket if necessary

**Comment by garyhalb** [comment]
In the demo for Vertical Resource view here (https://fullcalendar.io/js/fullcalendar-scheduler-1.5.0/demos/vertical-resource-view.html), when you select the Week view the column grouping disappears and appointments are all shown in a single column. As below:

![resource](https://cloud.githubusercontent.com/assets/24471279/21090089/01d870da-c046-11e6-905a-42ea694ebc10.jpg)

If this a configurable setting perhaps that I have missed?

**Comment by arshaw** [comment]
https://fullcalendar.io/docs/vertical_resource_view/getting_started/

> If you would like resource column functionality in a multi-day view, which is turned off by default, you'll need to activate either the groupByResource or groupByDateAndResource flags.

it's easy to miss that in the docs tho

**Comment by garyhalb** [comment]
Ah, thank you - kind of glossed over bit that while running with the demo.

**Comment by austinPatel** [comment]
Is there any way to display Resource in Horizontally fo Week View and Month View
We are using this plugin but some of feature like Google Calendar Week View and Month View With Left Panel Resources which with CheckBox those who are check will display his Events.

Please let me know i tried lots of things but not come out with solution
Thank You
