### ISSUE TITLE
11:30pm Problem in Full Calendar

### ISSUE THREAD

**Issue by minhajhussain1993** [fullcalendar/fullcalendar-scheduler#248]
Hello

I am facing an issue with full calendar that when ever i try to register an event on 11:30pm slot, the slot of 11:30pm is filled as well as the next day s slots from 12:00am to 1:00am also gets filled. i cant figure out this. plz help

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by minhajhussain1993** [comment]
Hey Adam,

I can show you screenshots of the bug that i faced, you can see them below.
it occurs on 11:30pm whenever i make event on 11:30pm to 12:00am the event
covers next day's 1:am too

**Comment by MinhajMJ** [comment]
![15540426_1161385403981480_951355193_o](https://cloud.githubusercontent.com/assets/10099864/21311262/2d378770-c59b-11e6-8ef5-671d220781a8.png)
![Uploading 15555154_1161385407314813_921232441_o.png…]()

**Comment by MinhajMJ** [comment]
![15555154_1161385407314813_921232441_o](https://cloud.githubusercontent.com/assets/10099864/21311407/e9e35db8-c59b-11e6-929b-9480873088bd.png)

**Comment by arshaw** [comment]
any way you can post a [runnable test case](https://fullcalendar.io/wiki/Reduced-Test-Cases/)? the cause of this is not immediately obvious to me. Might be daylight savings related. What timezone are you in?

**Comment by minhajhussain1993** [comment]
Pakistan Time Zone UTC+05:00 hours
