### ISSUE TITLE
Set width in scheduler view

### ISSUE THREAD

**Issue by guireg** [fullcalendar/fullcalendar-scheduler#252]
Hi,

We are currently testing FullCalendar Scheduler module on our application. Everything is perfect except that I can't manage to reduce its width.

AspectRatio setting gives us the ability to reduce/enlarge the height but nothing is possible to reduce width. On 13" screen, we have an horizontal scroll which is annoying like you can see on sample : https://fullcalendar.io/scheduler/ 

Would it be possible to have a dayWidth setting for example which enables you to set the width of one square inside the scheduler ? Or a width parameter like "height" which set the total width of scheduler ?

Cheers,

Guireg

**Comment by arshaw** [comment]
i believe slotWidth is what you're looking for: https://fullcalendar.io/docs/timeline/slotWidth/

plz let me know if it is not applicable.

**Comment by guireg** [comment]
Hi !

I already tried this setting but it's not resizing the width of the scheduler. No matter if I'm putting slotWidth: 2, slotWidth: "2px" or slotWidth:"2%" , it keeps the same original width which is way too large for many screens.

**Comment by arshaw** [comment]
Hmm, it doesn't work? Here's a demo where I've set `slotWidth:2` and it behaves as expected: http://jsbin.com/vuruneluwo/1/edit?js,output
