### ISSUE TITLE
Resources is not in a fixed position?

### ISSUE THREAD

**Issue by nguyenchitien195** [fullcalendar/fullcalendar-scheduler#254]
![image](https://cloud.githubusercontent.com/assets/18318660/21601143/2383c3d6-d1b9-11e6-97e8-82d252d1f5ae.png)
![image](https://cloud.githubusercontent.com/assets/18318660/21601156/4801e170-d1b9-11e6-905d-131539d0bdc7.png)
![image](https://cloud.githubusercontent.com/assets/18318660/21601178/757944d6-d1b9-11e6-9b5b-9a24487d3e70.png)

My calendar: header resources moves when i scroll, it is not in a fixed position ???
Please help me, thanks!

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
