### ISSUE TITLE
Clicking on vertical scroll bar of timeline causes dayClick event

### ISSUE THREAD

**Issue by harohl** [fullcalendar/fullcalendar-scheduler#256]
I am using the timeline view.  When a user clicks on the grid, I use the dayClick event to open up a dialog for creating a new schedule.  When the user clicks on the vertical scroll bar, the dayClick event is being triggered.  It seems that this should not happen.

**Comment by arshaw** [comment]
fix implemented here: https://github.com/fullcalendar/fullcalendar-scheduler/tree/fix-dayClick-scrollbar

**Comment by CraigHoneyfieldIS** [comment]
Is there anyway to fix this using css or jQuery?  I don't want to upgrade to a new version of the fullcalendar control right now.

**Comment by atilleul** [comment]
@arshaw I'd like to know the due date/release date of version 1.5.1. ? I'd like to update our company's Scheduler lib to the latest version but if you're gonna publish a 1.5.1 version with fixes (including this one) in the forthcoming days, I'd rather wait than start updating our FC components today.
Thanks to let me know ;)

**Comment by arshaw** [comment]
i hope to make a release with this fix this weekend

**Comment by atilleul** [comment]
@arshaw Would be extremely well-timed!! ;)

**Comment by arshaw** [comment]
Released in [v1.5.1](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.5.1)
