### ISSUE TITLE
Vertical scroll for timelineWeek ?

### ISSUE THREAD

**Issue by zulander1** [fullcalendar/fullcalendar-scheduler#258]
Hello,
I have a timeline timelineWeek with a slotDuration or 24 hours (one day),   is there a way i can i have Horizontal scroll with a duration of 14 days ? essentially have two-week or more ?

http://jsbin.com/bayegufofe/1/edit?js,output

EDIT: Made a mistake meant horizontally

**Comment by arshaw** [comment]
I think you are requesting a new feature. Could you provide a visual mockup of what you want?

**Comment by arshaw** [comment]
are you requesting something like this? https://github.com/fullcalendar/fullcalendar-scheduler/issues/261

**Comment by zulander1** [comment]
Maybe, 
perhaps i can explain more with the imge
Each event slot is 24 hours, in this viewport have 11 days.  you can see the scrollbar, it will allow me to scroll to another 3 days'.
![image](https://cloud.githubusercontent.com/assets/12099546/22006214/37dda512-dc37-11e6-8f6b-3e21bd05e3bc.png)

just like timelineDay where you have 10 hours in your viewport then you can scroll Horizontally to have the remaining hours.

does it make more sense ?

Thank's
P.S.: Great job on the calendar and scheduler

**Comment by zulander1** [comment]
So after looking around i cam to this http://jsbin.com/fofegi/3/edit?js,output
this is what i want to do ! but for two week

**Comment by arshaw** [comment]
yes, it's possible to achieve that with a [Custom View](https://fullcalendar.io/docs/views/Custom_Views/) with that is `type: 'timeline'` and a `duration` of your choosing.

**Comment by L0rDPSYCH0** [comment]
I am still interested in this, if this could become a possibility. I would even pay for something like this. I am working on a calendar but where events can start in one day and end in another. I need to show timeslots also but since I am using this in a mobile device, vertical scrolling is kind of the way to go...
