### ISSUE TITLE
scheduler callback problem, it doesn't work

### ISSUE THREAD

**Issue by hddung89** [fullcalendar/fullcalendar-scheduler#259]
This my options

> resources: function (callback) {			    
> 			    $.ajax({
>                     url: "<%= ResolveUrl("~/DesktopModules/hvgXinNghi/Services/LoadResources.asmx/LoadNhanSu") %>",
> 			        type: "POST",			        
>                     dataType: "json",
>                     data: GetResourceParam(),
>                     success: function (data) {                        
>                         var resourceObjects = data;
>                         callback(resourceObjects);
>                     },
>                     error: function () {
>                         generate(position, container, 'Error Loading !', 'error', false);
>                     },
> 			    }); }

I using resources as function but callback doesn't work as it in the events as function.
Anyone can help me pls ?

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
