### ISSUE TITLE
incompatible with momentjs version 2.1.0

### ISSUE THREAD

**Issue by dingzj** [fullcalendar/fullcalendar-scheduler#26]
Got incompatible issue with earlier version of momentjs 2.1.0
tried to fix, and too complicated logic to know how to fix.

Not sure other versions, but your example are using 2.9.0, that works.

**Comment by espen** [comment]
Well 2.1.0 is an old version (two years ago it seems). I don't see how this is an issue?

See changelog of momentjs here: https://github.com/moment/moment/blob/develop/CHANGELOG.md

**Comment by arshaw** [comment]
the minimum required version of moment is 2.5.0. this is in the bower.json and package.json, so package managers should respect this.
