### ISSUE TITLE
Event with several phases

### ISSUE THREAD

**Issue by ThomasGmas** [fullcalendar/fullcalendar-scheduler#262]
### Feature Requests
Every Event consists of 1 to n Phases. Each Phase has it’s own color, Hachures or image jpeg/animated-gif. (see attachment. I have corrected the Row headers from Category to Phase in the Popup-Window for editing the phases).
Tooltip for each phase.

Thanks in advance for your efforts!
Regards!

![scheduler](https://cloud.githubusercontent.com/assets/24961243/22053803/47bd2df0-dd53-11e6-9a16-de24e8eb3227.jpg)

**Comment by espen** [comment]
It's possible to create this yourself using a [custom view](https://fullcalendar.io/docs/views/Custom_Views/).

**Comment by ThomasGmas** [comment]
Many thanks for the information.

**Comment by arshaw** [comment]
Gantt chart functionality is out of Scheduler's current scope, but you might be able to hack something together with [eventRender](https://fullcalendar.io/docs/event_rendering/eventRender/).

**Comment by ThomasGmas** [comment]
Great hint, many thanks!
