### ISSUE TITLE
The timeline starts with the incorrect of the day in mode of the month

### ISSUE THREAD

**Issue by AnnaKuzova** [fullcalendar/fullcalendar-scheduler#269]
Hello!

New ticket from this ticket: https://github.com/fullcalendar/fullcalendar/issues/3538
In our calendar the timeline starts with the incorrect of the day in mode of the month.
In other modes correctly
I have attached screenshot https://drive.google.com/file/d/0BwzedJ6VKLxWbzJKbEkwVThCUnM/view?usp=sharing, https://drive.google.com/drive/folders/0BwzedJ6VKLxWUVVmWmg5TTc0cmM?usp=sharing

**Comment by arshaw** [comment]
What do you mean incorrect day? The month looks like February, and it's showing Feb 1st as the first day, and showing it as a Wednesday. All of that is correct, no?

**Comment by tlays11** [comment]
I too would like it to start with the current day.
For example in the timelineYear view it will start with January 1st and they have to scroll to the current date. Neither .fullCalendar('today'), nor .fullCalendar( 'gotoDate', date ) scroll horizontally to the current day.

**Comment by AnnaKuzova** [comment]
For example, the issue PRO-1091 should start on Monday, but starts from mid of Sunday
I add it to the calendar on Monday

**Comment by arshaw** [comment]
Ah ok.

@tlays11 sounds like you want the view to start at the current date. there's already a ticket in the core tracker for that:
https://github.com/fullcalendar/fullcalendar/issues/2847

@AnnaKuzova sounds like you want it to start at the beginning of the week instead the beginning of the month. This new proposed feature addresses that:
https://github.com/fullcalendar/fullcalendar/issues/3113

Could you please visit the links, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

Those new features will be part of the next release.
