### ISSUE TITLE
Reopen issue 74 - Lots of resources breaks the resource view order and doesnt append scrollbars to the bottom of the view

### ISSUE THREAD

**Issue by OliverDolan** [fullcalendar/fullcalendar-scheduler#271]
I have done some searching and it would seem issue 74 might not be resolved in the latest builds.

Link to similar/same issue:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/74

I believe I have reproduced it in the following jsBin's
http://jsbin.com/pijokucaci/edit?html,js,output

also adding resource order:
http://jsbin.com/doyawotiwo/edit?html,js,output

The main issue is it's difficult to read the data efficiently as the resource columns are very small

**Comment by arshaw** [comment]
i made a comment here: https://github.com/fullcalendar/fullcalendar-scheduler/issues/74#issuecomment-284121285

> The fix was that if no resourceOrder is specified, it should render the resources in the order they were specified. This seems to be correctly happening in your first demo

If you have further questions/responses, please write them on this ticket.

closing.

**Comment by OliverDolan** [comment]
In my opinion this should not be closed as the resource names are ineligible and they cannot be understood even when adding the resource order. The column headings become too small to read or use the information presented. Please take a look in the examples above to see what I was indicating at, maybe the issue is not the same as the original issue though

**Comment by arshaw** [comment]
@OliverDolan , this is issue is probably the one you'll want:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/110
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
