### ISSUE TITLE
eventLimit

### ISSUE THREAD

**Issue by foxpad** [fullcalendar/fullcalendar-scheduler#272]
Hey @arshaw

I need your help.
It is necessary to make the eventLimit for several events for a certain time.
For example, if I have 5 events for time 8 to 8.15, then I have to see one event to the number of events or a hyperlink such as eventLimit on month.
I use agendaWeek and I each hour is divided into 4 portions.

Sincerely, foxpad.

**Comment by arshaw** [comment]
I'm not sure the the UI would look like for your request. Where would the "more" link be located on the screen? A mockup would be really helpful.

My instincts tell me you should use `agendaDay` view instead. There will be more room.
