### ISSUE TITLE
Right click on fullcalendar

### ISSUE THREAD

**Issue by shubham19bhatt** [fullcalendar/fullcalendar-scheduler#273]
I tried to use this code for context-menu in fullcalendar:-

 element.bind('contextmenu', function(e)
                                     {
						               
						                alert('Right clicking');
						                //showContextualMenu(event, element, e);
						                $("#contextual-menu").css({
								             'position':'fixed',
								             'top':e.clientX,
								             'left':e.clientX,
								             'z-Index':999999
								         });
						            });
that alert is coming but after that no context-menu appears.

How can we add options in context menu?

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by shubham19bhatt** [comment]
We are using this functionality in salesforce. We can paste our code here, but for running it you may need to make several changes.
