### ISSUE TITLE
time bar issue with horizontal scroll.

### ISSUE THREAD

**Issue by kiranp0** [fullcalendar/fullcalendar-scheduler#274]
i am just testing scheduler with 100's of resources, 
my calender is in <div class=col-md-12>
so it break the design, so what i had done is 
if resources are greater than 4 ,then multiply them with 25 i.e. $width
then i set that $width to class `.fc-view-container .fc-view `. now its fine.
but issue  when i horizontal scroll to no5 resource ,
time-bar is also scrolled.

**Comment by OliverDolan** [comment]
is it the same issue I raised here?
https://github.com/fullcalendar/fullcalendar-scheduler/issues/271

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by kiranp0** [comment]
why it is close ?

basically i need to frees time column in recurse view while scrolling left to right
