### ISSUE TITLE
Min/max Time is not considered when filtering events within range (more than 24 hours)

### ISSUE THREAD

**Issue by DriesVandermeulen** [fullcalendar/fullcalendar-scheduler#275]
Hi, 

When I set the `minTime` and `maxTime`options to be more than 24 hours apart the scheduler nicely displays the correct range. This more than 24 hour option was added by in v1.2.1 #112 . 

The problem is that these options are not considered when filtering out the events in the `filterEventsWithinRange` function. The events that are outside the 24 hour range are assumed to be invalid events and are thus filtered out. 

Here is a [Bin](http://jsbin.com/jejabetigo/embed?js,output) demonstrating the problem.

Event 1: Start and end between 24:00 range **(shown)**
Event 2: Start between 24:00 range, the end is outside **(still shown)**
Event 3: Start and end outside the 24:00 hour range  **(not shown)**

**Comment by arshaw** [comment]
https://github.com/fullcalendar/fullcalendar/issues/2530
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
