### ISSUE TITLE
 Rerender calendar

### ISSUE THREAD

**Issue by shubham19bhatt** [fullcalendar/fullcalendar-scheduler#276]
We are trying to implement **Fullcalendar** in **salesforce**. We are facing a situation where we need to **refetch** all the updated events from the dataBase and render them to the calendar. We are not able to use **refetchEvents** as we need to fetch the updated events from dataBase. Please suggest some approach.

**Comment by arshaw** [comment]
if your event source IS a feed URL, or a custom function, it will be executed/fetched when refetchEvents is called.
