### ISSUE TITLE
custom eventConstraint but keep global businessHours

### ISSUE THREAD

**Issue by VIEWSION** [fullcalendar/fullcalendar-scheduler#280]
I try to assign custom constraint settings by defining resourceIds to a drop event... works fine like expected. I also use global businessHours - individual for each ressource. Unfortunately this will be overwritten / ignored as soon as I define a custom eventConstraint.

I guess it is more an enhancement than a bug... it would be great to set an eventConstraint but respect the global businessHours if set. Or to deal with resourceIds as well as business hours within the eventConstraint setting.

I know I can handle this with 'eventAllow', but it is more a workaround than a solution:

```
...
eventAllow: function(dropLocation, draggedEvent) {

	var bHStart	= this.businessHours.start;
	var bHEnd	= this.businessHours.end;
	
	var res = $(#myCalendar).fullCalendar( 'getResourceById', dropLocation.resourceId);
	
	if(res.businessHours){
	
	    bHStart = res.businessHours.start;
	    bHEnd	= res.businessHours.end;
	
	}
	
	bHStart	= moment.utc(bHStart, "HH:mm");
	bHEnd	= moment.utc(bHEnd, "HH:mm");
	
	return dropLocation.start.isSameOrAfter(bHStart) && dropLocation.end.isSameOrBefore(bHEnd);
}
...
```

**Comment by arshaw** [comment]
Hmm, if `eventConstraint: "businessHours"` and an `eventAllow` function is specified, both should be respected. I would consider it a bug otherwise.

Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)?
