### ISSUE TITLE
Drag Start/Stop for creating a new event

### ISSUE THREAD

**Issue by harohl** [fullcalendar/fullcalendar-scheduler#281]
Currently I create a new event with the dayClick event.  I use the clicked area on the calendar as the start time and just default the length.  It would be really cool to allow the user to drag their mouse over the calendar to create the event.  This would work similar to drawing a block in paintbrush.  This would allow the user to set the start and end time based on where the drag started and stopped.

**Comment by arshaw** [comment]
Pretty sure you are describing selection:
https://fullcalendar.io/docs/selection/
