### ISSUE TITLE
How to scroll to today in timelineMonth view

### ISSUE THREAD

**Issue by qweluke** [fullcalendar/fullcalendar-scheduler#284]
Hi,

Here is example code:
http://jsbin.com/ronociriku/1/edit?js,output

question is: how to automatically scroll (horizontally) to current day?

**Comment by arshaw** [comment]
dup of:
https://github.com/fullcalendar/fullcalendar/issues/861
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
