### ISSUE TITLE
Persian Calendar

### ISSUE THREAD

**Issue by mahdiidea** [fullcalendar/fullcalendar-scheduler#285]
Can i use your calendar in persian date (jalili) ?

**Comment by qweluke** [comment]
@mahdiidea 
have you checked one of these?
https://www.versioneye.com/javascript/ehsandanesh:persian-fullcalendar/2.5.0
https://github.com/fullcalendar/fullcalendar/issues/3267
http://stackoverflow.com/questions/10952938/jquery-fullcalendar-to-persian

**Comment by arshaw** [comment]
See https://github.com/fullcalendar/fullcalendar/issues/1813
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by SM-hosseini** [comment]
those codes not working
those codes is related to fullcalendar, no fullcalendar-scheduler
