### ISSUE TITLE
dateIncrement not working when  duration and dateincrement have different units

### ISSUE THREAD

**Issue by ajay12thwonder** [fullcalendar/fullcalendar-scheduler#287]
### Bug Reports
When we create a custom view and specify the duration and dateIncrement with different units, the forward and previous navigation is not working.

http://jsbin.com/tiyoyefohi/edit?js,output

When a view is defined as below, the navigation does not work
timelineCustomMonth: {
        type: 'timeline',
        duration: { **months**: 1 },
        dateIncrement: {**days**:7}
      }
however, when I specify 
timelineCustomMonth: {
        type: 'timeline',
        duration: **{ days: 30 },**
        dateIncrement: {days:7}
      }
then it works.

**Comment by arshaw** [comment]
reproduced. thanks.

**Comment by arshaw** [comment]
fixed by these commits:
https://github.com/fullcalendar/fullcalendar/commit/be185fda11c39749f7d9d0481a7832d07e08f144
https://github.com/fullcalendar/fullcalendar/commit/bd2ab7ad2f6e4ddf32348a8eab8bb2f585ab7ed5

will be release very soon

**Comment by arshaw** [comment]
updated fiddle with correct behavior: http://jsbin.com/koloqunete/1/edit?html,output

ps- if you specify `dateIncrement: {weeks:1}`, it will align with the start of the week

**Comment by arshaw** [comment]
Released in [fullcalendar-scheduler 1.6.1](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.6.1) and [fullcalendar 3.3.1](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.3.1)

**Comment by arshaw** [comment]
Related bug I found along the way: #289 
Use your own [titleFormat](https://fullcalendar.io/docs/text/titleFormat/) as a workaround.

**Comment by ajay12thwonder** [comment]
@arshaw 
Thanks for prompt  fix.

**Comment by htinou** [comment]
Bug is there again. You can see it on your  jsbin : http://jsbin.com/koloqunete/1/edit?html,output

Choose you custom month view and click next twice... it won't work more than once.
