### ISSUE TITLE
After render event for resources

### ISSUE THREAD

**Issue by florian-interaktiv** [fullcalendar/fullcalendar-scheduler#288]
Hey there,

would be great to have a callback after all resources have been rendered.
Just like "eventAfterAllRender" => resourceAfterAllRender.

Cheers :)

**Comment by arshaw** [comment]
I actually plan to deprecate `eventAfterAllRender` because it gets murky when subset of events get rerendered. I encourage use of `eventRender` only.

Could you explain your usecase? What do you want to do when all resources are rendered?

**Comment by tmercado** [comment]
I could use this too, So that after all the resources render, I can store references to the resource objects to mimic their height.

**Comment by camilovietnam** [comment]
I am trying to add a FontAwesome icon to the resource header columns and I think having resourceAfterAllRender would be useful for my case, I could fetch the headers and append the html in that function.
