### ISSUE TITLE
Add to CDN just like fullcalendar package

### ISSUE THREAD

**Issue by holtkamp** [fullcalendar/fullcalendar-scheduler#29]
`fullcalendar` is conveniently hosted at [cdnjs.com](https://cdnjs.com/libraries/fullcalendar) also discussed at the [download page](http://fullcalendar.io/download/). This would be great to have for`fullcalendar-scheduler` as well...

**Comment by Rastalamm** [comment]
+1 for this

**Comment by theinventor** [comment]
yes please +1

**Comment by caseyjhol** [comment]
See https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library

**Comment by arshaw** [comment]
i think auto-update is the preferred method:
https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

i will get to this pretty soon

**Comment by JamesValleyT** [comment]
+1 Not this is specilaly relevant because you want a JSBin before looking at issues/bug reports ...... I'm now trying to make a JSBin to chase down a possible problem with schuduler but I can't find a CDN!

**Comment by JamesValleyT** [comment]
For anyone else who finds this from Google .... I found one!

- https://fullcalendar.io/js/fullcalendar-scheduler-1.6.1/scheduler.min.css
- https://fullcalendar.io/js/fullcalendar-scheduler-1.6.1/scheduler.min.js 

:-P

(Seriously, I suspect they wen't be happy if you use that as a real CDN)

**Comment by acrollet** [comment]
+1, any movement on this?

**Comment by arshaw** [comment]
this was completed a little while ago:

https://cdnjs.com/libraries/fullcalendar-scheduler
