### ISSUE TITLE
Change day name rendering

### ISSUE THREAD

**Issue by qweluke** [fullcalendar/fullcalendar-scheduler#290]
My code: http://jsbin.com/xozadofije/1/edit?js,output

How to change day name rendering?
I want to achive sometnig like this:

```
<div class="dayName">Fri</div>
<div class="dayNumber">31</div>
```

**Comment by arshaw** [comment]
this other ticket captures what you want:
https://github.com/fullcalendar/fullcalendar/issues/3331
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
