### ISSUE TITLE
Timezone attribute of fullcalendar is not working 

### ISSUE THREAD

**Issue by shubham19bhatt** [fullcalendar/fullcalendar-scheduler#292]
We are using fullcalendar  in Salesforce where we tried to use its inbuilt attribute 'Timezone' which is not working. We are using many of the attributes like 'Weekends' ,'alldaySlot' and 'editable' etc. 
 Kindly please update on this if it is possible to use timezone of any region over the world.

**Comment by espen** [comment]
Kindly please follow the issue guidelines:

> ### Bug Reports
> You MUST have a JSBin recreation, or else your issue will be CLOSED without explanation.
> Instructions: http://fullcalendar.io/wiki/Reporting-Bugs/
> 
> ### Feature Requests
> Search the issue tracker for an existing ticket before creating a new one.
> Instructions: http://fullcalendar.io/wiki/Requesting-Features/
> 
> (Please erase the above text and begin typing. Thanks!)

As you can see at https://fullcalendar.io/js/fullcalendar-3.3.1/demos/timezones.html timezone is supported.

Also if this is not related to Fullcalendar Scheduler then go to https://github.com/fullcalendar/fullcalendar
