### ISSUE TITLE
Dynamic minTime and maxTime 

### ISSUE THREAD

**Issue by shubham19bhatt** [fullcalendar/fullcalendar-scheduler#293]
We are imlpementing fullcalendar in Visualforce pages salesforce, but we are facing a problem. We need different mintime ,maxtime  for timelineWeek and timelineDay.

We tried this approach:-
```
                 views: {
                    timelineWeek: {
                        slotDuration: '08:00:00',
                        filterStart: '00:00:00',
                        filterEnd: '23:59:59',
                    },
                    timelineDay: {
                    filterStart: '07:00:00',
                        filterEnd: '10:00:00',
                    },              
                },
```
but did not get any success. Please let us know if we need anything additional to be done.

**Comment by kurtfurbush** [comment]
The app we wrote is using agenda views and dynamically setting the minTime and maxTime. Could you set these options when your timeline type changes? Or are the times for timelineWeek and timelineDay "fixed" for each and you want to set them us as configuration, so you don't need to really change them dynamically to various values?

`.fullCalendar('option', { minTime: options.minTime(), maxTime: options.maxTime() })`

**Comment by arshaw** [comment]
@shubham19bhatt why would you expect that code to work? it has no reference to minTime or maxTime
