### ISSUE TITLE
When the context menu is selected How to get date??

### ISSUE THREAD

**Issue by drt0927** [fullcalendar/fullcalendar-scheduler#294]
https://jsfiddle.net/g9r26159/1/

When the context menu is selected

Now only the resource data is retrieved.

I want to get the date.

**Comment by espen** [comment]
Try StackOverflow. Please see https://fullcalendar.io/support/ regarding questions.

**Comment by arshaw** [comment]
when implemented, this feature will be useful to you:
https://github.com/fullcalendar/fullcalendar/issues/2430
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by lacmuch** [comment]
$('#yourfullcalendar').on('contextmenu',function(event){
var view = $('#yourfullcalendar').fullCalendar('getView');
var hit = view.queryHit(event.pageX,event.pageY);
var span = view.getHitSpan(hit);
//span.start is the date you clicked on
})
