### ISSUE TITLE
Removed background events come back when collapsing & expanding a resource

### ISSUE THREAD

**Issue by floriancargoet** [fullcalendar/fullcalendar-scheduler#295]
I think I've found a bug with background events and resource collapsing.

## Steps to reproduce:
- Add background event to a nested resource
- Remove the event, it correctly disappears from the view
- Collapse then expand the parent resource
- The event reappears!

Here's a demo of this bug: 
http://codepen.io/floriancargoet/pen/pemNNQ

**Comment by arshaw** [comment]
thanks for the repro.

**Comment by floriancargoet** [comment]
I have a quick fix but I'm not sure it's enough since I don't know the internals very well.
Anyway, here it is, it might point you in the right direction: the timeGrid doesn't have a `unrenderBgSegs` method so I added one that calls the super method and all rows' bgSegs to null.

```

**Comment by arshaw** [comment]
Released in [1.6.2](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.6.2).
