### ISSUE TITLE
Colour Weekends on scheduler View

### ISSUE THREAD

**Issue by mikedelvotti** [fullcalendar/fullcalendar-scheduler#298]
Guys,

I'm trying to colour weekends on the scheduler view but the normal code below doesn't seem to apply, 

.fc-sat, .fc-sun {
background-color: red !important;
}

is there another way to do this in a function of some sort?

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/)?

**Comment by mikedelvotti** [comment]
Hi, do you mean post the code on here, or a link to a working example?

When I use the code example above it works for colouring the weekends on the 'Month view' but not the scheduler timeline?

**Comment by arshaw** [comment]
coloring the fc-sat and fc-sun classNames will only work if your slotDuration is a single day. See this example: http://jsbin.com/karetubave/edit?js,output

**Comment by tringuyenxuan** [comment]
> Guys,
> 
> I'm trying to colour weekends on the scheduler view but the normal code below doesn't seem to apply,
> 
> .fc-sat, .fc-sun {
> background-color: red !important;
> }
> 
> is there another way to do this in a function of some sort?

can use 
	    td .fc-day-sun
	    {
	        background-color: lightgrey;
	    } 
         td .fc-day-sat { background-color:lightgoldenrodyellow; }
