### ISSUE TITLE
Business hours strange behavior

### ISSUE THREAD

**Issue by drango** [fullcalendar/fullcalendar-scheduler#299]
Hi Adam,

I have noticed a strange behavior and I'm not sure that this is desired (or at least it's not desired by me).

here is the jsfiddle: https://jsfiddle.net/drango/8o1k4u0b/6/

If we set the business hours for one resource for 4th day of week to: {dow: [3], start: "08:00", end: "17:00"} and we navigate to that day everything looks fine:

![image](https://cloud.githubusercontent.com/assets/9619748/25187395/294d7e34-2523-11e7-8961-7fabe7a9d48a.png)

If we switch to tree days timeline view, again everything is fine:

![image](https://cloud.githubusercontent.com/assets/9619748/25187471/67f7174e-2523-11e7-841f-1d33dbd9ea3f.png)

5th day of the week is marked as non-working.

Now if we go back to timeline day view and move the date to the 5th day of week, this day is marked as working:

![image](https://cloud.githubusercontent.com/assets/9619748/25187753/431d6f30-2524-11e7-95b2-a6b597e19404.png)

The strange behavior for me is that if on one view hours are marked as non-working this should be the case on all views.

I'm available if you need more info.

**Comment by drango** [comment]
@arshaw any comment on this issue?

**Comment by arshaw** [comment]
hi @drango it looks like you've discovered a bug. i'll take a look.

it reminds me of this older bug on core: https://github.com/fullcalendar/fullcalendar/issues/2944

**Comment by arshaw** [comment]
possible fix: #3652

**Comment by arshaw** [comment]
this was already fixed in fullcalendar 3.5.1 / scheduler 1.7.1
update working jsfiddle:
https://jsfiddle.net/8o1k4u0b/7/
