### ISSUE TITLE
Events not rendered if day changed in collapsed state (using grouping mode)

### ISSUE THREAD

**Issue by outofbounder** [fullcalendar/fullcalendar-scheduler#30]
This bug can be seen @ http://fullcalendar.io/js/fullcalendar-scheduler-1.0.0/demos/grouping.html

Note events present for resources B,C,D,E,F
1.Collapse '460 Bryant' group
2. Change the day forward, then backward so you land on today's date
3. Expand '460 Bryant' group
The events are not rendered in B,C,D,E,F

**Comment by arshaw** [comment]
released in v1.0.1. updated demo: http://fullcalendar.io/js/fullcalendar-scheduler-1.0.1/demos/grouping.html

**Comment by outofbounder** [comment]
Thanks for your hard work!
