### ISSUE TITLE
Review timezone related tests

### ISSUE THREAD

**Issue by wyleung** [fullcalendar/fullcalendar-scheduler#300]
Possible bug in tests:

https://github.com/fullcalendar/fullcalendar-scheduler/blob/master/tests/util/util.coffee#L77-L86

```
timezoneScenarios =
	'none':
		description: 'when no timezone'
		value: null
		moment: (str) ->
			$.fullCalendar.moment.parseZone(str)
	'local':
		description: 'when local timezone'
		value: 'local'
		moment: (str) ->
			moment(str)
```

I believe that the 'none' and 'local' scenario are switched based on the description given in the tests.

**Comment by arshaw** [comment]
nah, `none` means we want to use the timezone that the moment's string defines, which is what `parseZone` does. The statement `moment(str)` respects the *local* timezone.
