### ISSUE TITLE
Feature Request - Resource Image

### ISSUE THREAD

**Issue by davidwoods** [fullcalendar/fullcalendar-scheduler#305]
It would great if you could specify a resource image and or text on vertical or horizontal layouts

![concept](https://cloud.githubusercontent.com/assets/2377085/25584124/a96893a2-2e8c-11e7-88f2-3bd69c6003c9.jpg)

**Comment by NoNameWhatever** [comment]
That's a good idea because the Titles of resources gets all messy in this view.

**Comment by arshaw** [comment]
this is already possible with [resourceRender](https://fullcalendar.io/docs/resource_rendering/resourceRender/).

demo:
https://codepen.io/anon/pen/YVMayK?editors=0010
