### ISSUE TITLE
eventDrop add targetResourceId to event

### ISSUE THREAD

**Issue by CodeJason** [fullcalendar/fullcalendar-scheduler#306]
Hi,

We're in a situation where "staff" are the resources and an event can be assigned to more than one staff. Thanks to resourceIds, this is possible. 
When the event is dragged from one resource to another, the desired outcome is for the event to be duplicated in the other resource. 
When dragging an event with a single resource to another resource, inside eventDrop we can retrieve resourceId (send that to the server with the event id and add it to the event's resourceIds). But if the event is in two resources and is dragged to another (completely different) resource, it disappears from the other resource (which is fine), but we can't detect the resourceId and can't duplicate it. I realize the reason is that because it has more than one resource, it will update the resourceIds and the resourceId will remain null.

I've created a jsbin [here](http://jsbin.com/qomenebabu/edit?js,console,output)

If you drag event 1 to another resource, the console will log null (for resourceId), but not so with the other single events.

My proposal is to add a targetResourceId or something similar to find out which one it was dropped on.

**Comment by arshaw** [comment]
@CodeJason, I agree, it would be useful to know the resourceId's of the event being dragged: the resourceId before the drag and the resourceId as a result of the drag. Right now, there is no way to get this from the API.

**Comment by CodeJason** [comment]
Sure thing. 
Right now we are just duplicating the list of resources and then finding the one not present in the original.

Looking forward to the solution. 
Thanks for all the work.

**Comment by ablack83** [comment]
I was very surprised when I switched from single to multiple resources for events, to find that there there was no way to know the destination resource other than deducing it from the two arrays.  Please add this functionality.  It would be very much appreciated!

**Comment by arshaw** [comment]
this is now possible in v4
https://fullcalendar.io/docs/eventDrop
`oldResource.id` and `newResource.id`
