### ISSUE TITLE
Three day view with weekend: false doesn't always show three days

### ISSUE THREAD

**Issue by thomas479** [fullcalendar/fullcalendar-scheduler#307]
When I set the view of the fullcalendar scheduler to timelineThreeDays it correctly shows just three days.  
As I am browsing through different days the amount of days shown in the timeline sometimes becomes less then three.  
I think it has something to do with the `weekends: false`, because I can only reproduce it on a Friday.
The fiddle: https://jsfiddle.net/thomas479/0exd5wmz/ and the gif: http://i.imgur.com/W475mXt.gif

# How to reproduce in the fiddle:  
1. Move forward to the first Monday (eg. May 8). It will show Monday, Tuesday and Wednesday.
2. Move backwards one thick, it only shows Friday (I think because it wants to show Friday, Saturday and Sunday)

# Expected result:
After step 2 it should show Wednesday, Thursday and Friday

**Comment by arshaw** [comment]
the dayCount option will allow you to do what you want to do:
https://fullcalendar.io/docs/current_date/dayCount/

updated demo:
https://jsfiddle.net/0exd5wmz/1/
