### ISSUE TITLE
dragging events with same IDs, different resources, erases resource assignment

### ISSUE THREAD

**Issue by duetempi** [fullcalendar/fullcalendar-scheduler#308]
Hi,
Thanks very much to the contributors here.
I have a problem with an event with two resources.
When I drag and drop, or change the length of the appointment, graphically the event moves under the resource where the edit was made.
In the example that i tell you with jsbin you can try it with "event 1"

http://jsbin.com/fupuxeh/edit?js,output

![scheduler-1](https://cloud.githubusercontent.com/assets/22366073/25694733/3e4166aa-30b0-11e7-979c-6962be197724.png)
![scheduler-2](https://cloud.githubusercontent.com/assets/22366073/25694741/43b7b4fe-30b0-11e7-893c-b6e1a18bd0f1.png)
![scheduler-3](https://cloud.githubusercontent.com/assets/22366073/25694744/4a4e6056-30b0-11e7-9a3e-e87f13bc1f50.png)

Could you fix the bug?

Thank you

Giorgio

**Comment by arshaw** [comment]
the issue you describe is very similar to a previously resolved issue:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/111

The reason your case is different is because you are specifying two distinct event definitions with individual `resourceId` properties as opposed to a single event definition with an array of `resourceIds`.

So, here is a workaround:
http://jsbin.com/sucuzucujo/1/edit?js,output

However, what you've identified IS a legitimate bug that I will try to fix at some point.

**Comment by evanjmg** [comment]
@arshaw  is other event supposed to disappear and reappear on the other being dragged? That doesn't make sense - seems like a bug - makes my UI look glitchy

**Comment by arshaw** [comment]
@evanjmg what you mentioned in your most recent comment, that has been fixed in v1.7.0: https://github.com/fullcalendar/fullcalendar-scheduler/issues/155

**Comment by evanjmg** [comment]
👍

**Comment by arshaw** [comment]
Hi @evanjmg I have some questions that I'd really like the answers to:

- the problem you mentioned with 1.7, where the scroll gets out of sync... **is that happening on a touch device (iPad?) only?** If so, [there's already a report for it](https://github.com/fullcalendar/fullcalendar-scheduler/issues/339), and it seems to have been around for quite some time, prior to v3.5.0. If it's not a touch device, **could you please tell me what kind of browser you are using**?
- You said you don't like both events moving together as they drag. **What would you want instead?** Would you want the non-dragging event to stay put? If so, why even have them share the same ID if they are so unrelated?

**Comment by arshaw** [comment]
**note to self:** separate events with the same id's but different resourceId's now DO drag together. [demo](https://codepen.io/arshaw/pen/wqNwRG?editors=0010). and they keep their resource assignment as well. from my POV this bug is fixed.

**Comment by evanjmg** [comment]
@arshaw That jsbin is correct. Seems mine isn't doing the same behaviour, sorry about the confusion - I think I just need to remove some of my previous code.

**Comment by arshaw** [comment]
so... i think this is fixed then. closing

**Comment by evanjmg** [comment]
Yes that one is
