### ISSUE TITLE
Custom resource header renderer callback (fc-widget-header)

### ISSUE THREAD

**Issue by pgeyman** [fullcalendar/fullcalendar-scheduler#311]
I have a select element that I can filter resources, but I would like it to appear in the resources header cell (fc-widget-header), but there does not seem to be any callback renderer to be able to change the contents of the cell to custom content.

Please add a callback renderer that allows returning custom content to be used in the resources header cell.

**Comment by arshaw** [comment]
It is possible with [resourceRender](https://fullcalendar.io/docs/resource_rendering/resourceRender/)

See how I am inserting an image into the header...
https://codepen.io/anon/pen/YVMayK?editors=0010
