### ISSUE TITLE
cant read the JSON from Flask

### ISSUE THREAD

**Issue by lhzlhzvip** [fullcalendar/fullcalendar-scheduler#314]
Hi, I've tried all day long, but i can't find a problem with it.
the JSON from Flask work perfectly 
```
@app.route('/data/')
def return_data():
	conn = sqlite3.connect(D_appo)
	conn.text_factory = str
	c = conn.cursor()
	c.execute("SELECT * FROM appo_info")
	fetch = c.fetchall()

	for row in fetch:
   
		row[2]
		row[1]
		row[0]
	c.close()

	return jsonify(end=row[2],start=row[1],title=row[0])
```

and at ../data shows 
```
{
  "end": "2017-07-07 23:00:00", 
  "start": "2017-07-05 05:05:00", 
  "title": "lhzlhzvip"
}
```

i can see the calendar, but  the calendar didn't shows a event. 
here is the code:
```
		<script type="text/javascript">
			
			$(document).ready(function() {
				$('#calendar').fullCalendar({
                                               events: {
						url:'/data/',
						dataType: 'json',
						 }
				
				});
				
			});
		</script>
```

**Comment by espen** [comment]
Please ask questions on StackOverflow. See https://fullcalendar.io/support/

Here is an example of the JSON feed output: https://fullcalendar.io/js/fullcalendar-3.4.0/demos/php/get-events.php?start=2017-04-30&end=2017-06-11&_=1496133432559  Looks like your example is only for one event (which I am not sure would work), not an array of events.
