### ISSUE TITLE
Scheduler Timeline Week View - day separator

### ISSUE THREAD

**Issue by nick-goloborodko** [fullcalendar/fullcalendar-scheduler#315]
Hi,

I have not been able to find an easy way to demark the separation between days in the week timeline view. When scrolling it is very confusing for the users where one day ends and the next starts, especially when using custom minTime / maxTime.

Something as simple as having a thicker border between days would go a long way in improving the usability.

**Comment by arshaw** [comment]
dup of:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/245
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
