### ISSUE TITLE
Control vertical white space in timeline view

### ISSUE THREAD

**Issue by harohl** [fullcalendar/fullcalendar-scheduler#317]
A number of my users have complained about the row height of the resource rows on the timeline/scheduler view.  The white space makes the rows taller and thus limits the number of resources that can be viewed on the page.  While a small amount of white space is helpful for clicking on the grid (which creates new schedules in my interface), shrinking this space down would allow more resources to fit on the page for the larger clubs.

It would be nice if there was some kind of row height property that allowed you to specify by a percentage of the schedule height the amount of white space to use.

Using a percentage of the standard block height would not interfere with schedule stacking, which is why I would not want to actually set the row height.

**Comment by arshaw** [comment]
Some options for you:

write CSS to override the amount of whitespace between event. see the css statements at the bottom of the css pain in this codepen link: https://codepen.io/anon/pen/NgLOmb?editors=0110

have some sort of JS hook that does it. there's already some functionality like this in there:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/323
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by arshaw** [comment]
The biggest reason there is so much whitespace between rows by default is that the resource text on the left looks good with a comfortable amount of padding above and below. otherwise, it looks rather squished.
