### ISSUE TITLE
Multiple json ressources

### ISSUE THREAD

**Issue by Patatou** [fullcalendar/fullcalendar-scheduler#32]
Hi all,

I'm trying to add multiple json feed like this :
events: [
{
		url :'./json-plage.php'
	},
	{
		url :'./json-ressource.php'
	}
]

But, i've HasTime error... only work like this with one events json: 
events: {
		url :'./json-plage.php'
	},

Is it a know bug ?

Ty

**Comment by arshaw** [comment]
would you mind submitting a new bug report with a recreation demo? instructions here:http://fullcalendar.io/wiki/Reporting-Bugs/

it will be easy for you to start with "Scheduler Add-on: JSON feed template"
