### ISSUE TITLE
Empty resource json

### ISSUE THREAD

**Issue by alexsanro** [fullcalendar/fullcalendar-scheduler#321]
Hello, when I make a call to the database I return the resource empty, this is correct, since I do not want any column, but when I want to add with a empty resource some event, the selectable and editable event do not work, it's like If not noted. Does somebody knows why it could be?

**Comment by arshaw** [comment]
you might need to do `resources:false` to allow the user to select on the non-resources area

https://github.com/fullcalendar/fullcalendar-scheduler/issues/115
