### ISSUE TITLE
External event drag-n-drop causes errors in week and month views

### ISSUE THREAD

**Issue by rstoeber** [fullcalendar/fullcalendar-scheduler#325]
Here's a problem that's easy to see in the standard demo for fullcalendar-scheduler showing external event drag-n-drop here:

https://fullcalendar.io/js/fullcalendar-scheduler-1.6.2/demos/external-dragging.html

Placing an event properly onto the calendar requires grabbing an event from the far left and dropping it onto the correct room and time. However, the rooms (resources) are not displayed in either the week or month views.

The problem is that you can still drag an event onto the calendar in week and month view, but there's no way to select the room in those views so you're just creating errors. To see this in the demo linked above, go into Month view, drag an event over to the calendar and it appears where you dropped it. Now go back to the Day or 3 Day views and the event you just dropped is not visible since it's not associated with a valid room.

A good solution would appear to be using dropAccept with a function (something like if view=month return false), but dropAccept doesn't seem to know the current view.

If I'm reading the documentation correctly, both drop and eventReceive are called after it's too late and the event is already on the calendar, so I don't see a way to avoid this problem.

**Comment by arshaw** [comment]
It's still possible to get the current view in the dropAccept callback even when there's no param. See what I did here: https://codepen.io/anon/pen/GEexKx?editors=0010

```
    dropAccept: function() {
      var view = $('#calendar').fullCalendar('getView');
      return view.type === 'timelineDay';
    },
```
