### ISSUE TITLE
Using existing agenda views with scheduler

### ISSUE THREAD

**Issue by lesilent** [fullcalendar/fullcalendar-scheduler#326]
I've started playing around with the scheduler, and it's to my understanding that when you specify resources, it automatically changes agenda views to vertical resource view. Is there a way for these two different views to be coexist? I want to be able to give users the ability to continue using the current agendaDay view (where events are grouped by the date), but then also give them a button to change it to a vertical resource view (where events are grouped by resource columns). Maybe this can be done by creating separate views (eg. verticalAgendaDay and verticalAgendaWeek)?

**Comment by arshaw** [comment]
Yup, see this: https://github.com/fullcalendar/fullcalendar-scheduler/issues/115

Sorry, it's not really documented.
