### ISSUE TITLE
Fullcalendar-scheduler-1.6.2 Is it free to use?

### ISSUE THREAD

**Issue by stylehosting** [fullcalendar/fullcalendar-scheduler#327]
I'm going to use it on one website.
Fullcalendar-scheduler-1.6.2 Is it free to use?
No source modification and redistribution.

**Comment by espen** [comment]
Fullcalendar Scheduler is a paid add-on to the free Fullcalendar. See https://fullcalendar.io/scheduler/purchase/

**Comment by arshaw** [comment]
scheduler 1.6.2, as well as all other versions of scheduler are subject to these license terms: https://fullcalendar.io/scheduler/license/

**Comment by devframework-projects** [comment]
> Fullcalendar Scheduler is a paid add-on to the free Fullcalendar. See https://fullcalendar.io/scheduler/purchase/

thank you.

**Comment by stylehosting** [comment]
> Fullcalendar Scheduler is a paid add-on to the free Fullcalendar. See https://fullcalendar.io/scheduler/purchase/

thank you.

**Comment by stylehosting** [comment]
> Fullcalendar Scheduler is a paid add-on to the free Fullcalendar. See https://fullcalendar.io/scheduler/purchase/

thank you.
