### ISSUE TITLE
Scheduler - status indicator

### ISSUE THREAD

**Issue by martinbrowning** [fullcalendar/fullcalendar-scheduler#328]
Hi
It would be nice to have an easy way to indicate a specific status per event directly on the event view.
I currently make use of a specific borderColor to indicate a status, for example:

In scheduler to indicate payment status of a booking event like: Quoted, awaiting payment, partial payment, paid.

**Comment by espen** [comment]
Here is a few ways to achieve that:
* set className in the event object: https://fullcalendar.io/docs/event_data/Event_Object/.
* Add additional info or adjust the DOM on render using https://fullcalendar.io/docs/event_rendering/eventRender/. This can also be based on your own custom attributes on the event object.

I'm also going to implement something like that. But I'm guessing that user cases differ so much that's it's difficult to come up with a standard way of implementing this.

**Comment by arshaw** [comment]
thanks for the good answer @espen
