### ISSUE TITLE
Error from jQuery-ui draggable with hidden calendar

### ISSUE THREAD

**Issue by MartijnWelker** [fullcalendar/fullcalendar-scheduler#329]
When having a hidden calendar initialised and you start dragging a jQuery-ui draggable object FullCalendar will break and throw an error. This is caused because `slatCoordCache` is never made because `if (this.elementVisible())` doesn't pass (and `setDate` is never called).

You can see it happen here: https://codepen.io/anon/pen/jwJVJJ?editors=0000

In case the link goes down, here are the steps to reproduce:
- Add draggable elements
- Hide calendar element
- Call $.fullCalendar on the hidden element with `droppable` enabled
- Start dragging the element and the error will occur

**Comment by arshaw** [comment]
confirmed. thanks.

**Comment by MartijnWelker** [comment]
@arshaw Looks like this error is no longer occurring in the latest version.
