### ISSUE TITLE
 Visualization problem with resources and dynamic events in agendaDay

### ISSUE THREAD

**Issue by jaimeCMS** [fullcalendar/fullcalendar-scheduler#332]
Hello, I have a problem when viewing events within dynamic resources.  Mi code is this and resources and events are filled correctly. The resources are filled before the events.

<img width="501" alt="code" src="https://user-images.githubusercontent.com/9862574/28772253-e4d24f78-75e5-11e7-82cb-8d92a3b740e8.PNG">

When resources and events are filled by the callback function, It looks like this

<img width="452" alt="error" src="https://user-images.githubusercontent.com/9862574/28772348-3c36a12e-75e6-11e7-97ac-e232570b8943.PNG">

I would like to know what is the problem that looks bad sometimes, because at other times it shows well, or if I change day and return to the day is already shown correctly.

<img width="452" alt="ok" src="https://user-images.githubusercontent.com/9862574/28772501-b2aa6d4a-75e6-11e7-9d1d-cdcdb7da0f4a.PNG">

Please see if you can help me, I would appreciate it very much.

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
