### ISSUE TITLE
Dynamic change of resource row height

### ISSUE THREAD

**Issue by benlbrm** [fullcalendar/fullcalendar-scheduler#333]
I'm trying to reduce some resource row's height
Up to now, I've been able to change background color of some resources, but with the same method, I'm not able to change row's height

With resourceRender, I'm using this to change the background color: labelTds.css('background', '#ddd')
and this to change the height: labelTds.css('height', '10')

My code:
`
resourceRender: function (resourceObj, labelTds, bodyTds) {
 if (resourceObj.type === 'service' || resourceObj.type === 'office') {
  labelTds.css('background', '#ddd')
  labelTds.css('height', '10')
  bodyTds.css('background', '#ddd')
  bodyTds.css('height', '10')
 }
}
`
![fullcalendarresourcerow](https://user-images.githubusercontent.com/16845043/28920750-667ce0be-7853-11e7-86de-76d7eef9b0ab.jpg)

What's wrong in my case ?

Thanks

Benoît

**Comment by arshaw** [comment]
any way you could post a [Reduced Test Case](https://fullcalendar.io/wiki/Reduced-Test-Cases/) ?

You might need to tell the calendar to re-apply the height/dimensions. Try calling the render method: https://fullcalendar.io/docs/display/render/
