### ISSUE TITLE
filterResourcesWithEvents does not filter when swithing from week to day view

### ISSUE THREAD

**Issue by AssassinLV** [fullcalendar/fullcalendar-scheduler#334]
code pen demo: https://codepen.io/anon/pen/YxVpBe?editors=0010

How to reproduce:
1) Go to in week view
2) Go to the week of: "Aug 6 – 12, 2017"
3) Switch to the Day view

Expected: Resources that has no event on that day are hidden
Actual: Resources that has no event on that day are still visible

**Comment by arshaw** [comment]
reproduced. thanks. will try to fix this for next release

**Comment by arshaw** [comment]
codepen updated with better buttons and latest version:
https://codepen.io/arshaw/pen/gGoBOM?editors=0010

**Comment by arshaw** [comment]
queued for release

**Comment by AssassinLV** [comment]
@arshaw if the codepen has the updated version - then it seems that it works even less.... For example - if I now move to the day view - then the auditorium is still shown even if there are no days in that particular day or even the week...

**Comment by arshaw** [comment]
the codepen i posted is still proof of the bug existing.

the *fix* lives in the `master` branch, with no way for you to run it yet unless you want to build the project yourself

**Comment by AssassinLV** [comment]
ahh.. Understood. Thanks for clarification.

**Comment by arshaw** [comment]
Released in [v1.8.0](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.8.0)
