### ISSUE TITLE
Did someone try Angularjs support for Scheduler - uiCalendar

### ISSUE THREAD

**Issue by Babugoli** [fullcalendar/fullcalendar-scheduler#336]
Hi

I know lots of people are using scheduler, do some share info related to simple directive for scheduler.

or did some extent uiCalender directive to support scheduler. Its simple addition but great in return. 

Appreciate your help

**Comment by espen** [comment]
Try asking on StackOverflow or see https://github.com/angular-ui/ui-calendar/issues/317

Also please do note: "(Please erase the above text and begin typing. Thanks!)"

**Comment by arshaw** [comment]
please use this thread instead:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/11
