### ISSUE TITLE
Reset sorted Resource after navigate to next or previous day

### ISSUE THREAD

**Issue by sandeepparihar** [fullcalendar/fullcalendar-scheduler#337]
We have a button to sort the resource list in our scheduler, once sorted, if we go to a different date the sorting remains there. Is there a way to reset sorting when we go to a different date in scheduler?

For sorting we have used:
$('#calendar').fullCalendar('option', 'resourceOrder', 'orderByRegion,userLastName');

**Comment by lesilent** [comment]
A work around is to use the refetchResourcesOnNavigate option set to true along with a resources  function that returns the order you want based on the start/end dates like so:

```
$('#calendar').fullCalendar({
    refetchResourcesOnNavigate: true,
    resources: function (callback, start, end, timezone) {
        var rooms = [ 
            { id: 'a', title: 'Room A' },
            { id: 'b', title: 'Room B' }
        ];
        var today = moment();

        // You reorder you resources however you like,
        // but as an example, this just reverses the order
        if (start.isAfter(today)) {
            rooms.reverse();
        }
        callback(rooms);
    }
});
````

**Comment by sandeepparihar** [comment]
Thanks for reply sir! I use different approach and it worked for me.
