### ISSUE TITLE
drag drop event from external list or on calendar to scheduler resource cell by replacing its text

### ISSUE THREAD

**Issue by GeassEye** [fullcalendar/fullcalendar-scheduler#346]
is it possible to allow event that is on either calendar or on external list to drop on scheduler resource cell. I need to make field 3 to accept drag drop event from both list and calendar.

  resourceColumns: [
                        {
                            labelText: "a",
                            field: '1'
                        },
                        {
                            labelText: 'b',
                            field: '2'
                        },
                        {
                            labelText: 'c',
                            field: '3'
                        }
                    ],

**Comment by arshaw** [comment]
when the user drops the event on the resource text, what date/time would you expect the event to have?
