### ISSUE TITLE
scheduler dynamic double row bug 

### ISSUE THREAD

**Issue by ewartgh** [fullcalendar/fullcalendar-scheduler#349]
We have a button that is supposed to toggle between 1 or 2 header rows in the scheduler.

if loaded with 2 rows, we can toggle to 1 row - works fine
if loaded with 1 row, we can NOT toggle to 2 rows 

for example:
https://codepen.io/anon/pen/oGjBQv?editors=0010#anon-signup

**Comment by arshaw** [comment]
there was a bug in your code. you were assigning the setting value to an object with the `slotLabelFormat` rather than just the array itself. fixed: https://codepen.io/arshaw/pen/ZXBVxK?editors=0010#anon-signup
