### ISSUE TITLE
Upgrade to jQuery 2.x in zip distribution

### ISSUE THREAD

**Issue by florian-f** [fullcalendar/fullcalendar-scheduler#35]
The jquery version included in the `jquery.min.js` of the [fullcalendar-scheduler-1.0.0.zip](https://github.com/fullcalendar/fullcalendar-scheduler/releases/download/v1.0.0/fullcalendar-scheduler-1.0.0.zip) is 1.11.3:

`/*! jQuery v1.11.3 | (c) 2005, 2015 jQuery Foundation, Inc. | jquery.org/license */`

It should probably be v.2.1.4, since 2.1.4 is the jquery version that's included when fullcalendar-scheduler is installed with bower or built from source.

**Comment by arshaw** [comment]
i'll make this change when support for IE8 is dropped
