### ISSUE TITLE
'updateEvent' makes events disappear

### ISSUE THREAD

**Issue by wackawacka** [fullcalendar/fullcalendar-scheduler#350]
Simply calling updateEvent when viewing in resource/timeline view makes the event disappear
here is the simplest snippet of code: https://codepen.io/anon/pen/LzRjMv?editors=0010

here is a paste of the simple code:
$('#calendar').fullCalendar({
  eventClick: function(event, element) {
    event.title = "CLICKED!";
    $('#calendar').fullCalendar('updateEvent', event);
  },
  defaultView: 'timelineDay',
  defaultDate: '2017-05-04',
  resources: [
    { id: 'a', title: 'Auditorium A' },
    { id: 'b', title: 'Auditorium B', eventColor: 'green' },
    { id: 'c', title: 'Auditorium C', eventColor: 'orange' }
  ],
  events: [{ id: '1', resourceIds: ['b', 'c'], start: '2017-05-04T02:00:00', end: '2017-05-04T07:00:00', title: 'event 1' }]
});

but you dont have to update the title or anything - as soon as you call updateEvent, the event just disappears.

it seems to be because any custom properties are removed - which seems to include resourceIds
if you do a clientEvents with event.id - the resourceIds is null

In the mean time, if anyone else is having trouble with what seems like could be a common issue - I've done a workaround - but I think we can agree its not a desirable one: https://codepen.io/anon/pen/NaRzpw?editors=0011

Cheers,
Carl.

**Comment by arshaw** [comment]
bizarre. I was able to recreate. thanks.

**Comment by wackawacka** [comment]
Hi Adam, it looks like this issue might be linked to the following issue: https://github.com/fullcalendar/fullcalendar/issues/3839
so it will probably be fixed when that issue is resolved (possibly)

**Comment by arshaw** [comment]
queued for release.

**Comment by arshaw** [comment]
Released in [v1.8.0](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.8.0)

**Comment by wackawacka** [comment]
its probably nothing, but if its an easy fix...
when you get events with clientEvents (eg $('#calendar').fullCalendar('clientEvents');)
if there is only 1 resourceId - the event.resourceIds is null - even if you initially set all resources via the resourceIds property.

**Comment by arshaw** [comment]
@wackawacka , plz open a new ticket to continue this discussion.

(PS- first check if the `.resourceId` property is populated. That's populated when there's only one resource. bad API, i know)

**Comment by wackawacka** [comment]
have created #372 (included example)

   :)
