### ISSUE TITLE
Information about original resource when dragging an event that is associated with multiple resources

### ISSUE THREAD

**Issue by sboele** [fullcalendar/fullcalendar-scheduler#353]
It is possible to drag an event that is associated with multiple resources from one resource to another. It only drags the event on the resource you've selected.

I want to restrict the dragging possibilities to certain resources based on the original resource its coming from. Lets say I have an event that is associated with 2 resources (Resource A of Type 1 and Resource B of Type 2). When I start dragging the event from Resource A column I want to allow it to be dragged to resources of Type 1 only and the same for dragging an event Resource B to Type 2 only.

Is this possible? The information about the original resource is not on eventDragStart or eventAllow.

**Comment by arshaw** [comment]
i believe this is a dup:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/39
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by sboele** [comment]
Thanks, I've upped it! However, that only mentions eventDrop. I think it would be good to have this information on dragStart and eventAllow also. Probably on all the drag/drop events this would be usefull information,
