### ISSUE TITLE
Timeline Event With Same Start and End Dates

### ISSUE THREAD

**Issue by jobert21** [fullcalendar/fullcalendar-scheduler#355]
Hello,

view: timelineDay

When an event with the same **start** and **end** dates are the same, it still covers 1 hour in the timeline. Here is the codepen to demonstrate the issue.

https://codepen.io/jobert21/pen/VMrqzJ

**Comment by arshaw** [comment]
that's because the end date is considered invalid, and then it's falling back to [defaultTimedEventDuration](https://fullcalendar.io/docs/event_data/defaultTimedEventDuration/), which is two hours.
