### ISSUE TITLE
custom timeLine with multi color in each row

### ISSUE THREAD

**Issue by siedmohsen** [fullcalendar/fullcalendar-scheduler#356]
I have custom TimeLine to show roll call in each month that shows all day of month in separate row and hour of day is shown on column. We want to show some request of roll call as hourly mission or daily mission ,etc  in each day on its row with different color .(as below Picture)
can I use your plugin?
if yes ,How can i do it?

<a href="http://tinypic.com?ref=iv9wuw" target="_blank"><img src="http://i63.tinypic.com/iv9wuw.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by arshaw** [comment]
you might be able to get part of the way there by using eventRender:
https://fullcalendar.io/docs/event_rendering/eventRender/

however, figuring out the x coordinated of the inner subsections of the events will be hard. you might be better off using a different library that is better at Gantt charts.
