### ISSUE TITLE
How can I change modal to collapse when eventClick

### ISSUE THREAD

**Issue by kappabooom** [fullcalendar/fullcalendar-scheduler#359]
As the same with title, How can I change modal to collapse when eventClick
from this type
![image](https://user-images.githubusercontent.com/22300748/31476558-7dd5dcb2-af39-11e7-86f4-2378620efee0.png)

to this type
![image](https://user-images.githubusercontent.com/22300748/31476613-d6d3fdc6-af39-11e7-9198-9a00f7f2711f.png)

**Comment by arshaw** [comment]
which modal? (if it's bootstrap, your problem is likely out of the scope of FullCalendar's issue tracker). what do you mean by "collapse". There's not enough info here to diagnose a problem and the problem is likely due to your use of bootstrap.
