### ISSUE TITLE
[Missing] Vertical resource view with grouped columns

### ISSUE THREAD

**Issue by jdqx** [fullcalendar/fullcalendar-scheduler#360]
The title explains it all. The agendaDay view (also known as vertical resource view) does not support grouped columns (multiple vertical columns per time slot). I'll post a link to the reduced test case tomorrow ASAP. I'm guessing that the devs are already aware of this missing feature, hence why I am not in a rush to link to the error reproduction. Couldn't find this mentioned anywhere after a lot of searching around.

**Comment by sofima** [comment]
same here....

**Comment by McQuinTrix** [comment]
+1 happens in group resources view

**Comment by arshaw** [comment]
dup of:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/370 (which has a codepen)
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by arshaw** [comment]
apologies, the originally description made it sounds like this was a *bug* and a *regression* and I incorrectly lumped it together with bug #370.

This feature was never implemented for agenda views.

This is the correct ticket to vote on if you want to increase the priority:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/214

**Comment by arshaw** [comment]
released in [1.8.1](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.8.1)

**Comment by WeslleyDeSouza** [comment]
![image](https://user-images.githubusercontent.com/20669525/43364552-8f27f94c-931c-11e8-8aae-fce520f93366.png)


can be done in a view lines:
      this.config['viewRender']      = ( view, element,  )               => {
       const getFirstTh =()=> `<th class="fc-axis fc-widget-header" style="width:${view.axisWidth}px"></th>`

       const getLastTh =()=>`<th class="fc-resource-cell" data-resource-id="99gruppe" style="width: 
      15px;background-color: white;"></th>`
       let buildRows:any    = (grp)=> grp.map(r=>` <th>${r.title}</th>`).join('') 

     let $head = element.children[0].children[0].children[0].children[0].children[0] //todo: simplifyIt

     buildRows= buildRows(this.getData('workspace'))

     $head.insertBefore(createElementFromHTML(`<table>
      <tr>
          ${getFirstTh()}
          ${buildRows}
          ${getLastTh()}
         
       </tr>
      </table>`),$head.children[0])
   }

**Comment by jeremymcminn** [comment]
Just wondering if this is something that will be possible in FullCalendar 4 by default?

I'm hesitant to start building out a hacky solution when I intend to migrate across to version 4.  Thanks!
