### ISSUE TITLE
EventLimit for custom view of a duration of 90 days

### ISSUE THREAD

**Issue by afranzencallibrity** [fullcalendar/fullcalendar-scheduler#362]
I want to limit the number of events shown with my custom view, but it seems that EventLimit doesn't work for custom views. I have a view that has a duration of 90 days and I want only the first 5 events to show up in my view. When I use the EventLimit it doesn't have an effect on my view and I end up with an endless scrollbar which I don't want. Is there another way to accomplish this?

**Comment by anuraagbitcot** [comment]
@afranzencallibrity Where you able to achieve this?

**Comment by afranzencallibrity** [comment]
https://github.com/fullcalendar/fullcalendar/issues/3873 I posted it on the wrong repo
