### ISSUE TITLE
fc-content-skeleton DOM always create new one after change date or update

### ISSUE THREAD

**Issue by joey91133** [fullcalendar/fullcalendar-scheduler#363]
vertical-resource-view on v1.8.0
https://fullcalendar.io/js/fullcalendar-scheduler-1.8.0/demos/vertical-resource-view.html

![screenshot 2017-10-14-06-12-55 001](https://user-images.githubusercontent.com/8022316/31568440-fee30d5c-b0a6-11e7-8986-db784bec9c5a.png)

**Comment by arshaw** [comment]
recreated, thanks

accumulates DOM nodes as user navigates prev/next

**Comment by arshaw** [comment]
queued for release: https://github.com/fullcalendar/fullcalendar/commit/109f31eb344994e5470034a9c2c0c0978e5a4761

**Comment by arshaw** [comment]
released in [1.8.1](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.8.1). actually fixed in the lastest core (v3.6.2)
