### ISSUE TITLE
Locale does not change weekdays translation for timelineWeek

### ISSUE THREAD

**Issue by AssassinLV** [fullcalendar/fullcalendar-scheduler#367]
Locale does not set the weekdays translation for timelineWeek.

Here is the example: https://codepen.io/anon/pen/MEzLNg?editors=1010

---------------------
Note: I could not make a case more similar to our code - as the locale for us is set via Razor from the CurrentUICulture.

**Comment by davidoster** [comment]
Actually, all the timeline format doesn't translate days, weeks, months and am/pm on time format.
Check here: https://panel.nugaedu.online/fc/demos/column-grouping.html
the locale is set to el. 
locale: 'el',
`		timezoneParam: "Greece/Athens",
      		timezone: "Greece/Athens",
      		timeFormat: 'H(:mm)t',`
And the time format can't be changed to 24h clock.

**Comment by arshaw** [comment]
yes, something is going on here. will investigate more.

**Comment by arshaw** [comment]
@davidoster , you're using the wrong setting name. You should be using [slotLabelFormat](https://fullcalendar.io/docs/agenda/slotLabelFormat/) instead of timeFormat.

**Comment by arshaw** [comment]
@AssassinLV, queued for release

**Comment by arshaw** [comment]
released in [1.8.1](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.8.1)
