### ISSUE TITLE
Resources in day View

### ISSUE THREAD

**Issue by arilishu** [fullcalendar/fullcalendar-scheduler#37]
Hi Guys i want to use your plugin, but i can't find the viewDay with Resources and parent resources, as you have here:
http://fullcalendar.io/js/fullcalendar-scheduler-1.0.0/demos/column-grouping.html

Are you going to make it??

Thanks!

**Comment by arilishu** [comment]
Same question, but with week View!

Thanks!

**Comment by espen** [comment]
You want to make what is in that demo or what is your question?

**Comment by arilishu** [comment]
I want a mix of calendar and scheduler. I need to have resources in
horizontal and hours as the day view. in vertical.

Do you have that solution? Is that free?

Thanks!

**Comment by espen** [comment]
Resources is only available in the timeline views.

Given that events are horizontal on each resource row I'm not sure how useful a resource list is in day/week/month views. What could be useful is another behaviour of the resources though, working as filtering for which events to show in the view.

**Comment by arshaw** [comment]
i think you might be describing #5

**Comment by arilishu** [comment]
you are right.
That's exactly what i want.
i am now suscribed to the email list!

Thanks guys!

2015-10-10 19:25 GMT-03:00 Adam Shaw <notifications@github.com>:
