### ISSUE TITLE
resourceGroupField is not working

### ISSUE THREAD

**Issue by subicura** [fullcalendar/fullcalendar-scheduler#370]
https://codepen.io/anon/pen/pWYeEJ?editors=0010

From 1.8.0, resourceGroupField is not working!

Please fix this issue.

**Comment by Folrond** [comment]
Yup, I have the same issue. Switched to 1.8.0 from 1.7 and resourceGroupField stopped working.

The official demos showcase the issue too:

1.7.0 with working resourceGroupField:
https://fullcalendar.io/js/fullcalendar-scheduler-1.7.0/demos/grouping.html

1.8.0 no resourceGroupField
https://fullcalendar.io/js/fullcalendar-scheduler-1.8.0/demos/grouping.html

**Comment by arshaw** [comment]
confirmed. thank you. will get this fixed very soon.

**Comment by McQuinTrix** [comment]
+1

**Comment by arshaw** [comment]
queued for release

**Comment by arshaw** [comment]
released in [1.8.1](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.8.1)
