### ISSUE TITLE
Fixed header in vertical resource view

### ISSUE THREAD

**Issue by harish0000** [fullcalendar/fullcalendar-scheduler#371]
I want to fix the resources header(sticky header), so that on scroll the resources stays at the top.

didn't find any proper solution for this.

can anyone help in this ?

**Comment by arshaw** [comment]
there's a ticket already for this:
https://github.com/fullcalendar/fullcalendar/issues/3473
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
