### ISSUE TITLE
Inconsistencies with resourceId and resourceIds 

### ISSUE THREAD

**Issue by wackawacka** [fullcalendar/fullcalendar-scheduler#372]
this example shows the main concern: https://codepen.io/anon/pen/VMOmJJ?editors=0010

basically all the resources are set through the resourceIds array, but when you come to retrieve these you have to work out which one to get based on either resourceId being null or resourceIds being null, it would be much nicer if it was more consistent, at very least always having the resourceIds array even if there is only one item - perhaps it would be easier to just get rid of resourceId altogether? it seems a little unnecessary and redundant 

(the more I think about it the more it makes sense to make that property deprecated, it would make things less complicated and probably largely reduce the complexity in your code... take away a few headaches I imagine) :D

**Comment by arshaw** [comment]
I agree

**Comment by wackawacka** [comment]
Also, sort of connected - when you go through eventRender and have multiple events I cant see any way of getting the resourceId of the current event on the current resource being rendered.

either resourceId could be added as an extra parameter on the eventRender event

or (this could be an additional feature as well as the above solution) in my case I just need different classes for different resources on the event - so perhaps there could be the addition of a "classes" property on the event
e.g. 
{
  id:1,
  resourceIds:['a','b'],
  title:'some job to go to'.
classes:[{
  rId:'a',
  class:'on-route'
},{
  rId:'b',
  class:'on-site'
}]
}

**Comment by wackawacka** [comment]
not sure if this helps anyone but the current way I'm overcoming this is the following:-
in the renderFgSegEls function under: 

	var el = $(node);

I do:
	$(node).data('fc-seg', seg);

then in my eventRender method:

	eventRender: function (event, element, view) {
		var rId = element.data('fc-seg').resource.id;
		for (var i = 0; i < event.classes.length; i++)
			if (event.classes[i].rId == rId) {
				element.removeClass(event.className);
				element.addClass(event.classes[i].class);
			}
	}

**Comment by ejdaly** [comment]
Following @wackawacka in TimeGridEventRenderer.prototype.fgSegHtml(), you can add a data-resource attribute there, e.g.:

`const resourceId = seg.resource ? seg.resource.id : null;`

`        return '<a class="' + classes.join(' ') + '"' +
            (eventDef.url ?
                ' href="' + html_1.htmlEscape(eventDef.url) + '"' :
                '') +
            (skinCss ?
                ' style="' + skinCss + '"' :
                '') +
            (resourceId ?
                ' data-resource="' + resourceId + '"' :
                '') +                
            '>' +
            '<div class="fc-content">' +`

(note: this is v4alpha)

**Comment by arshaw** [comment]
this is no longer an issue in v4.here's what you'd use now:
https://fullcalendar.io/docs/Event-getResources
