### ISSUE TITLE
Chained events dragging animation

### ISSUE THREAD

**Issue by itajackass** [fullcalendar/fullcalendar-scheduler#376]
I've a system where an event is made by subevents....so i'm implemented it with a virtual "chain" of events...if i drag an events... all events chained follow the event modified....
try it: https://jsfiddle.net/outecxnb/8/
but during dragging, only the event selected moving on realtime with the mouse.... and all others events set new position when i drop.... i'm looking for a solution to show the animation during dragging to ALL events in the same time..is it possible? I think considering all chained events like a ONE SINGLE EVENT maybe?

**Comment by archemedia** [comment]
just give them the same ID and they should move together

**Comment by itajackass** [comment]
Try but there's a problem during RESIZE one event: all events resize.

**Comment by arshaw** [comment]
in v4, all events that share a `groupId` will be resized together. they will animate together while resizing as well
