### ISSUE TITLE
Chained events on the same line in timeline

### ISSUE THREAD

**Issue by itajackass** [fullcalendar/fullcalendar-scheduler#377]
Like example in my other request some minutes ago, i need a system with an events made by sequentially chained subevents like example here: https://jsfiddle.net/outecxnb/18/
the problem is that every chain of events, MUST be in the same line to prevent confusing. If you see example jsfiddle you see the "chain events" RED split in 2 line on the last 2 events.
I'd like every chain STAY on the same line. I know i can put every chain in different RESOURCE but is not a solution for me, causing problems and confusion to end-user.
Another solution would be using a single event instead a chain of EVENTS of course....in this case i need a system to collapse the single EVENT and show the children events like this mockup screen shot:
![senza titolo-1](https://user-images.githubusercontent.com/17260726/32320371-e140ac5c-bfbd-11e7-8d71-8f74f7b7593d.jpg)

Request is similar...maybe equal to this thread: https://github.com/fullcalendar/fullcalendar-scheduler/issues/95

**Comment by itajackass** [comment]
Is there hope to implement this features in near future? Cause If not, i have to thinking about another approach and remove my idea to use subevents...

**Comment by arshaw** [comment]
Yes, #95 is the ticket for this. I'll close this one.

Implementing this feature is not on the near-term roadmap. Unfortunately there's a lot of stuff that's higher priority.
