### ISSUE TITLE
resourcesInitiallyExpanded not working as expected

### ISSUE THREAD

**Issue by HadrienKulik** [fullcalendar/fullcalendar-scheduler#378]
The parameter `resourcesInitiallyExpanded` collapses the children of a resource correctly.

However it seems like it also tries to collapse the groups of resources (which I think is the expected behavior), but it does not fully work. When at `true`, the group headers seem to be in a "collapsed state" but the grouped resources are still showing.

You can tell that the headers are in a collapsed state because the arrow indicator is in the collapsed position, and a click on the header does not do anything initially, since it tries to expand a list of resources that is already expanded.

![image](https://user-images.githubusercontent.com/1494897/32410761-beeb8c70-c19e-11e7-819d-df290ee020e9.png)

Tested on 1.8.1
https://codepen.io/anon/pen/XzdyyQ?editors=0010

Expected behavior :
![image](https://user-images.githubusercontent.com/1494897/32410774-26d09d08-c19f-11e7-870d-77831ce4f9d4.png)

**Comment by HadrienKulik** [comment]
I would add that one could imagine having 2 separate global parameters : `resourcesInitiallyExpanded` and `resourceGroupsInitiallyExpanded` to better control the behavior described above.

Additionally, it would be great to have a `initiallyExpanded` parameter _per ressource_ that would give more granular control on what to expand and collapse at init, if this resource has children.

I understand the resourceGroups are done slightly differently than resources with children and could not really be controlled individually with such a parameter. Maybe it would require something like a `resourceGroupExpand` function to control individually. 

It would also be great if the DOM of these resourceGroups were tagged in some way (maybe at least with the `resourceGroupField`), because they are kinda hard to get to and customize, especially since they do not seem to trigger any event at rendering.

**Comment by arshaw** [comment]
recreated, thanks

**Comment by arshaw** [comment]
queued for release

**Comment by arshaw** [comment]
Released in core [v3.7.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.7.0) and scheduler [v1.9.0](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.9.0).

**Comment by HadrienKulik** [comment]
Thanks !

**Comment by luongthanhle** [comment]
I can how to update resourceEntityExpansions. I have a problem the same above
