### ISSUE TITLE
addResource with parentId doesn't render correctly

### ISSUE THREAD

**Issue by RenBrand** [fullcalendar/fullcalendar-scheduler#379]
### Bug Report
Whenever a child resource is added/created via '[addResource](https://fullcalendar.io/docs/resource_data/addResource/)' the child resource is rendered as a root resource. A switch of the calendar date causes the child resources to be rendered correctly underneath its parent. Hence it seams that the resources is attached correctly to its parent but not rendered in a correct way.

The [example on JS Bin](http://jsbin.com/voxonujoqi/1/edit?html,js,output) shows the problem. Whenever you click the "Click me"-button in the upper right corner you will add a new resource to the 'Auditorium C' resource, which will be rendered at the end of the resource-view. If you switch to the next day the newly created resource will be rendered correctly underneath 'Auditorium C'.

**Comment by arshaw** [comment]
queued for release

**Comment by arshaw** [comment]
Released in core [v3.7.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.7.0) and scheduler [v1.9.0](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.9.0).
