### ISSUE TITLE
timeline selection rendering w/o a resource, too dark

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar-scheduler#382]
https://fullcalendar.io/js/fullcalendar-scheduler-1.8.1/demos/selectable.html

Click the **select w/o a resource** button

![screen shot 2017-11-13 at 7 11 12 pm](https://user-images.githubusercontent.com/56520/32756142-94b8b8b0-c8a6-11e7-95e0-5d2da453ee5e.png)

All the individual resource render the selection AND the general non-resource background does as well, causing double opacity.

Introduced in 1.8.0

**Comment by arshaw-test** [comment]
hey @arshaw, did you get this?

**Comment by arshaw-test** [comment]
@arshaw ???? whats going on here?

**Comment by arshaw** [comment]
resolved
