### ISSUE TITLE
Webjar creation failing

### ISSUE THREAD

**Issue by sisao** [fullcalendar/fullcalendar-scheduler#385]
On https://www.webjars.org/ creation for a new version is failing, perhaps since 1.7.x, with this error message:

> Failed!
All attempts to determine an acceptable license have been exhausted. The package.json file did not contain a spec-compliant license definition and the license could not be determined by trolling through the source repo: https://github.com/fullcalendar/fullcalendar-scheduler.git
The acceptable open source software licenses are at bottom of: https://bintray.com/docs/api/
The provided licenses were: SEE LICENSE IN LICENSE.md
This problem will likely need to be resolved by working with the library maintainers directly.
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

Can you readd a valid licence file?

Regards,
Stefan

**Comment by acerix** [comment]
I don't see any recent changes to license files, and the definition in package.json is valid according to https://docs.npmjs.com/files/package.json#license .

Maybe they don't accept "SEE LICENSE IN LICENSE.md" anymore?  Do you know what needs to be added/changed for it to work?

**Comment by jamesward** [comment]
It looks like the license service was incorrectly detecting the license as WTFPL.  That has been resolved but since the license can't be detected as a valid license, it can't be auto-deployed.

**Comment by acerix** [comment]
Thanks for the help.

webjars.org now has version 1.9.0

https://github.com/webjars/fullcalendar-scheduler
