### ISSUE TITLE
Option for timelineYear view to scroll to the current date on render

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar-scheduler#387]
Request for new option similar to `scrollTime` but for scrolling to the right in the `timelineYear` view, so it looks like this on load:

https://codepen.io/anon/pen/POXMbp?editors=0010

**Comment by acerix** [comment]
https://fullcalendar.freshdesk.com/a/tickets/73

**Comment by arshaw** [comment]
this would fall under this existing feature request:
https://github.com/fullcalendar/fullcalendar/issues/1037
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
(can you notify the customer @acerix ?)
