### ISSUE TITLE
FullCanlendar AngularJs version

### ISSUE THREAD

**Issue by KevangPatel** [fullcalendar/fullcalendar-scheduler#391]
Do we have full-calendar-scheduler in angularjs Code rather than in Angular 2 ?

**Comment by acerix** [comment]
I'm not sure what you are asking, but FullCalendar is not affiliated with the Angular integrations.

I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/11
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
