### ISSUE TITLE
Locale error

### ISSUE THREAD

**Issue by mkerp** [fullcalendar/fullcalendar-scheduler#396]
### Bug Reports
You don't support localization for scheduler any more? After I implemented: "locale" parameter and link:
https://fullcalendar.io/js/fullcalendar-3.8.0/locale-all.js I got JS error: Cannot read property 'datepickerLocale' of undefined.

Example here: https://codepen.io/anon/pen/XVrEYQ

**Comment by acerix** [comment]
The Scheduler has support for many locales, and can be used like this:

https://codepen.io/anon/pen/dJpRGY?editors=0010

Much of the localization support is provided by other libraries, so, for example, the "au" locale you are using is not one of the [locales in moment.js](https://github.com/moment/moment/tree/develop/locale).  

I'm not sure why your example has an error, please provide a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/) if it's a bug.
