### ISSUE TITLE
[suggestion] Typescript example

### ISSUE THREAD

**Issue by SpareShade** [fullcalendar/fullcalendar-scheduler#399]
Thank you for this amazing tool!

I am currently experimenting with Scheduler using Typescript (and Vue), and am having not much luck getting it to work.
The calendar renders just fine, but none of the Scheduler functionality is there. Ie. resources are not appearing in the header; ``` getResources() ``` method is not loaded, etc.
Thus a suggestion to provide a few Typescript examples in the demo section.

I have pasted the abbreviated ts component, so any pointers would be greatly appreciated.

```javascript
import $ from 'jquery'
import moment from 'moment'
import * as FC from 'fullcalendar'
import * as Scheduler from 'fullcalendar-scheduler'
```
Then in the Vue component
```javascript
let fc = new FC.Calendar($('#calendar'), {
  schedulerLicenseKey: 'CC-Attribution-NonCommercial-NoDerivatives',
  editable: true,
  selectable: true,
  header: {
    left:   'prev,next today',
    center: 'title',
    right:  'month,agendaWeek,agendaDay,agendaTwoDay'
  },
  defaultView: 'agendaTwoDay',
  views: {
    agendaTwoDay: {
      type: 'agenda',
      duration: { days: 2 },
      // views that are more than a day will NOT do this behavior by default
      // so, we need to explicitly enable it
      groupByResource: true,
      //// uncomment this line to group by day FIRST with resources underneath
      // groupByDateAndResource: true
    }
  },
  resources: [
    {
      id: 'a',
      title: 'John',
    },
    {
      id: 'b',
      title: 'Jerry',
    }
  ],
  events: [
    {
      id: 'abcd-uid-123',
      resourceId: 'a',
      title  : 'event1',
      start  : '2018-01-04T12:30:00',
      end  : '2018-01-04T15:30:00',
    },
    {
      id: 'abcd-uid-12345',
      resourceId: 'b',
      title  : 'event2',
      start  : '2018-01-04T12:30:00',
      end  : '2018-01-04T17:30:00',
    },
  ]
})
fc.render()
```

**Comment by SpareShade** [comment]
well, my mistake was in importing 'fullcalendar-scheduler', which should have been just:
```javascript
import 'fullcalendar-scheduler'
```

**Comment by acerix** [comment]
Thanks for the suggestion, I couldn't find any demos or example of using in TypeScript and agree that would be useful.

Here's a link to the TypeScript initiative which is still open:

https://github.com/fullcalendar/fullcalendar/wiki/Initiatives#converting-to-typescript

**Comment by arshaw** [comment]
this is now accounted for in the docs: https://fullcalendar.io/docs/typescript/
