### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clone' of undefined [when rendering background events]

### ISSUE THREAD

**Issue by outofbounder** [fullcalendar/fullcalendar-scheduler#4]
I cannot change the day.  <code>Uncaught TypeError: Cannot read property 'clone' of undefined</code>

```javascript
            var blockedEvent = {
                title: event.title,
                start: event.start,
                end: event.end,
                allDay: false,
                resourceId: linkedRoomId,
                rendering: 'background'
            };
```
   The events render in the background but I get the attached 
![stacktrace](https://cloud.githubusercontent.com/assets/13893573/9395621/bcd735de-474c-11e5-9429-187e9428e9c4.png)

I could not get the online jsbin demos to work but I created them anyway.  I broke out the scheduler.js to more lines in case that helps determine the root cause.  The behavior is the same for at least IE 11.0.9600.17914 and Chrome 44.0.2403.155 m<link>http://jsbin.com/wucediz/edit?output</link>

**Comment by arshaw** [comment]
i must have forgotten to update this ticket. this was fixed with v1.0.0. jsbin to demo: http://jsbin.com/pugeka/edit?js,output

**Comment by mohitv29** [comment]
Might be possible that Source which is auto populated in fullcalendar is not being populated. That's why it is giving error while rendering BG events.

**Comment by mohitv29** [comment]
![fullc](https://cloud.githubusercontent.com/assets/14051187/13916906/7b8d25b8-ef83-11e5-90b6-f40e82be7301.jpg)

**Comment by Daniel3549** [comment]
Alguien ya encontró alguna solución?

**Comment by malkomich** [comment]
Sí, @Daniel3549 

jQuery library must be downgraded to version 2.x to get it working with fullcalendar.

https://stackoverflow.com/questions/37821389/fullcalendar-2-7-3-events-not-showing-on-initial-load/37897708#37897708
