### ISSUE TITLE
Setting for collapsing resource by default

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar-scheduler#40]
As per the SO thread here:

http://stackoverflow.com/questions/32265394/fullcalendar-scheduler-set-to-collapse-by-default

reported by @projectfuturism

**Comment by woodburn8** [comment]
Any ETA for this feature?  It is an important one for me as well.. too many child nodes under the resource.  Thanks.

**Comment by arshaw** [comment]
not quite sure how this will stack up against the other bugfixes/features in the upcoming release, but will try to get it in there. Likely sometime in January though.

**Comment by J3QQ4** [comment]
Sorry to bother, any chance this will be implemented this year?

**Comment by chriswilley** [comment]
FWIW, I figured out you can do the following:

    calView = $('#calendar').fullCalendar('getView');
    function collapseLocations() {
        for (x = 0; x < calView.rowHierarchy.children.length; x++) {
        thisRow = calView.rowHierarchy.children[x];
        if (thisRow.groupValue != 'Resource A') {
            thisRow.collapse();
        }
    };

Assumes you want all resources besides Resource A to be collapsed. You can call this function after all events are loaded (I load events using ajax, and this function gets called in the success callback); if you call it before they're loaded, the events don't display next to their resources until the next refetchEvents.

I would still vote for a more built-in way to do this.

**Comment by J3QQ4** [comment]
Can we add @chriswilley's method above into the code, add a condition for calling .collapse() or .expand() depending on the current state, and name the method toggleCollapseAll?

**Comment by veda-hr** [comment]
[Example](http://jsbin.com/jepuha)
By the start of the calendar all resources should be closed. We have realised this with the code by chriswilley. 
With a lot of resources the browser breaks off the JavaScript. There appears an error message, because the Script owns a very long term. 
Enclosed an example in addition. How can the error be repaired? How can a resource default be shown collapsing?

**Comment by kvnvandenbrande** [comment]
Any updated ETA on this feature?

**Comment by espen** [comment]
See https://fullcalendar.io/wiki/Requesting-Features/

> There are over 100 existing feature requests. Someone else probably already wants what you want. Please search through the issue tracker (link below) and if you find what you're looking for, please vote with a  reaction on the topmost description of the issue (learn how) and press the Subscribe button to receive updates when progress is made.
Comments like "+1" or "when will this be done?" will be ignored. Only  reactions on the topmost description will be counted.

**Comment by arshaw** [comment]
I made a quick pre-release of this feature.

download `scheduler.js` to use:
https://github.com/fullcalendar/fullcalendar-scheduler/tree/row-collapse-default/dist

source code if you're interested.
https://github.com/fullcalendar/fullcalendar-scheduler/tree/row-collapse-default

**Comment by arshaw** [comment]
set `resourcesInitiallyExpanded: false`

**Comment by veda-hr** [comment]
Ich bin bis 28.08.2017 abwesend.

Ihre Mail erreicht mich nicht, da ich ausser Haus bin.  Die Mails werden
nicht weitergeleitet.
Nach meiner Rückkehr werde ich Ihnen antworten.

Wenden Sie sich bitte in dringenden Fällen an hr.manager@veda.net.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[fullcalendar/fullcalendar-scheduler] Setting for collapsing resource by
default (#40)" gesendet am 9.8.2017 16:40:42.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by veda-hr** [comment]
Ich bin bis 28.08.2017 abwesend.

Ihre Mail erreicht mich nicht, da ich ausser Haus bin.  Die Mails werden
nicht weitergeleitet.
Nach meiner Rückkehr werde ich Ihnen antworten.

Wenden Sie sich bitte in dringenden Fällen an hr.manager@veda.net.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[fullcalendar/fullcalendar-scheduler] Setting for collapsing resource by
default (#40)" gesendet am 9.8.2017 16:41:14.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by speedy78** [comment]
I replaced the scheduler.js it does not work.

This is the error: 
`Uncaught TypeError: spec.class is not a constructor
    at constructor.instantiateView (fullcalendar.js:11623)...`

**Comment by arshaw** [comment]
Implemented and released in [v1.8.0](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.8.0)

https://fullcalendar.io/docs/resource_rendering/resourcesInitiallyExpanded/
