### ISSUE TITLE
Event resize background highlight overlaps and stays after releasing

### ISSUE THREAD

**Issue by MartijnWelker** [fullcalendar/fullcalendar-scheduler#406]
When resizing an event the background will become highlighted, this highlight is not properly removed/updated when moving the mouse and not removed after releasing the event.

Resize an event on either side in the codepen to see the issue.
https://codepen.io/anon/pen/goZzBy?editors=0010

This bug was introduced in v1.9.1 [this pen](https://codepen.io/anon/pen/JMwZpx?editors=0010) runs on 1.9.0 and doesn't have the issue.

![screen shot 2018-01-19 at 14 57 44](https://user-images.githubusercontent.com/6674662/35154139-52e1a5c0-fd29-11e7-941a-8f3fc8c87b80.png)

**Comment by acerix** [comment]
Thanks for the detailed report.  Can see the resize highlight in Timeline view is growing with the event, but not shrinking with it.

**Comment by arshaw** [comment]
this is a rather embarrassing bug, I'll get this fixed this weekend

**Comment by arshaw** [comment]
fixed in 1.9.2 (just released):
https://fullcalendar.io/scheduler/
