### ISSUE TITLE
firstDay option is not applied

### ISSUE THREAD

**Issue by polinin** [fullcalendar/fullcalendar-scheduler#408]
Hi.
We use fullcalendar 3.8.0 and fullcalendar-scheduler 1.9.1 (also tried 3.7.0 and 1.9.0). 
But we cannot set the first day of weeks to Monday, it always show Sunday in custom views.
I tried both "weekNumberCalculation: 'ISO'" and "firstDay: 1" options. 
Please see an example [here ](http://jsfiddle.net/vheyrpcg/2).

We used older versions before and some time ago (cannot tell you exact version) it worked, but there were another issues, so we updated it.

Please help.
Regards, Polina

**Comment by acerix** [comment]
Thanks for the detailed report.

I can see that when `slotLabelInterval` is a multiple of 7 days, for custom timeline views with a duration in days or weeks, the labels always start with the closest Sunday before `defaultDate`. It makes sense  that it should instead start with the first day of the week, according to the `firstDay` setting.

https://codepen.io/anon/pen/GybVxZ?editors=0010

**Comment by arshaw** [comment]
fixed and released in core 3.8.1 and scheduler 1.9.2
https://codepen.io/arshaw/pen/MQgMPa?editors=0010

**Comment by polinin** [comment]
Thank you!
