### ISSUE TITLE
Refetched resources not maintained across views

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar-scheduler#41]
See http://jsbin.com/yomiva/edit?js,output

*instructions:* change to resource1 or 2, now click on 3day.. the resources seem to jump back to
the previous resources

**Comment by arshaw** [comment]
released on v1.0.1
jsbin updated with latest version
http://jsbin.com/yomiva/3/edit?html,output

**Comment by eybarta** [comment]
thank you!
