### ISSUE TITLE
eventResize / scheduler delta is undefined when resize from begining ( left ) of event

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar-scheduler#416]
Moved from https://github.com/fullcalendar/fullcalendar/issues/4042

https://codepen.io/JustinRLeonard/pen/Jpdqqw?editors=0011

`delta` is undefined when resizing an event from the left.

**Comment by livmackintosh** [comment]
I have raised a PR for this issue after lots of stress and hair-pulling. I'm not all that brilliant with JavaScript (global objects - yuck!) but have managed to fix this after making 3 pages of notes tracing things back.

**Comment by pkeogan** [comment]
any eta on a fix? need a pull?

**Comment by arshaw** [comment]
#4135 has been merged into the core project's master branch

**Comment by arshaw** [comment]
this was a implemented in the core, which has a new release (v3.10.0) that will fix the problem. plz upgrade to core 3.10.0
