### ISSUE TITLE
variable 'fullCalendar' must be of type 'Calendar', but here has type 'object'

### ISSUE THREAD

**Issue by jimmylogic** [fullcalendar/fullcalendar-scheduler#417]
I am using fullcalendar-scheduler it is working fine. But when i am generate build(dist)  for production by using `ng build --prod`. It is throwing

node_modules/fullcalendar-scheduler/node_modules/fullcalendar/dist/fullcalendar.d.ts(2525,10): error TS2403: Subsequent variable declarations must have the same type.  Variable 'fullCalendar' must be of type 'Calendar', but here has type 'object'.

**Comment by acerix** [comment]
It should be [built with `gulp dist`](https://github.com/fullcalendar/fullcalendar/blob/master/CONTRIBUTING.md#development-workflow), maybe an issue with the angular module you are using? Is there something that should be changed in the Scheduler to get it working? 

There is an open issue for Angular support:

https://github.com/fullcalendar/fullcalendar-scheduler/issues/11
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by osnersanchez** [comment]
I also have this same problem
