### ISSUE TITLE
eventOverlap:false and timelineMonth views

### ISSUE THREAD

**Issue by thiagoducca** [fullcalendar/fullcalendar-scheduler#423]
issue: #422
hey there @acerix, thank you for your reply! to clarify my issue, check this codepen: https://codepen.io/anon/pen/VQrLVQ?editors=0010 - basically, it seems that {eventOverlap: false} doesn't work for the timelineMonth view, as I would expect both reservations on "2323 South Lane" to show up one after the other (where they are shown one above the other). How can I make them show up one right after the other, assuming overlapping dates are guaranteed not to happen?
![untitled-2](https://user-images.githubusercontent.com/8313259/36274970-70b9b702-1257-11e8-85d9-2eba88887491.jpg)

**Comment by acerix** [comment]
Thanks for clarifying.  

The issue is that `slotDuration` is one day in timelineMonth view, so those two events both show as taking the entire day. Would it work to use a smaller duration like this?

https://codepen.io/anon/pen/gvXrme?editors=0010

**Comment by thiagoducca** [comment]
Nice!
But I have in testing "timelineYear"  and is not working as a "timelineMonth"
https://codepen.io/anon/pen/oEowgq

![screencapture-codepen-io-anon-pen-oeowgq-1518746160467](https://user-images.githubusercontent.com/8313259/36290335-aebaddfc-1292-11e8-861a-841a5bb66826.png)

**Comment by acerix** [comment]
In timelineYear view, there is a warning in the console "slotDuration results in too many cells" because it is avoiding rendering so many time slots since that takes a long time.

It works as expected by increasing `MAX_TIMELINE_SLOTS`, but would need some tweaking to make it perform better:

https://codepen.io/acerix/pen/qxVXXe?editors=0010
