### ISSUE TITLE
[Feature Request] Tooltip/title hover slot time for slots. 

### ISSUE THREAD

**Issue by hdrodel** [fullcalendar/fullcalendar-scheduler#433]
I found it very difficult to keep track of the time when adding events to a calendar with multiple resources by clicking the time grid. 

So I thought it might be useful to have some tool-tip text appear when hovering the slot displaying the time. 

Adding the following to the `processOptions:` function:
`var slotTooltips =  view.opt('slotTooltips');` 

And the following to the `html +=` in the `renderSlatRowHtml`
`+(this.slotTooltips ?  'title="'+slotDate.format('HH:mm')+'"' : '' )+`

would make it possible to have the tooltips displayed when the option `slotTooltips: true,` is added to the calendar

**Comment by john1452** [comment]
Are there any work arounds for this?

**Comment by arshaw** [comment]
this feature request has existing tickets:

highlight cells on hover
https://github.com/fullcalendar/fullcalendar-scheduler/issues/102

Drag indicator for date/time
https://github.com/fullcalendar/fullcalendar-scheduler/issues/123


Could you please visit the links, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by FarazGhani91** [comment]
$('.fc-timegrid-slot-lane').hover(function () {
            var getDefaultTime = $(this).attr('data-time');
            var formatedTime = moment(
                moment().format() + ' ' + getDefaultTime,
                'YYYY-MM-DD HH:mm:ss'
            ).format('hh:mm a');
            $(this).attr('data-time', formatedTime);
        });
