### ISSUE TITLE
[Question] Control what resources are expanded by default

### ISSUE THREAD

**Issue by jpeszleny** [fullcalendar/fullcalendar-scheduler#435]
When setting up a [resource object](https://fullcalendar.io/docs/resource-object), is there a property to set if the resource is expanded or collapsed? I would like to expand a particular resource and have the rest collapsed.

**Comment by acerix** [comment]
I couldn't find a good way to accomplish that, but for now you could try just a click on the resource area lke this:

https://codepen.io/anon/pen/odNOWZ?editors=0010

**Comment by jpeszleny** [comment]
That does the trick. Thanks again!

**Comment by acerix** [comment]
Good to hear. You can leave this issue open as a feature request if you still want it.
