### ISSUE TITLE
FullCalendar Scheduler showing 356 Records

### ISSUE THREAD

**Issue by precise-sajid** [fullcalendar/fullcalendar-scheduler#437]
I am using fullcalendar Scheduler ver 1.8.0 and it is Free version and i am using asp.net webforms before that it was showing me 430 records but now it is showing me 356 records i am asking from you is this any error in that or i am using it wrongly i checked all the records and they all are correct

Regards

**Comment by arshaw** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
