### ISSUE TITLE
eventLimit is not working in timelineDay view

### ISSUE THREAD

**Issue by jitendra-kr** [fullcalendar/fullcalendar-scheduler#439]
I am trying to use event limit in timelineDay view. But is not working

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/128
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
