### ISSUE TITLE
JQuery UI dialog strange behaviour in combination with custom button.

### ISSUE THREAD

**Issue by kdenzel** [fullcalendar/fullcalendar-scheduler#441]
See http://jsbin.com/loqutaxawo/1/edit?html,output

i have a really strange behaviour with this, but See yourself.

**Comment by acerix** [comment]
Strange behavior, but it doesn't seem related to the calendar code.  I think the issue is reusing the same <div> for different `dialog`ues.

**Comment by kdenzel** [comment]
No this is not the Problem, i already tested it. In my main-project i use a different dialog for the button then for the plus icons and the events, still same behaviour. I think it has to do with the calendar, cause it only happens if i open a dialog in a custom button.

Maybe it has to do that the button becomes focus after closing or something else. I can't figure out where the Problem is, but i gues it has definitely to do with opening a dialog with the custom button.

**Comment by kdenzel** [comment]
It just occurred to me that it happens with every button. If you load the page and you haven't pressed any button, the dialog closes and doesn't scroll to the top. But if you press any button, the dialog scrolls to the top.

**Comment by kdenzel** [comment]
I guess i have figured out the problem, i think it has to do with the focus. When the button has this blue "focus" border and the dialog closes, it scrolls to the focus element. Maybe i have to set the focus on the plus-Icon?

**Comment by kdenzel** [comment]
Ok i got the Problem. The focus was still on the button after i pressed it. So in the plusButton.click function i added $(':focus').blur();. Now the browser does not scroll to the focused element and stays in position.
