### ISSUE TITLE
changeView on Timeline does not update duration

### ISSUE THREAD

**Issue by kdenzel** [fullcalendar/fullcalendar-scheduler#442]
See https://jsbin.com/femomoraqa/edit?html,output

I dunno if this is a real issue and the View-Object was not designed for this but:

In my Project i have a Button show period, where the user can select a date and specify the duration he want's to see. I already got a workaround for this but i mention this issue nevertheless.

When you open the dialog and click on update view, the view changes the start date, but the duration slot is always like it was first initialized. 

My workaround for this is: I made a function initializeCalendar(customView) where the customView parameter is passed. If customView is not defined, the customView will be calculated to the Month View and will be set to 'defaultView'.

Everytime the user will click on showPeriod Button, the calendar gets reinitialized, a customView object is generated and passed to the initialize function. It works but in my opinion it seems a little bit ugly to reinitialize the complete calendar cause the changeview does not update the duration parameter.

What do you think?

**Comment by kdenzel** [comment]
...yea i realized even the start date does not update if i pass more settings. When you change this line below the comment to

                            //here i want to update my customView
                            $('#calendar').fullCalendar("changeView", "customView", startDateMoment);

then the Calendar will change the date, but the duration stays the same like initialized.

**Comment by acerix** [comment]
The third param in [changeView](https://fullcalendar.io/docs/changeView) is "visibleRange" for `customView` so it only accepts a start/end time.

You could update the duration like this:

https://codepen.io/anon/pen/QxWJVe?editors=0010

and the date with [gotoDate](https://fullcalendar.io/docs/gotoDate).

**Comment by kdenzel** [comment]
Thanks this seems much cleaner than the previous method and it works fine.
