### ISSUE TITLE
Feature Requests - EventClick True/False per event

### ISSUE THREAD

**Issue by noveweb** [fullcalendar/fullcalendar-scheduler#443]
Enable or disable "EventClick" on especific event and changing cursor from hand to pointer like this:

[{
"id":"1",
"title":"My event",
"description":"Street A",
"start":"2018-05-29",
"color":"#000000",
"editable":true,
**"clickable":true/false, <---- This**
}]

Thanks and sorry by my bad english :)

**Comment by acerix** [comment]
Thanks for the suggestion.  You could also define this property yourself and use it change the mouse cursor CSS in `eventRender`.

**Comment by arshaw** [comment]
eventRender is the way to go
