### ISSUE TITLE
Business hours like fullcalendar and a little more

### ISSUE THREAD

**Issue by weha** [fullcalendar/fullcalendar-scheduler#444]
I've seen multiple issues submitted regarding business hours but not a request to simply have business hours of a resource behave the same way as the fullcalendar main bussiness hours.
Meaning multiple business hours  (one per day - https://fullcalendar.io/docs/businessHours )  instead of 1 for the whole week.
If I use the fullcalendar syntax on the scheduler 1.9.4 it just sets the whole day as if it were a holiday.

I'm going to use background events for now but it would seem more consistent to me if it were the same syntax.

Concurrently I would like to ask the possibility to have multiple business hours per day.
So like hours before noon and hours in the afternoon. A lunchbreak if you will.

**Comment by stgunholy** [comment]
Have the same need - to be able to specify business hours for each day... and multiple rages for day as well

**Comment by arshaw** [comment]
this should be possible in v4 now
