### ISSUE TITLE
Broken text in event bars when scrolling horizontally

### ISSUE THREAD

**Issue by gerhardhager** [fullcalendar/fullcalendar-scheduler#446]
When in day-view - and an event starts before the hour-times visible in the calendar-scheduler view (so that you get a horizontal scrollbar inside), the calendar displays the text in the <span> slightly above the eventblock.

Visualisation:
This looks how its supposed to be (screenshot1):
![grafik](https://user-images.githubusercontent.com/39992464/41036872-c93777f2-6991-11e8-9cfb-bb81a42ef80f.png)

This is what happens when you scroll to the right in the day-view (screenshot2):
![grafik](https://user-images.githubusercontent.com/39992464/41036880-d1c52194-6991-11e8-9634-631e44c71e83.png)

This happens when you switch between days, forcing the rerender and have a horizontal scrollbar on the bottom side because you cant see all the hours in your view (shrink your resolution if necessary). 

As you can see; for each resource expanded, the <span> with the “07:00 – 17:00” texts goes up by 10px.

What is happening and how to fix:
the scheduler is creating a copy of the span element as soon as you scroll to the right and hides the first one – as seen in the 
ScrollFollowerSprite.prototype.buildAbsoluteEl
function in scheduler.js.
The first span with the class “fc-title” gets a “visibility: hidden” and a new span is created with the class “fc-title fc-following” with an absolute position.

This new absoluteElement (span) gets the top, left and width calculated in
ScrollFollowerSprite.prototype.assignPosition
in scheduler.js.

Here in the calculation for the “top” seems to be the issue with the calculation of the viewPort(this.follower.viewportRect.top), probably caused by the small 0.2 sec transistion animation when the resources expand on switching between days, as its always 10px off per expanded resource. For each resource expanded (with events in it), the absuluteElement gets drawn 10px higher up (10px less top than it should have). 

This is the css for the transition in scheduler.css:
tr.fc-transitioning > td > div {
    transition: margin-top 0.2s;
}

tr.fc-collapsed > td > div {
    margin-top: -10px;
}

We are not quite sure as we didn’t want to dig deeper into the code of fullcalendar, but the top calculation of the viewport rectangle seems to be causing the issue as it is (or is not) considering the animation. 

Note: expanding or collapsing the resources fixes the issue for the specific day-view and scrolling does not put the spans 10px off - but switching between days causes the issue to occur again.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by acerix** [comment]
I noticed in this demo, that scrolling to the right makes the text move down slighty, is that the same issue you are referring to?

https://fullcalendar.io/releases/fullcalendar-scheduler/1.9.4/demos/simple.html

**Comment by gerhardhager** [comment]
I don’t think this is the same issue, probably it is related. Please have a look at the attached screenshots, there you can see how the texts are shown when scrolling.
We drilled down into the scheduler source code and mentioned the suspicious code part in the ticket, maybe this helps.
Additionally we’ll try to setup a stripped-down demo of the bug.

Regards,
Gerhard Hager
Technischer Leiter
Q Point GmbH
Stroheckgasse 11
1090 Vienna | Austria

Phone    +43 1 319 20 90
Mobile   +43 664 600 40 500
gerhard.hager@q-point.com<mailto:gerhard.hager@q-point.com> |  www.q-point.com

Comm. Reg.: FN 389013 d | Comm. Court: Vienna | UID: ATU67607707

**Comment by arshaw** [comment]
this should no longer be the case in v4. v4 uses native css props to achieve this. much less bug-prone
