### ISSUE TITLE
Timeline ressource view invertion

### ISSUE THREAD

**Issue by olivierlab** [fullcalendar/fullcalendar-scheduler#452]
Currently, into timeline ressource view, timeline is horizontal and ressources are verticals.

Is it possible to add a field into timeline ressource view configuration to invert ressource and timeline so it will be possible having timeline verticaly and ressources horizontaly ?

For example into timelineYear configuration :
     timelineYear: {
         orientation : 'vertical'
     }

The field 'orientation' would have two values : 
  * 'horizontal' (the default value), 
  * 'vertical' (the new one).

**Comment by acerix** [comment]
The `agenda` view can be used to display resources vertically, but I couldn't find a good way to make that work up to a year.

https://fullcalendar.io/releases/fullcalendar-scheduler/1.9.4/demos/vertical-resource-view.html

You should be able to create that as a custom view for now. I imagine this would be complex to implement as a new feature.

**Comment by olivierlab** [comment]
Indeed I had thought to do it with a custom view but as you say, this will be complex to implement.
Thank you for you response.

**Comment by olivierlab** [comment]
yes, i developped a view specially for that but not into fullcalendar.

**Comment by olivierlab** [comment]
No, i didn't published it because it was for a customer. I only used moment.js and jquery. I developed everything else.

**Comment by arshaw** [comment]
the original tickets describes Vertical Resource View, which is implemented

**Comment by olivierlab** [comment]
Great !
