### ISSUE TITLE
Remember fc-expander status when switching views

### ISSUE THREAD

**Issue by Mynameisbt** [fullcalendar/fullcalendar-scheduler#455]
Is there a way currently to have the UI remember the status of the group expander when switching views?  For example, https://fullcalendar.io/scheduler by default Auditorium D is expanded.  If the user collapses it and clicks on 3 days, Auditorium D is expanded again.  Is there anyway to remember the state of the group when the calendar rerenders?

**Comment by acerix** [comment]
I think it would be useful to have an option to preserve which groups are expanded, but no easy way to do that currently.

There's an option [resourcesInitiallyExpanded](https://fullcalendar.io/docs/resourcesInitiallyExpanded) to have them collapsed by default if that helps.

**Comment by Mynameisbt** [comment]
Thanks for the response.  

For now what I am doing is using the eventAfterAllRender callback to add click event listeners to the fc-expander elements to keep track of the collapsed groups and to also trigger mouseclicks on the expanders that have been collapsed by the user.  Its a hack but works for now.

**Comment by arshaw** [comment]
Apologies, there is already a ticket for this:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/42
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
