### ISSUE TITLE
Provide the "context" ("this" variable) as the last parameter in callbacks / public functions

### ISSUE THREAD

**Issue by ejdaly** [fullcalendar/fullcalendar-scheduler#456]
(Apologies if already suggested, I searched under "context" and "bind" / "binding")

Suggestion, that the last (or first) argument in the public methods be the same as "this" / the context.

Reason:
In a lot of the methods, one of the arguments is already the same as the context, but in some methods the context is not passed as an argument at all. 
(e.g. eventResize() does not provide the context as an argument)

If you need to bind "this" from the parent context, will lose access to it from within the function (e.g. in eventResize(), the context is the DOM element being resized. You have access to the fcEvent, but if that event has multiple resources, it won't be possible to tell which one the user is interacting with unless you can access the DOM element itself)

Note: I'm just pushing the context to the list of args in Calendar.prototype.publiclyTrigger(), before calling (although, now the context will sometimes be passed twice...)

Calendar.prototype.publiclyTrigger()  [v4-alpha]
```

        args.push(context);
        this.triggerWith(name, context, args); // Emitter's method
        if (optHandler) {
            return optHandler.apply(context, args);
        }
```

**Comment by acerix** [comment]
Thanks for the suggestion, I made this demo to test and can see that there's no easy way to tell which copy of the event was resized if the event shows in multiple resources:
https://codepen.io/anon/pen/xaxXKW?editors=0010

**Comment by ejdaly** [comment]
Correct, currently there is no way to get the resourceId of the element being interacted when the event is in multiple resources. 

There is a separate issue there really:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/372#issuecomment-414091421

This issue is more about inconsistency and inability to access the context if using bind at a higher level (for some of the public methods, including eventResize()). 

Trying to make it consistent would probably involve backwards-incompatible changes to public methods; but just adding the context to the few methods that currently don't have it would be relatively non-intrusive (adding as the last parameter).

It might be too small of an issue to warrant any change to the API however, and there is a fairly quick edit that can be made if people are stuck...

**Comment by arshaw** [comment]
in v4 (for which an alpha has recently been released for scheduler), the context of all callbacks will be the instance of the `Calendar` object. However, instead of using `this`, you can simply use your own reference to the Calendar object, which is typically called `calendar` in all the examples.

View the source of this demo and look for `var calendar =`
https://fullcalendar.io/docs/v4/timeline-standard-view-demo

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
