### ISSUE TITLE
eventOrder is not working in timeline view

### ISSUE THREAD

**Issue by pserafin** [fullcalendar/fullcalendar-scheduler#460]
Using:
    "fullcalendar": "**4.0.0-alpha**",
    "fullcalendar-scheduler": "**^4.0.0-alpha.2**",
Demo:
https://codepen.io/anon/pen/KxROWY?&editors=001

According to doc. events should be ordered by default by title (https://fullcalendar.io/docs/eventOrder)
but in timeline view they are always filtered by event start date. 
**Setting eventOrder to any value has no effect on that view** but it should !

**Comment by acerix** [comment]
It seems your demo did not save correctly, it's using version 3.9 and doesn't show the issue. 

Do you mean that events with the same start time are not showing in order by title in timeline view?

**Comment by pserafin** [comment]
With 3.9 behavior is the same.
"Do you mean ().." - No they do. But we want to show events sorted by title (same as in basic view) not by starting day.
When using resources in timeline view I can set  resourceOrder attribute to 'title' and achive requested vertical sorting. But I dont want to use resources here. eventOrder attribute should work as expected and sort events vertically by given criteria.

**Comment by pserafin** [comment]
and just to make clear I'm talking about vertical sorting, the rorizonalt event placement is correct.

**Comment by acerix** [comment]
I don't see any events in your demo that could be sorted differently, none of them have the same start time.  

Setting `resourceOrder` changes the order of resources so it wouldn't put the events in order.

**Comment by pserafin** [comment]
OK, so let's start again..... 
Use date: September 14, 2018
starting from the top to bottom (vertically) you have events: Lunch, Conference, Meeting.
Setting eventOrder='title' should sort event as: Conference, Lunch, Meeting.
This is how eventOrder is working with e.h. 'month' view.
And again you are wrong setting resourceOrder will order resource and because resources are binded with events by tuples resource.Id <=> event.resourceId it will force events to be sorted according to resourceOdred as well.
Honestly speaking I don't understand why you have such difficulties with understanding this bug, maybe its because of my english....
Last try:
Here you have example with events vertically sorted by resources (Conference, Lunch, Meeting):
https://codepen.io/pserafin/pen/mGjaWR
and counterexample without sorting (Lunch, Conference, Meeting):
https://codepen.io/pserafin/pen/MqBZGx
In both examples eventOrder is set but has not impact on horizontal sorting at all...
Here you have example with working eventOrder for month view  (Conference, Lunch, Meeting):
https://codepen.io/pserafin/pen/WgKLgg

**Comment by acerix** [comment]
Thanks for the demos, I think I understand better.  So, you are looking for events to be in order regardless of resource, but the timeline view first draws the list of resources based on `resourceOrder` and then each resource's events which are ordered by `eventOrder` only within the resource:

https://codepen.io/anon/pen/qMQLKv?editors=0010

The only way to not have the events grouped by resource is to not use resources:

https://codepen.io/anon/pen/bxQOmq?editors=0010

You could also look at using a custom view to get what you want.

**Comment by pserafin** [comment]
Thanks for answer, but your are still missing the source of this error. For timeline view events are always sorted by startdate first, it doesn't matter if I use resources or not.
case with resources:
https://codepen.io/pserafin/pen/eLbOJQ
case without resources
https://codepen.io/pserafin/pen/YOdKGq

for both examples eventOrder is set to 'title', but events are drawn in order Meeting, Lunch, Conference.
So the conclusion is that or:
1. eventOrder is not working
2. eventOrder is working as expected but documentation is misleading and this properties should be descrived as 'working only for events with same start date'

**Comment by pserafin** [comment]
OK, the doc. is correct:
 "eventOrder 2.4.0
Determines the vertical ordering events that have the same times."

So it's my fault I've read what I wanted to see :|. Im closing this task.
