### ISSUE TITLE
View room (ressource) in list mode

### ISSUE THREAD

**Issue by Picpool** [fullcalendar/fullcalendar-scheduler#463]
Hi,

Is it possible to view the ressource (room) for each event in list mode.
That seems so basic but i don't see it in the example...
link:https://fullcalendar.io/releases/fullcalendar-scheduler/1.9.4/demos/simple.html
Thanks al ot

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/348
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by Picpool** [comment]
Does it mean it is not possible and it won't be...?

**Comment by acerix** [comment]
It's not currently built-in and there is already an open feature request but we don't have an ETA when that will be added.  You could make a custom view for now.

**Comment by Picpool** [comment]
thanks for your answer, what do you mean by a custom view ?

**Comment by acerix** [comment]
https://fullcalendar.io/docs/custom-view-with-js
