### ISSUE TITLE
addResource not working

### ISSUE THREAD

**Issue by pizzadev** [fullcalendar/fullcalendar-scheduler#464]
Argument of type '"addResource"' is not assignable to parameter of type '"refetchEventSources"'.
when try to 
$('calendar-scheduler').fullCalendar('addResource',{});

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by pizzadev** [comment]
sorry, it was my mistake.  solved by updating to last version. Please close this ticket.
