### ISSUE TITLE
Bump jQuery removal branch's fullcalendar dependency?

### ISSUE THREAD

**Issue by robrez** [fullcalendar/fullcalendar-scheduler#469]
I noticed that a new, nice-looking release was tagged over in the fullcalendar core repo (4.0.0-alpha.2).

I was wondering if this repo (maybe the jQuery removal branch?) will bump that dependency anytime soon?

**Comment by acerix** [comment]
Yes, jQuery is being removed from the Scheduler as well, the alpha is expected for mid-November.
