### ISSUE TITLE
expose MAX_CELLS

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar-scheduler#47]
from @Patatou

---

Hi there,

When i put slotDuration: '00:05:00', slotWidth:30 and slotLabelInterval: '00:30' : 
- In timelineDay i've this http://hpics.li/9d59a2b
- In timelineWeek  i've this http://hpics.li/22d31f5

Option slotDuration and slotWidth is no longer taken in consideration when i'm on timelineWeek view.

I've try to simply modify your example with timelineThreeDays with simply put days:7, and i've same effect.

Any solution ?

**Comment by arshaw** [comment]
my recreation of what you describe: http://jsbin.com/kesamasufa/1/edit?js,output

**Comment by arshaw** [comment]
this is actually by design :( if fullcalendar predicts that many many DOM nodes will be created from the slot configuration, it decides not to render them. is actually spits out a warning that is seen in the console
<img width="1092" alt="screen shot 2015-12-29 at 5 40 20 pm" src="https://cloud.githubusercontent.com/assets/56520/12031764/62c816f8-ae53-11e5-9af1-82bd19e6ac4a.png">

**Comment by arshaw** [comment]
however, this max number of cell constant should be exposed to the power user:
https://github.com/fullcalendar/fullcalendar-scheduler/blob/master/src/timeline/TimelineGrid.defaults.coffee#L5

I'll repurpose this issue to be about exposing that constant via the API.

The ultimate solution here is to allow endless scrolling, where cells render on-demand, but we're a little ways off from that solution.

**Comment by Patatou** [comment]
This is exactly that !!!

This is not a probleme when your event duration is 30 minutes or more, but when your event is under, the render is not performant :'(

**Comment by arshaw** [comment]
this is released in v1.9.1
https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.9.1

you can set `$.fullCalendar.MAX_TIMELINE_SLOTS`
