### ISSUE TITLE
Fixed time column in agenda view (similar to timeline view)

### ISSUE THREAD

**Issue by WebspressoCo** [fullcalendar/fullcalendar-scheduler#470]
@arshaw Thank you for your amazing work so far!

I've recreated my issue here: https://jsfiddle.net/yb9a5c6k/10/
I used the 4.0.0-alpha.2 version, but the same issue appears in the JQuery version.

When more than a few resources are loaded, the columns become tiny. Unfortunately, Fullcalendar doesn't have an option to specify the column width in agenda view, so I've used the solution proposed here by @acerix: https://github.com/fullcalendar/fullcalendar/issues/3022

The issue with that is that the time column on the left is not visible when the horizontal scroll is used. I couldn't solve the problem with CSS. If I change the position of the column to absolute / fixed the times spill over the rest of the page:  https://jsfiddle.net/yb9a5c6k/11/

Scheduler already solves this issue for the timelineView, as shown here: https://jsfiddle.net/yb9a5c6k/3/
As you can see the resources and the times are always visible on screen.

I want to achieve the same in agendaView. Is this possible?

**Comment by acerix** [comment]
It sounds like you are requesting horizontal scrolling in agenda view, there is already an open request for that:
https://github.com/fullcalendar/fullcalendar/issues/3022
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by WebspressoCo** [comment]
Thank you for the quick response!

I know about the 3022 issue, I've even referenced it in this issue. However, as far as I understand this is not a priority for the project, and nobody is going to work on it in the near future. 

I'm willing to implement it myself, but I need some pointers. From what I saw, the timeline implementation uses the Spreadsheet class to initialize the fixed column. (https://github.com/fullcalendar/fullcalendar-scheduler/blob/master/src/resource-timeline/Spreadsheet.ts)

Should I use the same class to create a custom view with a fixed time column or is there a better solution?

**Comment by acerix** [comment]
New features are prioritised based on votes, so there are quite a few ahead of this one https://fullcalendar.io/issues/

You can discuss ideas in the open issue.  The scheduler code can't be used directly since the license is different but it makes sense that this feature would work the same as in the timeline view.

**Comment by WebspressoCo** [comment]
> New features are prioritised based on votes, so there are quite a few ahead of this one

Well, according to the link you gave me, it's actually the most voted issue for the scheduler: https://fullcalendar.io/issues/#fullcalendar-scheduler

Too bad that the scheduler code can't be modified, I guess I'll implement something similar on my own.

**Comment by richlandhosting** [comment]
$(".fc-time-grid > .fc-slats").css('z-index','99999');

I added this to my $().ready(function() or anytime after the calendar is generated.
