### ISSUE TITLE
Wrong files in v4.0.0-alpha.2 release

### ISSUE THREAD

**Issue by Folrond** [fullcalendar/fullcalendar-scheduler#472]
The v4.0.0-alpha.2 release contains the old V4.0.0 FullCalendar lib.
Obviously because of this the plugin's api does not contain and reflect the changes mentioned in blog post linked below the release.

If I update the wrong file manually I get the following errors:
![image](https://user-images.githubusercontent.com/11175253/48728262-c9a09900-ec34-11e8-8369-7f9b67c9b114.png)

The following JsBin contains your column grouping demo with the updated FullCalendar file.
https://jsbin.com/lemovulifa/edit?html,js,output

**Comment by acerix** [comment]
I see the error, but am not sure which you mean by the "wrong files".

**Comment by acerix** [comment]
The scheduler v4 doesn't support the newer fullcalendar alpha2, it's using the older alpha release of fullcalendar on purpose.

**Comment by Folrond** [comment]
Oh, okay then will this change in the future? Because this makes the versioning and the documentation ambigous. The current version of the scheduler is v4.0.0-alpha.2 but it really should be v4.0.0-alpha.
The plugins documentation under v4 section describes and reflects the alpha.2 api which is entirely different then v3 or v4.alpha thus there is currently no docs or inrofmation about the current state of the scheduler. 
I might copy this to a new issue too considering this is a problem related to docs and versioning.

**Comment by acerix** [comment]
Yes, this is an exception for the alpha version and is mentioned in the release notes:

> the Scheduler plugin has not been made compatible with v4.0.0-alpha.2 yet. It is still stuck on the first alpha release

https://fullcalendar.io/docs/v4/release-notes

**Comment by Folrond** [comment]
You're right, I missed that part, thanks for the feedback :)
