### ISSUE TITLE
[alpha3] timeline view divider not draggable by user

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar-scheduler#479]
![screen shot 2018-12-21 at 5 45 40 pm](https://user-images.githubusercontent.com/56520/50366716-7aa69600-0549-11e9-8114-a1a66de575d1.png)

This will be fixed for v4 official release.

**ALSO**, individual column headers need to be resizable again

**Comment by marcojakob** [comment]
Might be related to this: Setting the `width` of `resourceColumns` does not work.

```
resourceColumns: [
    {
      labelText: 'First Name',
      field: 'fname',
      width: '10%'
    }
  ,
```

The `fc-widget-header` always stays at `width:30%`.

BTW: I was trying to hide the resource column (for mobile) by setting `width:0`. Maybe there is a better way to hide it? If not, this might be a feature that could be included.

**Comment by mchapman** [comment]
Also perhaps related (or worth investigating at the same time): when the calendar is very wide on a resourceTimelineDay view the timeslots get progressively further out of line throughout the day.
![screenshot from 2019-02-28 12-41-42](https://user-images.githubusercontent.com/373462/53567253-91bfc080-3b56-11e9-9c6c-4e5733a91450.png)
Note:  You may need a 4K monitor to see this.

**Comment by arshaw** [comment]
@marcojakob the `resourceAreaWidth` setting controls the width of the whole group of columns. the widths of the `resourceColumns` defines how the resourceAreaWidth is split amongst the columns. the behavior is working as expected.

@mchapman would you mind posting a new issue with a recreation? you'll probably be able to recreate this for anyone if you force the width of the containing div to be huge.

**Comment by mchapman** [comment]
@arshaw - Happy to do that.  Is there a V4 equivalent of the debugging template from https://fullcalendar.io/reduced-test-cases? (I tried before making the original post to figure out the URL on your server, but it isn't obvious)

**Comment by arshaw** [comment]
@mchapman i'm working on making something more official for that. @acerix do you have something?

**Comment by acerix** [comment]
@mchapman @arshaw Here's a codepen someone made for the new beta, but it doesn't have all plugins included:

https://codepen.io/guice11/pen/bzxvEa

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
