### ISSUE TITLE
[alpha3] resource object missing many properties

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar-scheduler#482]
The following properties that used to be available on the [Resource object](https://fullcalendar.io/docs/resource-object)...

- eventColor
- eventBackgroundColor
- eventBorderColor
- eventTextColor
- eventClassName
- businessHours

These are no longer available on the [v4 Resource object](https://fullcalendar.io/docs/v4/resource-object)

TODO: make them available again.

**Comment by frlinw** [comment]
Please add an explicit `extendedProps` property to be consistent with event object.

**Comment by arshaw** [comment]
All of the named properties, with the exception of businessHours, have been restored. `extendedProps` is also available.

[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
