### ISSUE TITLE
[alpha3] error when dragging an event from one calendar to another which does not have a resource with the event's resourceId

### ISSUE THREAD

**Issue by buerobuettner** [fullcalendar/fullcalendar-scheduler#484]
following my example code for two calenders with drag and drop for events enabled:
The example comes from the drag and drop demo: [external-dragging-2cals.html](https://github.com/fullcalendar/fullcalendar/blob/v4.0.0-alpha.3/demos/external-dragging-2cals.html)

[external-dragging-2cals with scheduler](https://pastebin.com/dcJ5PQSH)

When i drag and drop an event from the upper to the lower calendar i get following error:

> Uncaught TypeError: Cannot read property 'length' of undefined
    at ResourceSplitter.Splitter._splitEventStore (fullcalendar.js:7911)
    at ResourceSplitter.Splitter._splitInteraction (fullcalendar.js:7950)
    at ResourceSplitter.splitEventDrag (fullcalendar.js:2214)
    at ResourceSplitter.Splitter.splitProps (fullcalendar.js:7868)
    at ResourceTimelineView.render (scheduler.js:2108)
    at ResourceTimelineView.Component.receiveProps (fullcalendar.js:3352)
    at CalendarComponent.renderView (fullcalendar.js:10094)
    at CalendarComponent.render (fullcalendar.js:10019)
    at CalendarComponent.Component.receiveProps (fullcalendar.js:3352)
    at Calendar.renderComponent (fullcalendar.js:9166)

removing the resource definition of the "destCalendar" object throws no error - BUT i need resources in both calendars :(

can you help?

**Comment by acerix** [comment]
Thanks for the report.  I put your code in the debugging template to test:

https://codepen.io/anon/pen/XoaYwa?editors=0010

The error happens if the destination calendar doesn't have a resource with the `id` matching the `resourceId` of the event being dragged.

**Comment by buerobuettner** [comment]
i see - thats not nice ;)
will there be a fix or a workaround for that?

**Comment by acerix** [comment]
It will be fixed but might take some time.  I couldn't find a good workaround but you could put all the resources in the second calendar to fix the error then just hide the ones you don't need.

**Comment by arshaw** [comment]
fixed in core v4, and here's the test to prove it: 0b97481319370c7448b25b2275321845fd6e4bd2

when released, i'll comment on this ticket again

**Comment by arshaw** [comment]
this is been fixed in [4.0.0-alpha.4](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v4.0.0-alpha.4)

**Comment by buerobuettner** [comment]
works great thanks!

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)

**Comment by sanishan** [comment]
The same error happens again today!

https://codepen.io/sanishan/pen/BaBdJLa

I can drag from the above calendar to bellow calendar if event created in the above calendar, but can't drag from below calendar to above if event created in below calendar.

Thanks,
