### ISSUE TITLE
EventAfterRender not called when expanded resources

### ISSUE THREAD

**Issue by fdiedler** [fullcalendar/fullcalendar-scheduler#487]
Hi,

I wonder if it is a bug or not but when I render events for the first time, **_eventRender_** and **_eventAfterRender_** are called for each event as expected.

Now, I collapse one resource group field and I expand it. The **_eventRender_** callback is called for each event in this group but not **_eventAfterRender_**.

A demonstration can be found here : 
https://jsbin.com/yajitagami/edit?html,console,output

To reproduce this bug, just collapse the "b" group then expand it . We will see in the console that the **_eventRender_** is triggered but not the **_eventAfterRender_**...

Because I modify position of events (_top_ CSS attribut), I have to use **_eventAfterRender_** callback because it does not work with **_eventRender_** callback. 

Can you help me ?

Thanks

**Comment by acerix** [comment]
Thanks for the detailed report, it makes sense that `eventAfterRender` should always be called after `eventRender` but I can see only `eventRender` fires in that case.

**Comment by fdiedler** [comment]
Hi Acerix, 

Is there any hack that I can do for now before waiting the new release ? 
I need to modify the position of some events (in _height_ dimension)

Supposed I have 2 kinds of events _TypeA_ and _TypeB_. I want all events of _TypeA_ rendered as normal and each events of _TypeB_ rendered **_at a fixed position_** under events of _TypeA_ (if exists in the current cell)

A example will be better : 
![example](https://user-images.githubusercontent.com/42271872/50816707-ab484700-1321-11e9-84ab-e5688e5564a8.png)

Thanks for your reply and great plugin :)

**Comment by acerix** [comment]
As a quick hack, you could use a CSS class instead and force the position style with "!important":

https://jsbin.com/jewivavemo/1/edit?html,css,console,output

**Comment by fdiedler** [comment]
Indeed, it works :)
I just found that the _eventAfterAllRender_ callback is not called in the same situation (after expanded resources). I don't know if it is a bug.

I tell you this because I want to set a **fixed** height for each resources regardless the events associated.
I try using CSS 
```
.fc-widget-content {
        height: 60px !important; 
        background-color:#BDB76B; // just for debug
}
```

But it does not work. Is there a quick hack to do this ? 

Thanks for your help and for this great plugin !

**Comment by acerix** [comment]
It sounds like you are doing something quite different from how the timeline view works so it would likely work better to make a new custom view instead of forcing the hieghts/positions which will lead to other issues.

https://fullcalendar.io/docs/custom-view-with-js
