### ISSUE TITLE
Events snap to top of cell when being resized in timeline view

### ISSUE THREAD

**Issue by teriblus** [fullcalendar/fullcalendar-scheduler#488]
Can be seen with the default template setup : https://codepen.io/teriblus/pen/dwqreE
I also recorded the problem : https://www.youtube.com/watch?v=Ddak1E4KOJc&feature=youtu.be

The problem is that when there are overlapping elements, if an event is resized, during the resize operation, il will be drawn at the top of the slot, instead of its real position. This is really annoying when there are more than 3 events (users will wonder where their event went!)

The same occurs when dragging, but it is less annoying.

**Comment by alxmcr** [comment]
Hi @teriblus 

I was able to resolve this problem using two properties:

```javascript
eventOverlap: false,
slotEventOverlap: false
```

I've applied these properties to [your code](https://codepen.io/maurroj/pen/JwmjRB?editors=0010) and I believe It works! 😄 Can you try to use this modified code, Please?

**Comment by acerix** [comment]
Are you suggesting that the event should instead be positioned where it will appear after being resized? 

I believe that would cause a performance problem since every event would need to be rendered again at each frame while an event is being resized.

**Comment by teriblus** [comment]
@alxmcr no, it's not what I meant, thank you :)

@acerix In my opinion, it should appear at the same line where it was before the resize, and not "jump" at the top of the slot, over the event that is there. It should not appear where it will be after resize as it will "jump" too.

I'm not a native english speaker and have not practiced english recently so do not hesitate to ask for clarifications. thx

**Comment by acerix** [comment]
Thanks for clarifying, I agree that if the event is staying in the same resource it would look better and would be more usable if it doesn't jump to the top while interacting.

**Comment by arshaw** [comment]
thank @teriblus . Issue #354 is just same. We'll use it to track this problem for both drag+resize
https://github.com/fullcalendar/fullcalendar-scheduler/issues/354
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
