### ISSUE TITLE
Incorrect rendering of events when using slotDuration equal to one day

### ISSUE THREAD

**Issue by alheka** [fullcalendar/fullcalendar-scheduler#49]
If an event spans more than one day and a view with slotDuration equal to one day is used, the event will not end on the last day, it will end on the day before the last day.

This problem did not exist in v 1.0.0.

Demo here:
http://jsbin.com/ceyizevaxu/1/edit?js,output

**Comment by arshaw** [comment]
fixed in v1.0.2 (just released). see updated jsbin:
http://jsbin.com/koceda/1/edit?js,output
