### ISSUE TITLE
 Duplicate resource groups when resourceOrder and resourceGroupField are on the same field

### ISSUE THREAD

**Issue by iiibbbmmm** [fullcalendar/fullcalendar-scheduler#490]
Duplicate resource groups while `resourceOrder` and `resourceGroupField` being the same field

[codepen](https://codepen.io/anon/pen/VqRJdW)

**Comment by acerix** [comment]
Thanks for the report, it's clear those options don't work together.

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released) This is fixed.
