### ISSUE TITLE
render data overlap view issue

### ISSUE THREAD

**Issue by cagmac** [fullcalendar/fullcalendar-scheduler#491]
My application reload data on click event, initially works fine but after several clicks the row on daily view overlaps. If I zoom the browser or click on next or back buttons, it fixes the view issue.
![image](https://user-images.githubusercontent.com/15915542/51292613-62575900-19d9-11e9-9b66-ec03f42ea3af.png)
![image](https://user-images.githubusercontent.com/15915542/51292641-7d29cd80-19d9-11e9-84d2-d9fcd675c66d.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

Also, which browser are you using?

**Comment by cagmac** [comment]
Hi, thanks to response, I have a codepen demostration: [codepen link](https://codepen.io/cagmac/pen/YdoaEX?editors=1111)
I am using google chrome, but testing in firefox and safary is the same.

**Comment by acerix** [comment]
Thanks for the demo, I couldn't easily get it working but it should work if you do the 'render' from within the modal's `on('shown.bs.modal')` callback.

**Comment by cagmac** [comment]
Thanks, acerix that fixed the issue.
