### ISSUE TITLE
Update FullCalendar to v3.10.0 in composer.json

### ISSUE THREAD

**Issue by nlyn** [fullcalendar/fullcalendar-scheduler#494]
It looks like Scheduler is still installing v3.9.0 even though v3.10.0 is out now.

**Comment by acerix** [comment]
How are you installing it?

**Comment by nlyn** [comment]
I have these 3 dependencies in my `package.json`:

```
    "fullcalendar": "^3.10.0",
    "fullcalendar-reactwrapper-with-scheduler": "^1.1.0",
    "fullcalendar-scheduler": "^1.9.4",
```

It seems that `fullcalendar-scheduler` will always install `3.9.0` in its own node modules.

**Comment by nlyn** [comment]
I should note that the problem I'm trying to resolve is, since upgrading fullcalendar to v3.10.0 I'm experiencing this kind of problem https://github.com/fullcalendar/fullcalendar/issues/3911 which seems to be a regular thing when people upgrade fullcalendar with scheduler also enabled. 

I'm wondering if perhaps making sure scheduler has a dependency for the most up to date fullcalendar, it might resolve the problem.

**Comment by nlyn** [comment]
The current version of scheduler specifies `~v3.9.0` 

https://github.com/fullcalendar/fullcalendar-scheduler/blob/v1.9.4/composer.json

**Comment by acerix** [comment]
Thanks for the details, I didn't notice that in composer.json

**Comment by lucagouty** [comment]
@acerix any news about that one ? It's impossible to update to `3.10.0` until that's fixed. 

Also it's not the first time, it happened with previous release : https://github.com/fullcalendar/fullcalendar/issues/4089#issuecomment-375459329

Maybe we should think about a way to avoid this to happen again

**Comment by acerix** [comment]
There's another issue regarding whether to update composer or drop support:

https://github.com/fullcalendar/fullcalendar/issues/4489

**Comment by arshaw** [comment]
we decided to stop supporting composer for v4, so I'll close this issue
