### ISSUE TITLE
Callback function when a resource header is clicked

### ISSUE THREAD

**Issue by scott-oliver** [fullcalendar/fullcalendar-scheduler#498]
Is it possible to trigger an event when selecting a resource columns **cell**? I'm having success using the following, however this is only triggered when selecting the resource **title** (rather than also including the white space around it):

`resourceRender: function(resourceObj, labelTds, bodyTds) {
    var resourceLabel = labelTds.find('.fc-cell-text');
    resourceLabel.css({'cursor': 'pointer'});
    resourceLabel.click(function(event) { ... }`

It is important to mention, that I need to **keep the functionality of the collapse/expand resources** though.

Love your work!

**Comment by acerix** [comment]
I tried your code and it seems to work fine if you listen for clicks on labelTds instead:

https://codepen.io/acerix/pen/LaVawo?editors=0010
