### ISSUE TITLE
ColumnHeaderFormat is ignored in timeline views

### ISSUE THREAD

**Issue by IndyHaine** [fullcalendar/fullcalendar-scheduler#507]
Hi!

In any timeline view in the scheduler, the columnHeaderFormat and the titleFormat option is being ignored. You can set it inside the view-object, or globally, it will not be applied.

Here is a test case where you can see the default column header format in timelineView, and if you click the other "week" button, it will take you to basicWeek, where columnHeaderFormat is applied:
https://codepen.io/anon/pen/eXMBKy?editors=0010

If there is another option for timeline view headers that I haven't found yet, please let me know.
Thank you in advance for viewing this issue!

**Comment by ady642** [comment]
Thank you bro
