### ISSUE TITLE
 Why does not it work using ngIf in div?

### ISSUE THREAD

**Issue by andrejm7** [fullcalendar/fullcalendar-scheduler#509]
Why does not it work using ngIf in div?

<div *ngIf="mostraAgenda == true" class="col-lg-10" id='calendar'></div>

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by andrejm7** [comment]
Clear.

The example is without a link https://codepen.io/anon/pen/YgRwzJ?editors=1000

Note not a simple html 

<div * ngIf = "1> 0" id = 'calendar'> </ div>

It is not my condition. I do not want my calendar not to appear in certain condition.

**Comment by acerix** [comment]
I don't see any problems in the demo, what is not working?

**Comment by andrejm7** [comment]
Why is ngIf not working?

**Comment by andrejm7** [comment]
*ngIf="1 === 0"

**Comment by acerix** [comment]
`ngIf` is part of Angular so it won't do anything without that framework.

**Comment by andrejm7** [comment]
Can you help it?

**Comment by acerix** [comment]
Angular support is not built-in but there is a request to add that:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/11
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
