### ISSUE TITLE
Adding resource when adding event

### ISSUE THREAD

**Issue by timd2i** [fullcalendar/fullcalendar-scheduler#51]
I add an event bij dragging a period on the calendar.
Then i get a bootstrap modal with start en end date already filled in. Using this code:
select: function(start, end) {
												var start = $.fullCalendar.moment(start).format("YYYY-MM-DD HH:mm:ss");
												var end = $.fullCalendar.moment(end).format("YYYY-MM-DD HH:mm:ss");
												$('#AddEventModal #start').val(start);
												$('#AddEventModal #end').val(end);
												$('#AddEventModal').modal('show');
											},

Is it not possible use the clicked resource?

**Comment by arshaw** [comment]
the resource object should be the last parameter:
http://fullcalendar.io/docs/selection/select_callback/

**Comment by timd2i** [comment]
I used following code:
select: function(start, end, resource) {alert($.fullCalendar.resource);	},

But this gives me "undefined" as alert.

**Comment by arshaw** [comment]
you'll want something more like this:

```
select: function(start, end, resource) {
    alert(resource.id);
},
```

**Comment by arshaw** [comment]
^ corrected
