### ISSUE TITLE
Event's resource constraints not respected dragging between two calendars

### ISSUE THREAD

**Issue by Hoakie** [fullcalendar/fullcalendar-scheduler#512]
Both eventAllow and resource constraints aren't honored when dragging between two calendars.   In the pen, you should not be able to drop  from resource A or B onto Resource C or D since the eventAllow is set to always return false.   Also the  " Only Allowed on "a" and "c" Event " on resource C should not be allowed to drop onto resource D.  The constraint is obeyed if you try and drop onto resource B

https://codepen.io/hoakie/pen/oVaEmY

**Comment by acerix** [comment]
Events from another calendar are work like "external events" and use `eventReceive` instead of `eventAllow`.

https://fullcalendar.io/docs/other-calendar-dragging

I can see the constraint isn't working as expected.

**Comment by Hoakie** [comment]
@acerix, actually eventAllow and dropAccept both get called from external dragging.   Did you mean eventDrop doesn't get called?    

The only issue with the eventAllow(dropLocation, draggedEvent)  from external event is the "draggedEvent" parameter does not contain event information even though it is defined on the Draggable and the external event appears to be created.  This is probably a different "bug" but I haven't had time to create a reduced test case yet.

**Comment by acerix** [comment]
Sorry, yes, I mixed that up with eventDrop. 

I see the issue with eventAllow now, the event should't be created since it returns `false`. So that bug is related but should be separate issue.

It looks like draggedEvent does have most of the event info though (`contraint` is not copied):

https://codepen.io/acerix/pen/PLXRxa?editors=0010

**Comment by arshaw** [comment]
fixed with https://github.com/fullcalendar/fullcalendar/commit/f812c661deedc51b326c79ee27ed57e5f9f704f7

will comment again when released

**Comment by arshaw** [comment]
fixed in v4.0.2! (was actually a bug in core, also updated to v4.0.2)
