### ISSUE TITLE
eventAllow not called when dragging between resourceTimeGridDay calendars

### ISSUE THREAD

**Issue by Hoakie** [fullcalendar/fullcalendar-scheduler#513]
When using "resourceTimeGridDay" view, you can drag an event between calendars even though both calendar's  eventAllow function set to always returns false.  

 https://codepen.io/hoakie/pen/EMGerQ?editors=0011

I tried to see if this was a global project but if you change the calendars to  "timeGridDay" the behavior appears to be correct.

https://codepen.io/hoakie/pen/rRoqOJ?editors=0011

issue created based on feedback from #512

**Comment by acerix** [comment]
Confirmed, thanks

**Comment by arshaw** [comment]
fixed with https://github.com/fullcalendar/fullcalendar/commit/f812c661deedc51b326c79ee27ed57e5f9f704f7

will comment again when released

**Comment by arshaw** [comment]
fixed in v4.0.2! (was actually a bug in core, also updated to v4.0.2)

**Comment by kibblewhite** [comment]
Is this still an issue as I have exact the same issue, works in resource view but not in timeGridDay for example?
