### ISSUE TITLE
Dynamically update resources of an event

### ISSUE THREAD

**Issue by Flauschbaellchen** [fullcalendar/fullcalendar-scheduler#514]
I first posted this question on SO (https://stackoverflow.com/questions/55316625/how-to-change-resources-of-events) but as it seems that this feature is missing for real, I would like to kindly ask for an implementation.

In FullCalendar 3.x I changed the resource of an event using:
```js
event.resourceId = newResourceId;
```

In FullCalendar 4.0 (currently running 4.0.1) I cannot find the right way...
My current code is:
```js
var calendar_event = calendar.getEventById(data.event.id)
if (calendar_event) {
  calendar_event.setProp('title', data.event.title)
  calendar_event.setProp('resourceIds', [data.event.resourceId])
}
```
`setProp` seems to be not the correct method as afterwards the event does not reflect the change within the grid, only the title has been changed to the new one.

A setter to `getResources()`, e.g. `setResources()` does not exist.

The official documentation on https://fullcalendar.io/docs/resource-data only includes resource-fetching, not programmatically set a new one to an existing event.

The migration guide https://fullcalendar.io/docs/upgrading-from-v3 mentions only the methods `setProp`, `setExtendedProp`, `setStart`, `setEnd`, `setDates`, `setAllDay`, `moveStart`, `moveEnd`, `moveDates` to replace `updateEvent` - resources are missing.

My current workaround is to delete and add the event again:
```js
calendar.getEventById(data.event.id).remove()
calendar.addEvent(data.event)
```

How to move an event to another resource without loading and initializing the whole event a second time?

**Comment by acerix** [comment]
Thanks for the report and workaround, I couldn't find any other way to change an event resource.

Here's a demo, although even removing the event, setting the resourceId, and adding it back doesn't seem to work if the same object is used.

https://codepen.io/acerix/pen/MxNvZP?editors=0010

**Comment by arshaw** [comment]
This is now possible with [Event::setResources](https://fullcalendar.io/docs/Event-setResources) in v4.0.2
