### ISSUE TITLE
Multi resource click and drag to create an event

### ISSUE THREAD

**Issue by ScarlettCode** [fullcalendar/fullcalendar-scheduler#515]
Hi,

Could you add the ability to click and drag to create an event across multiple resources. Click 8AM on resource A and drag to 5PM on resource C would create an event linked to A, B and C for 8 to 5. This would only work when when you want to create events for multiple resources that are next to each other but I think there are enough cases where this is true that it would be a worthwhile addition.

Thank you

**Comment by Harmindersingh05** [comment]
I would also like this please, this feature is core to our job management system.

**Comment by leiferic93** [comment]
Would indeed be a great feature!

**Comment by JensLindman** [comment]
![image](https://user-images.githubusercontent.com/51082408/58417083-04700780-8084-11e9-9656-9745a70e983e.png)
This missing feature is exactly what we need too. 👍

**Comment by arshaw** [comment]
Issue #310 , when implemented, will help you achieve this. That issue relates to allowing selection across days/resources. Once implemented, you could listen to that hook and programmatically call `addEvent` (multiple times?)

https://github.com/fullcalendar/fullcalendar-scheduler/issues/310
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
