### ISSUE TITLE
Issue in IE edge week view day header format change

### ISSUE THREAD

**Issue by Yogeshkad** [fullcalendar/fullcalendar-scheduler#518]
### Bug Reports
Fullcalendar scheduler view rendering differently in IE edge please check attached screens week header loading as Wed 4/3 in chrome while in edge it is Wed 4 3

![chrome image](https://user-images.githubusercontent.com/4671476/55315582-7fda8180-5464-11e9-9fc8-eec957f3d349.PNG)

![IE Edge issue](https://user-images.githubusercontent.com/4671476/55315591-85d06280-5464-11e9-9aee-a79c35c94112.PNG)

**Comment by acerix** [comment]
The default is now to let the browser choose how to render dates:

https://fullcalendar.io/docs/upgrading-from-v3#date-library

You could use the moment plugin which is consistent across browsers:

https://fullcalendar.io/docs/moment-plugins

**Comment by Yogeshkad** [comment]
OK, Let me check again. https://fullcalendar.io/docs/v3/locale-demo this url code was working on IE edge  but didn't noticed that it is because of moment plugin.

**Comment by arshaw** [comment]
this issue, once implemented, will solve your problem:
https://github.com/fullcalendar/fullcalendar/issues/4778
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
