### ISSUE TITLE
viewSkeletonRender is not called when the day is changed after the calendar height is changed

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar-scheduler#519]
Original issue: https://github.com/fullcalendar/fullcalendar-scheduler/issues/508

https://fullcalendar.freshdesk.com/a/tickets/774

Clicking "next" should trigger `viewSkeletonRender` but that doesn't happen if the height of the calendar was changed.

https://codepen.io/acerix/pen/MRYPpQ?editors=0010

**Comment by arshaw** [comment]
viewSkeletonRender is not meant to be called when prev/next navigation happens, or when any other date navigation happens for that matter.

[datesRender](https://fullcalendar.io/docs/datesRender) is what you're looking for

**Comment by Mansoun** [comment]
@arshaw 
Hi. 
Please check this  [this](https://codepen.io/ADyson82/pen/oNjExGx)
[datesRender](https://fullcalendar.io/docs/datesRender) is not working when switch dates range!
