### ISSUE TITLE
eventDrop old resourceId and new resourceId

### ISSUE THREAD

**Issue by Surt** [fullcalendar/fullcalendar-scheduler#52]
Hi,

I'm triying to get the old ```resourceId``` from an event in a resource dropped into a new resource, as well as the new ```resourceId```. Is there any way to do it?

For the old resource id I just need to ask for the ```event.resourceId``` but how can I know the new resource where the event was dropped?

```js
eventDrop: function (event, delta, revertFunc) { }
```

**Comment by sulian** [comment]
try eventDragStart to retreive the orginal resource.

```var myResource = $('#calendar').fulLCalendar('getResourceById', event.resourceId);```

**Comment by Surt** [comment]
@sulian perfect, but I'm wondering how to get the resourceId where the event was dropped.

**Comment by sulian** [comment]
Ok.

this is how I proceed :
```
var currentType = null;
$('#calendar').fullCalendar({
   ...
   eventDragStart: function(event) {
      var myResource = $('#calendar').fullCalendar('getResourceById', event.resourceId);
      currentType = myResource.type; // the variable of your resource 
   },
   eventDrop: function(event, delta, revertFunc) {
      var myResource = $('#calendar').fullCalendar('getResourceById', event.resourceId);
      console.log('New resource : ' + myResource.type;
      console.log('Old resource : ' + currentType;
   }
});
```
Hope it helps you

**Comment by arshaw** [comment]
yup, access `event.resourceId`.

Issue #39 is concerned with making it easier to get the old resourceId (so you don't have to do the `eventDragStart` trick like in @sulian's example)
