### ISSUE TITLE
Error while integrating Fullcalendar library with Salesforce lightning Component

### ISSUE THREAD

**Issue by wasimachetu** [fullcalendar/fullcalendar-scheduler#522]
Error while integrating Fullcalendar library with Salesforce lightning Component:

We have created lightning component in Salesforce. As per the application requirement, we need to integrate Full Calendar vertical-resource-mixed 4.0.2.

Lightning didn't allow us to include any library from outside the application. So we uploaded all the library related to vertical-resource-mixed in our lightning application.

These were the list of all library we had included in our application.

<script src='https://fullcalendar.io/releases/core/4.0.2/main.min.js'></script>
<script src='https://fullcalendar.io/releases/interaction/4.0.2/main.min.js'></script>
<script src='https://fullcalendar.io/releases/daygrid/4.0.1/main.min.js'></script>
<script src='https://fullcalendar.io/releases/timegrid/4.0.1/main.min.js'></script>
<script src='https://fullcalendar.io/releases/resource-common/4.0.2/main.min.js'></script>
<script src='https://fullcalendar.io/releases/resource-daygrid/4.0.1/main.min.js'></script>
<script src='https://fullcalendar.io/releases/resource-timegrid/4.0.1/main.min.js'></script>

now when we try to run the application, we facing some issue in above library.
The calendar is showing properly but when we try to move the mouse hover above the calendar it show the error 
"Uncaught TypeError: Illegal invocation
throws at https://worksteps--worksteps.lightning.force.com/resource/core/4.0.2/main.min.js:6:1128"

We have also try with older version 1.9.4, but the calendar not displaying properly.

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by PrateekKumarSrivastava** [comment]
I am facing the same issue. Can you guys help me with this?
