### ISSUE TITLE
the dateIncrement option does not work in both direction

### ISSUE THREAD

**Issue by youkoal** [fullcalendar/fullcalendar-scheduler#525]
### reproduction
https://codepen.io/damien-capron/pen/eoWgwm

Hello there.
I might be dumb but when i try to navigate, i can go in one direction, but only once in the other one.

this issue is a bit similar to this one : https://github.com/fullcalendar/fullcalendar-scheduler/issues/287
but since it's a 2017 issue i think it can't be the same.

**Comment by acerix** [comment]
Thanks for the report.  Your demo is not working for me because one of the sources times-out, but I can see the issue in the default debug template:

https://codepen.io/acerix/pen/eoEzNM?editors=0010

Related to this issue but I'm not sure it's a duplicate:

https://github.com/fullcalendar/fullcalendar/issues/4386

**Comment by youkoal** [comment]
> Thanks for the report. Your demo is not working for me because one of the sources times-out, but I can see the issue in the default debug template:
> 
> https://codepen.io/acerix/pen/eoEzNM?editors=0010
> 
> Related to this issue but I'm not sure it's a duplicate:
> 
> [fullcalendar/fullcalendar#4386](https://github.com/fullcalendar/fullcalendar/issues/4386)

Hello acerix, Thanks,
This is indeed the issue i experienced (in your codepen).

**Comment by youkoal** [comment]
Hi
Sorry if I'm rude, I just want to know if there is any updates about this issue.
Thx for your work :)

**Comment by arshaw** [comment]
I'm nearly certain this issue on the core issue tracker is the same:
https://github.com/fullcalendar/fullcalendar/issues/4678
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

(I'm closing this issue)
