### ISSUE TITLE
TypeError: "Cannot read property '_raw' of null" when updating resources with setOptions

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar-scheduler#527]
https://github.com/fullcalendar/fullcalendar-scheduler/pull/523#issuecomment-481631130

**Comment by arshaw** [comment]
this bug is reproducible when calling the internal `setOptions` method, but this has actually been removed in v4.2.x. The way one should add/remove resources is via the `Calendar::addResource` and `Resource::remove` methods.

**Comment by ziaulrehman40** [comment]
I am not using `setOptions` anywhere but this error is happening randomly, trying to find the cause, any help will be appreciated. Thanks.

**Comment by ziaulrehman40** [comment]
![image](https://user-images.githubusercontent.com/22441482/83876401-3ebdbb80-a752-11ea-8662-db8da15c12f1.png)
For the reference, stack trace if difference from https://github.com/fullcalendar/fullcalendar-scheduler/pull/523#issuecomment-481631130

**Comment by ziaulrehman40** [comment]
NVM, my code had logical bug which was passing `null` resources instead of `[]` in one case, and next time resources were sent it started throwing this error.
Fixed by passing `[]` if no resources.
