### ISSUE TITLE
Timeline header cells don't align with time cells with large resourceAreaWidth

### ISSUE THREAD

**Issue by ru1x89** [fullcalendar/fullcalendar-scheduler#528]
There is an alignment problem displaying the correct width of the header area table cells in day view. This happens only when we set a custom resource area width size.

CodePen Example: https://codepen.io/anon/pen/WWMbgZ

<img width="1680" alt="full-calendar-header" src="https://user-images.githubusercontent.com/1969949/56270384-9c88e180-6113-11e9-9ad8-3e6652e24951.png">

**Comment by acerix** [comment]
Thanks for the report and demo, might be the same issue as this:

https://github.com/fullcalendar/fullcalendar-scheduler/issues/505

**Comment by arshaw** [comment]
same as
#505 
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
