### ISSUE TITLE
dayRender is not called in timeline view

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar-scheduler#530]
`dayRender` does not get called in timeline view:

https://codepen.io/acerix/pen/PgQVLR?editors=0011

In version 3, it is called for each column:

https://codepen.io/acerix/pen/qwxvdR?editors=0011

Reported in https://fullcalendar.freshdesk.com/a/tickets/678

**Comment by arshaw** [comment]
fixed in v4.1.0

**Comment by ramavilli** [comment]
Not working in react, 

                "@fullcalendar/core": "^4.2.0",
		"@fullcalendar/daygrid": "^4.2.0",
		"@fullcalendar/interaction": "^4.2.0",
		"@fullcalendar/list": "^4.2.0",
		"@fullcalendar/moment": "^4.2.0",
		"@fullcalendar/react": "^4.2.0",
		"@fullcalendar/resource-daygrid": "^4.2.0",
		"@fullcalendar/resource-timegrid": "^4.2.0",
		"@fullcalendar/resource-timeline": "^4.2.0",
		"@fullcalendar/timegrid": "^4.2.0",
