### ISSUE TITLE
selectOverlap not called in "Grid" views when using Scheduler plugin

### ISSUE THREAD

**Issue by qbuache** [fullcalendar/fullcalendar-scheduler#536]
The handler _selectOverlap_ is not called in any "Grid" view when using the Scheduler plugin.

### Example
https://codepen.io/anon/pen/LvMaXJ?editors=0011

As expected, you can't select periods already booked in the "Timeline view", but it wrongfully works on the "Week view".

The console does not report the use of the _selectOverlap_ handler on the "Week view".

### Tried
You talked about a manual fix for that bug in an old issue :
https://github.com/fullcalendar/fullcalendar-scheduler/issues/56#issuecomment-151776023

But there is no "getPeerEvents" function to comment anymore.

FullCalendar and Scheduler 4.1.0

Thank you for your help

**Comment by acerix** [comment]
Since you are using resources, you should use `resourceTimeGrid` instead of `timeGrid` so it will display the resource and `selectOverlap` also works:

https://codepen.io/anon/pen/mggKZR?editors=0010

**Comment by qbuache** [comment]
Ok using `resourceTimeGrid` fixes the issue with `selectOverlap`.

I can remove the resource name and duplicate week line with CSS in `resourceDayGridMonth`, `resourceTimeGridWeek`
![month_view](https://user-images.githubusercontent.com/4728069/56949621-b246cf80-6b33-11e9-8e28-709a476331cb.png)
but not in `resourceTimeGridDay` as there is only one line and `datesAboveResources = true` do nothing in that view.

I want to display the day name the same way the `timeGridDay` does.
https://codepen.io/anon/pen/MRdYrj?editors=0010

And there is no class `fc-today` in the header of `timeGridDay` view.

**Comment by qbuache** [comment]
Issue is resolved. 

You should add a note in your documentation about the fact that you can't really use non-Scheduler and Scheduler views at the same time.
