### ISSUE TITLE
Scheduler TimelineDay View

### ISSUE THREAD

**Issue by sivaraj-mindze** [fullcalendar/fullcalendar-scheduler#54]
Hi,
I am planning to purchase Fullcalendar Scheduler (TimelineDay view) for my project.   On this behalf, I have been creating / researching this component using docs and google help, found this is little similar to my requirement.

I would like to clarify, whether we have the following functionalities in the licensed version.
1. Load the resources / events from an array object (instead of json file).
2. Edit events will update the same eventId (not creating a new eventId).
3. Search / Filter Resources
4. Styling:
-  Resource Render -  Left and Right Cells Alternate colors
- Unavailable Time slots - Greyit down and accept no click
- Refetch Resources and events on Fullcalendar Header Date navigation.

**Comment by arshaw** [comment]
1 - yes, possible
2 - yes, that is the case
3 - not implemented yet. feature request #7
4 - please play around with demos. probably possible through CSS

might want to play around with the demos on this page: http://fullcalendar.io/scheduler/
and download the free trial, which contains the code for the same demos:
http://fullcalendar.io/scheduler/download/
