### ISSUE TITLE
Naming inconsistency for 'eventResourceEditable' flag

### ISSUE THREAD

**Issue by gmw-web** [fullcalendar/fullcalendar-scheduler#545]
According to the docs, the `eventResourceEditable` flag determines whether the user can drag events between resources.

The docs state `eventResourceEditable` in the title and the last example on the page as the correct parameter but this doesn't actually work. 
The first example states `resourceEditable`, which appears to be working, but feels wrong to use due to the naming of the page etc..

_Furthermore:_
Should this flag work on the root level (not sure)? 
At the moment, it doesn't appear to do anything (neither of the two parameter names): [sandbox](https://codesandbox.io/s/fullcalendar-vue-hgg0r).

**Comment by acerix** [comment]
`eventResourceEditable` is a "global" setting that applies to all events.  For more control you can set `resourceEditable` on specific events.  Here is a demo:

https://codepen.io/anon/pen/QRPKqQ?&editable=true&editors=001

Are you suggesting that the event-specific option should have the same name?

If it's only not working in the Vue component please post in that repo:

https://github.com/fullcalendar/fullcalendar-vue/

**Comment by gmw-web** [comment]
> `eventResourceEditable` is a "global" setting that applies to all events. For more control you can set `resourceEditable` on specific events. Here is a demo:
> 
> https://codepen.io/anon/pen/QRPKqQ?&editable=true&editors=001
> 
> Are you suggesting that the event-specific option should have the same name?

I was under the impression that the same name was to be used for the global setting and the event resource settings, that's why I was a bit confused.

I'm not entirely sure why there's a difference in naming of the global settings and more local settings though, but perhaps you can explain. To me it appears that these settings toggle the same thing but just operate on a different level.
If the difference in naming is just to make that distinction (global vs. local), then perhaps there are better ways to indicate this difference.

> If it's not working in the Vue component please post in that repo:
> 
> https://github.com/fullcalendar/fullcalendar-vue/

The global setting appears to be working in your example (plain JS version), but not for the Vue component (see [this pen](https://codesandbox.io/s/fullcalendar-vue-2wwen)). I will post about this in the Vue component repo.

**Comment by gmw-web** [comment]
> The global setting appears to be working in your example (plain JS version), but not for the Vue component (see [this pen](https://codesandbox.io/s/fullcalendar-vue-2wwen)). I will post about this in the Vue component repo.

Nevermind, this appears to be fixed in the latest version (v4.2.0), see [this codepen](https://codesandbox.io/s/fullcalendar-vue-srtgt).

**Comment by arshaw** [comment]
good intuition on prop naming! yeah, that was a bug leftover from v4beta
