### ISSUE TITLE
Resource columns not resizing correctly

### ISSUE THREAD

**Issue by stefanopattaro** [fullcalendar/fullcalendar-scheduler#55]
Hi, 
I found out that if you use both "resourceColumns" and "resourceGroupField", it is not possible to resize the columns correctly using the column resize handle.

How to reproduce the issue:
1 - Open this sample link: http://jsbin.com/tugebubelu/edit?js,output
2 - Click and drag the separator between "Room" and "Occupancy" to resize the column

The "Occupancy" column disappear.

Kind regards
Stefano

**Comment by arshaw** [comment]
thanks
