### ISSUE TITLE
Link between events like project management tool

### ISSUE THREAD

**Issue by guillaumeko** [fullcalendar/fullcalendar-scheduler#550]
Hi guys,

I wonder if it's possible to add a "project management" like feature. I mean, just simple css links between events, and add a new property, linkedTo:eventId, or similar ?

Like this:
![Capture d’écran 2019-06-25 à 09 37 49](https://user-images.githubusercontent.com/1857479/60079346-0c2bd600-972e-11e9-99f6-d3c8e9d1eaf5.jpg)
![Capture d’écran 2019-06-25 à 09 38 02](https://user-images.githubusercontent.com/1857479/60079348-0cc46c80-972e-11e9-9cdd-6db2dbf0c775.jpg)

Thanks for your feedback. 🍦

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4748
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
