### ISSUE TITLE
Events with no end time after 11pm have a one-hour duration

### ISSUE THREAD

**Issue by samurdhilbk** [fullcalendar/fullcalendar-scheduler#552]
Events with no end time with a start time after 11pm (from 23:00:01) seem to automatically get a duration of 1 hour (and extend to the next day). Am I missing something? Please see the pen below for a minimal example.

https://codepen.io/anon/pen/GbyNPE

**Comment by acerix** [comment]
By default, [defaultTimedEventDuration](https://fullcalendar.io/docs/defaultTimedEventDuration) is 1 hour meaning that events with no end time will be displayed as 1 hour.

**Comment by arshaw** [comment]
PS: this setting might be of interest to you: https://fullcalendar.io/docs/nextDayThreshold
