### ISSUE TITLE
selectOverlap does not work

### ISSUE THREAD

**Issue by sulian** [fullcalendar/fullcalendar-scheduler#56]
Hi

it seems that the selectOverlap option doesn't work with schreduler.

Try this JS Bin (and use "Run with JS") :
http://jsbin.com/kuhilexozo/edit?js,output

Currently it's possible to select range even if an event already exists and when the selectOverlap is set to false. It doesn't work also with background event

**Comment by arshaw** [comment]
dup of #24. see my latest comment for a workaround:

https://github.com/fullcalendar/fullcalendar-scheduler/issues/24#issuecomment-151775812

**Comment by sulian** [comment]
Dear @arshaw, with your quickfix, problem is still here : I can select range fover Event and backgroundEvent or creating a new event even if ```selectOverlap```is set to false...

**Comment by arshaw** [comment]
that jsbin is not working because it doesn't contain my hacked JS that is needed (getPeerEvents needs to be commented out in scheduler.js). please resume discussion on #24, this issue is closed
