### ISSUE TITLE
Module not found in azure devops

### ISSUE THREAD

**Issue by VinayBHiraskar** [fullcalendar/fullcalendar-scheduler#566]
Hi,
I'm using fullcalendar-scheduler 1.9.4 with angular and it's working as expected in my local machine dev environment (visual studio code), we had used azure devops for our pipeline configuration, unfortunately it fails in the npm build step with statement "Module not found: Error: Can't resolve 'fullcalendar'" I had attached the screenshot of same below and my package.json will looks like this

`{
  "name": "myproject",
  "version": "1.1.1",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "build-staging": "ng build --configuration=staging"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "1.0.0-beta.3",
    "@angular/animations": "^6.0.3",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "@auth0/angular-jwt": "2.0.0",
    "@ng-bootstrap/ng-bootstrap": "^2.1.0",
    "@ngx-loading-bar/http-client": "^2.1.0",
    "@ngx-progressbar/core": "5.0.1",
    "@ngx-pwa/local-storage": "6.0.0-rc.0",
    "@swimlane/ngx-charts": "^8.1.0",
    "@swimlane/ngx-datatable": "^13.0.1",
    "@types/ckeditor": "^4.9.8",
    "@types/dwt": "^15.3.1",
    "@types/jest": "^24.0.13",
    "@types/jspdf": "^1.3.1",
    "@types/xlsx": "0.0.36",
    "angular-2-dropdown-multiselect": "1.8.0",
    "angular-calendar": "0.25.2",
    "angular-fusioncharts": "^3.0.1",
    "angular-gridster2": "^7.1.0",
    "angular-in-memory-web-api": "0.6.0",
    "angular-moment": "^1.2.0",
    "angular-resizable-element": "3.0.0",
    "angular-user-idle": "^2.1.4",
    "angular5-csv": "^0.2.11",
    "bootstrap": "4.0.0-alpha.6",
    "brew": "0.0.8",
    "chart.js": "^2.8.0",
    "ckeditor4-angular": "^1.0.0",
    "classlist.js": "1.1.20150312",
    "core-js": "^2.5.4",
    "d3": "^5.9.2",
    "date-fns": "1.29.0",
    "dateformat": "^3.0.3",
    "dwt": "^15.3.3-sdk",
    "enhanced-resolve": "4.0.0",
    "fabric": "^2.7.0",
    "file-saver": "^2.0.2",
    "flag-icon-css": "3.0.0",
    "font-awesome": "4.7.0",
    "fullcalendar-scheduler": "^1.9.4",
    "fusioncharts": "^3.13.4",
    "jquery": "^3.4.1",
    "jqwidgets-scripts": "^7.1.0",
    "jspdf": "^1.5.3",
    "jstransformer": "1.0.0",
    "leaflet-map": "0.2.1",
    "moment": "2.24.0",
    "ng-connection-service": "^1.0.4",
    "ng-dynamic-component": "^4.0.2",
    "ng-inline-svg": "^8.4.0",
    "ng2-ckeditor": "1.2.0",
    "ng2-completer": "^2.0.8",
    "ng2-dragula": "1.5.0",
    "ng2-pdf-viewer": "^5.3.3",
    "ng2-pdfjs-viewer": "^3.5.1",
    "ng2-smart-table": "1.5.0",
    "ng2-validation": "4.2.0",
    "ngx-bootstrap": "^5.1.0",
    "ngx-nvd3": "^1.0.9",
    "ngx-pagination": "3.1.1",
    "ngx-perfect-scrollbar": "6.2.0",
    "ngx-popper": "^6.2.0",
    "ngx-quill": "^5.1.0",
    "ngx-toastr": "8.8.0",
    "node-sass": "^4.12.0",
    "popper.js": "^1.15.0",
    "powerbi-client": "https://gitlab.com/Chandan323/powerbi-client.git",
    "primeflex": "^1.0.0-rc.1",
    "primeicons": "^1.0.0",
    "primeng": "6.1.6",
    "quill": "^1.3.7",
    "rxjs": "^6.0.0",
    "rxjs-compat": "^6.5.5",
    "simple-crypto-js": "2.2.0",
    "tether": "1.4.4",
    "ts-xlsx": "0.0.11",
    "web-animations-js": "2.3.1",
    "widgster": "1.0.0",
    "xlsx": "^0.14.4",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.13.9",
    "@angular/cli": "^6.0.3",
    "@angular/compiler-cli": "^7.2.5",
    "@angular/language-service": "^6.0.3",
    "@types/d3": "^5.7.2",
    "@types/jasmine": "^2.5.53",
    "@types/jquery": "^3.3.29",
    "@types/node": "~10.12.1",
    "@types/dwt": "^13.4.5",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "^5.4.1",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~3.1.1"
  }
}
`

![image](https://user-images.githubusercontent.com/1111767/82761984-df8bad00-9e1b-11ea-933e-84402a035e36.png)

can some one help me with steps to resolve this issue. thanks in advance

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by VinayBHiraskar** [comment]
> Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

It worked for me after pointing out the full calendar version by replacing "fullcalendar-scheduler": "^1.9.4" to "fullcalendar-scheduler": "1.9.4" and "jquery": "^3.4.1" to "jquery": "3.4.1"
