### ISSUE TITLE
Resource's children as an object

### ISSUE THREAD

**Issue by krzcho** [fullcalendar/fullcalendar-scheduler#58]
While doing xml to hash to json conversion in ruby when a resource has just a single child then resulting children parameter becomes child itself and not an array with single element - postprocessing is needed for such situation to enclose single child into the array; would be nice if script would treat non-array children as a single child object
I will try to post a pull request for it

**Comment by arshaw** [comment]
hmm, rather than having FullCalendar accommodate this behavior, which seems to be a shortcoming of the ruby library, more generally i'd rather allow pre-processing of resource data, similar to how [eventDataTransform](http://fullcalendar.io/docs/event_data/eventDataTransform/) works.

**Comment by arshaw** [comment]
if we decide to accommodate non-arrays for `children` i'm afraid others might have requests for making the data format more flexible... and i'd rather adhere to a stricter spec for the data and provide pre-processing hooks

**Comment by krzcho** [comment]
I would say it is not pragmatic approach but you are the boss :)
