### ISSUE TITLE
businessHours per-resource

### ISSUE THREAD

**Issue by xxAtrain223** [fullcalendar/fullcalendar-scheduler#61]
It would be awesome if there was a way to have business hours for each resource in the timeline(Day) view. 
In my app, each resource represents a room, and each room has it's own business hours. I would like to make it so that people can't try to schedule for a time for when the room is closed.
I might be able to make a hack that does this, but I would like it to be in a more official manner.

**Comment by arshaw** [comment]
This might already be possible: use [Background Events](http://fullcalendar.io/docs/event_rendering/Background_Events/) that are assigned to your resources, but with the `dow` param that [businessHours](http://fullcalendar.io/docs/display/businessHours/) offers.

But in the same vein as https://github.com/fullcalendar/fullcalendar/issues/2686, it would be nice if this was more formalized.

**Comment by san983** [comment]
this would be a great feature :+1:

**Comment by timd2i** [comment]
Looking forward to this feature

**Comment by emalherbi** [comment]
:+1:

**Comment by arshaw** [comment]
this should probably be implemented simply as another [Resource Object](http://fullcalendar.io/docs/resource_data/Resource_Object/) property, `businessHours`, that accepts the same input as the normal `businessHours` setting.

**Comment by mattdanna** [comment]
:+1:

**Comment by arshaw** [comment]
also, `eventConstraint` and `selectConstraint`, when either of their values are set to `"businessHours"`, needs to respect the business hours defined by the individual resources.

**Comment by tjphippen** [comment]
I use scheduler for our technicians & have been trying to get something like this feature working for quite some time. I use background events to display their scheduled hours & currently have constraints on the events themselves but that doesn't stop users from dragging the events to another resource(tech) that's not scheduled at that time..

**Comment by timd2i** [comment]
Having the samen problem as @tjphippen

**Comment by arshaw** [comment]
my failed attempt at using bg events w/ `eventConstraint` to workaround this: http://jsbin.com/dubisehuzi/1/edit?js,output

similar to what @tjphippen describes i think. the shortcoming i see is that the user can drag to events that don't have the green bg event at all. might be a separate bug. requires further triaging.

**Comment by skizznited** [comment]
Well it is kind of working. I noticed if i add more backgroundevents, I can add events to the calendar between the lowest time and the highest time of all the background events.
Is there a way to add an array to the eventConstraint?

Means:
Res1: 1pm - 3pm
Res2: 4pm - 7pm

I can add events to Res1 between 1pm and 7pm
I can add events to Res2 between 1pm and 7pm

I think it's because of the multiple given IDs there.

**Comment by skizznited** [comment]
Something new about this issue? I'm really interested in using this calendar for my project - but it should work with the eventConstraint

**Comment by becompi** [comment]
Having the same problem here.
I'm using Scheduler and would be great to have this feature.

**Comment by arshaw** [comment]
this has been implemented and released in scheduler [v1.3.3](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.3.3).

updated Resource Object docs:
http://fullcalendar.io/docs/resource_data/Resource_Object/

**Comment by xxAtrain223** [comment]
Many thanks @arshaw

**Comment by sulian** [comment]
Thanks @arshaw 👍

**Comment by arshaw** [comment]
better documentation for this feature: https://fullcalendar.io/docs/resource_data/businessHours-per-resource/
