### ISSUE TITLE
Dynamic custom view

### ISSUE THREAD

**Issue by MartijnWelker** [fullcalendar/fullcalendar-scheduler#66]
Hello !

I'm currently testing fullcalendar-scheduler if it fits our application and I came across an implementation issue, I'm in a situation where we have the user enter 2 dates and want to render the scheduler between those dates.
My current implementation is overwriting the view object in but this doesn't work (gives very strange results most of the time).

What is the recommended way to do this ?

Current implementation:

    function goToPeriod(dateObject) {
                if(!checkCalendarExistance())
                    return;

                var diff = moment.duration(
                    moment(dateObject.end)
                        .diff(
                            moment(dateObject.start)
                        )
                );

                var timelineType;
                if(diff.asDays() < 8) {
                    timelineType = 'timelineWeek';
                } else if (diff.asWeeks() < 5) {
                    timelineType = 'timelineMonth';
                } else {
                    timelineType = 'timelineYear';
                }
                
                var customView = {
                    type: timelineType,
                    duration: diff
                };

                calendar.fullCalendar('option', 'views', 'customView', customView);
                handleCalendarEvent('changeView', 'customView');
                handleCalendarEvent('gotoDate', dateObject.start);
                
            }

**Comment by arshaw** [comment]
instead of "overwriting the view object" each time, which i doubt works, it would be much more reliable to destroy/reinitialize the calendar each time the `timelineType` changes.
