### ISSUE TITLE
Event render cause wrong event.column

### ISSUE THREAD

**Issue by JJTOkenizer** [fullcalendar/fullcalendar-scheduler#67]
After spending many hours to understand what causes this bug (after I explain in more detail), updating plugins (jquery, fullcalendar and stuff) I finally figured out what's going on. As you can see I use multicolumn, an external resource available here: https://github.com/mherrmann/fullcalendar-columns

The version of FullCalendar that I'm using is the 2.3.1

Now the main problem is that if I move an event from the column 0 to the same column that I will get the event was moved to column 1. Almost always the event is moved to the next column and this is wrong. In jsfiddle you can verify this malfunction. I do not understand why because this event render.

JSFIDDLE: http://jsfiddle.net/jc07k3dd/56/

incriminated code:

     unavailablePeriod =
     {
         'title': "unav",
         'start': start,
         'end': date_end,
         'allDay': false,
         'color': '#BEBEBE',
         'editable': false,
         'className': 'fc-unavailable',
         'column': 0
      };

How can I fix?

**Comment by sulian** [comment]
@JJTOkenizer  it's an issue with multi-columns plugin not with fullcalendar. Perhaps you must post a report to @mherrmann

**Comment by mherrmann** [comment]
He already did. I believe it's an issue with FullCalendar, not fullcalendar-columns.

Btw @sulian, beware of JJTOkenizer - he's been spamming my repository for two weeks, essentially wanting me to do his coding for him, and creating new accounts whenever I tell him that he should go to StackOverflow.

**Comment by mherrmann** [comment]
(The corresponding fullcalendar-columns issue, where @JJTOkenizer posted basically exactly the same question, is https://github.com/mherrmann/fullcalendar-columns/issues/12).

**Comment by JJTOkenizer** [comment]
I fixed the problem, it is inherent to the way the data is handled by moment.js.
A little note for @mherrmann I have not made any kind of spam. You must know how to help people in difficulty if you work with open-source projects, and also you have to know how to support people like me who get involved to solve the problems.
You are a rude person who has no respect for anything.
I hope not to have more to do with you. Thank @aromka who implemented a serious logic in your project.
PS: you are about to ban users who report problems related to your library, but to what end? I repeat, if you do not change mentality this job is not for you.
