### ISSUE TITLE
Resource specific dropable

### ISSUE THREAD

**Issue by fierytone** [fullcalendar/fullcalendar-scheduler#71]
Hey there.

It would be cool. If you could disable event drop or snap on specific resources.

Let's say that you had a list of resources with chilldrens like this:

![image](https://cloud.githubusercontent.com/assets/12230934/11300549/5033fd9a-8f90-11e5-9abf-d8d9aeaac72b.png)

I achieved this by "revertFunc" on resources with childrens, but it doesn't look as smooth as when you drop an event outside of the calendar.

**Comment by arshaw** [comment]
I believe this could be solved by the API proposal in #50. Could you please subscribe to that ticket?
