### ISSUE TITLE
Lots of resources breaks the resource view order and doesnt append scrollbars to the bottom of the view

### ISSUE THREAD

**Issue by dizzleuk** [fullcalendar/fullcalendar-scheduler#74]
Hi having around 15 resources trying to be rendered in the resource view for this example:
http://fullcalendar.io/js/fullcalendar-scheduler-1.1.0-beta2/demos/agenda-views.html

using code like this:
resources: [
                    { id: 'a', title: 'Room A' },
                    { id: 'b', title: 'Room B', eventColor: 'green' },
                    { id: 'c', title: 'Room C', eventColor: 'orange' },
                    { id: 'd', title: 'Room D', eventColor: 'red' },
                    { id: 'e', title: 'Room E' },
                    { id: 'f', title: 'Room F', eventColor: 'green' },
                    { id: 'g', title: 'Room G', eventColor: 'orange' },
                    { id: 'h', title: 'Room H', eventColor: 'red' },
                    { id: 'i', title: 'Room I' },
                    { id: 'j', title: 'Room J', eventColor: 'green' },
                    { id: 'k', title: 'Room K', eventColor: 'orange' },
                    { id: 'l', title: 'Room L', eventColor: 'red' },
                    { id: 'm', title: 'Room M', eventColor: 'red' },
                    { id: 'n', title: 'Room N', eventColor: 'red' },
                    { id: 'o', title: 'Room O', eventColor: 'red' }
                ],
 will cause the following errors:

the resource headings are no longer in order a->z
scroll bars should be appended to the bottom when lots of resources are rendered

Hopefully this helps you
Best Regards

**Comment by arshaw** [comment]
could you follow [Bug Report Instructions](http://fullcalendar.io/wiki/Reporting-Bugs/) and post a recreation in JSBin/JSFiddle ?

**Comment by dizzleuk** [comment]
Just take the example code in the full-calendar-scheduler "simple" here:
https://github.com/fullcalendar/fullcalendar-scheduler/blob/master/demos/simple.html
and multiply the number of resources added to the full calendar.

**Comment by yokomizor** [comment]
I've noted that it is happening on Chrome and Opera. I've also tested on Safari, Firefox and IE11 and it works pretty well.

**Comment by yokomizor** [comment]
A workaround is to implement a resourceOrder function.

For example:
```javascript
resourceOrder: function (a, b) {
  return a.title > b.title;
}
```

**Comment by yokomizor** [comment]
I think that it is being scrambled here: https://github.com/fullcalendar/fullcalendar-scheduler/blob/7a5cc8d2335ad938b0329fe2cdccbd33c65e6fd7/src/common/ResourceDayTableMixin.coffee#L42

**Comment by yokomizor** [comment]
Implementing resourceOrder seems to solve the problem:

```javascript
resourceOrder: function (a, b) {
  return a.title < b.title ? -1 : a.title > b.title ? 1 : 0;
}
```

**Comment by arshaw** [comment]
@dizzleuk i've created this fiddle: http://jsbin.com/yedapokide/1/edit?js,output

from what i can tell, in both Chrome and FF, without specifying the `resourceOrder` setting, the order of the resources is the order they were received, which is intended behavior. [See docs](http://fullcalendar.io/docs/resource_rendering/resourceOrder/)

Adding a `resourceOrder: 'title'` option sorts by title

Knowing this information, @dizzleuk and @yokomizor , is there still a problem?

**Comment by yokomizor** [comment]
It seems to occur only using agendaDay view.

**Comment by dizzleuk** [comment]
yes i was also using the day view.

**Comment by arshaw** [comment]
recreated, will fix.

there is a workaround if you simply want to sort by title, just set `resourceOrder` to `"title"`

**Comment by yokomizor** [comment]
nice!

**Comment by arshaw** [comment]
fixed in scheduler 1.2.0, released

**Comment by OliverDolan** [comment]
Is it possible this is still not working correctly?
http://jsbin.com/pijokucaci/edit?html,js,output

**Comment by arshaw** [comment]
The fix was that if no resourceOrder is specified, it should render the resources in the order they were specified. This seems to be correctly happening in your first demo
