### ISSUE TITLE
"Please use a valid licence key" is appended to the html multiple times 

### ISSUE THREAD

**Issue by dizzleuk** [fullcalendar/fullcalendar-scheduler#75]
"Please use a valid licence key" is appended to the html multiple times:
![image](https://cloud.githubusercontent.com/assets/15214401/11453669/fdb6162c-9613-11e5-9cd4-b84277d58b58.png)

**Comment by arshaw** [comment]
this happens when going forward/back.

no visible symptoms unless you inspect DOM.

**Comment by dizzleuk** [comment]
sorry do you need more information from me to fix it or are you aware of the resolution?

**Comment by arshaw** [comment]
i've recreated it and plan on fixing it

**Comment by arshaw** [comment]
just released in [v1.2.1](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.2.1)
