### ISSUE TITLE
RowHeight of Resources ?

### ISSUE THREAD

**Issue by jdriesen** [fullcalendar/fullcalendar-scheduler#76]
Hi,

First of all... Congratz with the development of this component.
Really great piece of software !

I would like to know if there is a possibility to specify the rowheight of resources...
Please see [this picture](http://www.3sn.it/fullcal/rowheight.png)

Update:
Just found out about: eventOverlap: false, 
Did (most part) of the trick...
Thought, there is still a 'white gap' between the events...
Please take a look at 
![rowheight2](https://cloud.githubusercontent.com/assets/1137648/11589486/423b3b8c-9a89-11e5-8abd-2c8c2195cfe8.png)

Thanks in advance for your reply.

Regards,
Johnny

**Comment by arshaw** [comment]
hmm it must be related to your custom CSS. the unstyled version of Scheduler does it just fine: http://fullcalendar.io/js/fullcalendar-scheduler-1.1.0/demos/no-overlap.html
