### ISSUE TITLE
minTime bug with event positioning

### ISSUE THREAD

**Issue by mlaufer** [fullcalendar/fullcalendar-scheduler#78]
Hello,

there seems to be a problem with the calculation of events, which start before the current minTime of the resource timeline view. Basically, all events with the class "fc-not-start" are positioned incorrectly, since they lack a proper left or width value.

Also, creating an overlap between normal events and one of those buggy oness does not result in the correct overlap display of normal events, since the resource row will not be increased and they just plainly overlap.

See: http://jsbin.com/fuheyegega/1/edit?js,output

Setting "left: 0px" with css or javascript does not fix the overlap bug, but helps with displaying right now

**Comment by arshaw** [comment]
a further whittled down recreation:
http://jsbin.com/hepexabeco/1/edit?js,output

**Comment by arshaw** [comment]
fixed in scheduler 1.2.0, released
