### ISSUE TITLE
timeline DnD/resize, all-day not sticking 

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar-scheduler#79]
hi @starfishmod, to summarize the bugs you mentioned in #38:

- when in timelineMonth, and dragging an all-day event from one resource to another (or maybe even one day to another within the same resource), you're saying the event loses its all-day and becomes timed? this would be a bug
- when resizing an all-day event within timelineMonth, it loses it's all-day and becomes timed? this would be a bug as well.
- when in timelineMonth, when an event has a time, and is dragged from one day to another, it's time is reset (00:00:00) ? If so, this would be a bug as well.

I will work to reproduce these.

**Comment by starfishmod** [comment]
Thank-you for looking at these - yes the first 2 points are what I see.

The 3rd point is that if say the time is 8am when I drag it will change the time to whatever the time is between the slot - so that can be 2am or 3pm or wherever the mouse is located. So when I drop it'll change from 8am to 11:42am (as an example)

**Comment by starfishmod** [comment]
Just though i'd let you now I found a work around (for my issues) in the config by setting
```javascript
views:{
  timelineMonth:{
      snapDuration:'24:00:00'
  }
}
```

And then I set my other views to the different snapDurations

**Comment by arshaw** [comment]
I made a JS recreation of what you describe with `timelineMonth`:
http://jsbin.com/fugowotede/edit?js,output

I am unable to move/resize either the all-day or the timed event in such a way where the `allDay` value changes. So, I can't recreate the problem. Maybe I am misunderstanding.

Could you post a JSBin recreation with your configuration?
http://fullcalendar.io/wiki/Reporting-Bugs/

**Comment by starfishmod** [comment]
Ok it seems that it's when I add

snapDuration:'00:05:00',
slotDuration:'00:15:00',

which works for month as expected, but not timeline month.

http://jsbin.com/hedofagodu/edit?js,output

On 29 December 2015 at 18:54, Adam Shaw <notifications@github.com> wrote:

> I made a JS recreation of what you describe with timelineMonth:
> http://jsbin.com/fugowotede/edit?js,output
>
> I am unable to move/resize either the all-day or the timed event in such a
> way where the allDay value changes. So, I can't recreate the problem.
> Maybe I am misunderstanding.
>
> Could you post a JSBin recreation with your configuration?
> http://fullcalendar.io/wiki/Reporting-Bugs/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fullcalendar/fullcalendar-scheduler/issues/79#issuecomment-167750131>
> .
>



-- 
Regards

Andrew

**Comment by arshaw** [comment]
ah ok, the problem you are experiencing is the same on reported here:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/47

by design, the calendar won't render timeline when there will be many many cells as a result. See your JS console, it reports a warning.
