### ISSUE TITLE
Resources - Event row mis-alignment

### ISSUE THREAD

**Issue by MacTwister** [fullcalendar/fullcalendar-scheduler#80]
Hi,

I am trying to use this plugin where each resources has 3 columns and are grouped. However I get an issue with the row mis-alignment between the resource side and events side. This seems to occur when a resource group (the first column) only has one child. If you would add another child resource so that group has two resources, then rows align up ok. 

I provided a example for you to play around. 
example: if you change resource "e",  making col2 = "Group 1" you will see the rows aligning up again.
http://jsbin.com/tosotutuye/1/edit?js,output

Kind regards

**Comment by arshaw** [comment]
thanks for the recreation

**Comment by arshaw** [comment]
fixed in scheduler 1.2.0, released
