### ISSUE TITLE
addResource and removeResource don't work in vertical resource view

### ISSUE THREAD

**Issue by caseyjhol** [fullcalendar/fullcalendar-scheduler#84]
Demo: http://jsbin.com/yekenibilo/1/edit?js,output

Select `timelineDay` for the view. Then, click the **add/remove room** button. You'll see that **Auditorium A** is removed/added each time you click it. Then, select `vertical resource` for the view. Try adding/removing the room, and nothing happens.

**Comment by arshaw** [comment]
fixed in scheduler 1.2.0, released
