### ISSUE TITLE
Is there an equivalent of the resourceWeek view from the jarnok resource views addon?

### ISSUE THREAD

**Issue by paulduran** [fullcalendar/fullcalendar-scheduler#85]
Hi,

We currently use FC1 with the jarnok resourceviews addon. The new official scheduler addon for fullcalendar looks great and would slot in nicely for our 'day' view however we have a view like the following for week/fortnight views with the resources along the 'Y' axis and the days along the 'X' axis:

![image](https://cloud.githubusercontent.com/assets/601548/11923255/f4b740da-a7f4-11e5-8c6a-78fc5ddd2855.png)

Is it possible to achieve a similar type of view with the scheduler addon?

**Comment by arshaw** [comment]
you can use the `timelineWeek` view with slotDuration set to 1 day. see jsbin:

http://jsbin.com/sakegiqasi/1/edit?js,output
