### ISSUE TITLE
eventOverlap: false not work with eventResourceField set

### ISSUE THREAD

**Issue by wilga** [fullcalendar/fullcalendar-scheduler#86]
http://jsbin.com/taxuru/edit?output

When eventResourceField is set to an alternate field name, the eventOverlap:false method gets buggy.  It will not allow an event to drag to an available resource if the abandoned resource is booked at the available resource time.  Then, it will permit overlaps.  Tough to explain, but plain to see the issue at the above jsbin link.

**Comment by arshaw** [comment]
thanks for the jsbin. confirmed

**Comment by arshaw** [comment]
update with latest: http://jsbin.com/qivayotupu/1/edit?js,output

**Comment by arshaw** [comment]
just released in [v1.2.1](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.2.1)
