### ISSUE TITLE
memory leak upon destroy

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar-scheduler#87]
reported by Kieren Grant:

-------------

Been playing around with some scheduler demos  and noticed this:

https://output.jsbin.com/nupisayule

Reproducing in 2.5.0 + scheduler 1.1.0 for any calendar with attached
resources. Destroying + rebuilding the calendar should free
all the resources (and it does work perfectly when it's filled
just with events alone).

However, if there's any resources present, you can notice the huge amount 
of retainers - orphaned DOM elements etc. The number rapidly increases 
with each cycle.

I've fixed the library to prevent this, but not in the most efficient
way I'm afraid. Seeing a performance drop after the fix.

**Comment by grantkieren** [comment]
Here's two more bins to illustrate it:

#1: timelineDay, no resources: http://jsbin.com/gukosewalu/1/edit?js,output
#2: timelineDay, with resources: http://jsbin.com/cazoqucafa/1/edit?js,output

Take an initial heap snapshot and another one after 20-30 cycles of destroy+init.
If you compare them, the 1st bin shows no detached dom objects, the 2nd
one ends up with 5k+ orphaned divs.

**Comment by grantkieren** [comment]
Manual unbinding of dragstart & sortstart after calling 'destroy' fixes the leak.

**Comment by arshaw** [comment]
i can confirm that dragstart/sortstart are not getting unbound. thank you

**Comment by arshaw** [comment]
fix release in [v1.3.2](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.3.2)
