### ISSUE TITLE
refetchEvents reset the scroll position

### ISSUE THREAD

**Issue by sparh** [fullcalendar/fullcalendar-scheduler#89]
Hi,
I am sorry if it is not the godd place to post this, I am new with github.
This may be related to https://github.com/fullcalendar/fullcalendar/issues/2970

To reproduce go to http://jsbin.com/daxonojiga/edit?js,output
Scroll the calendar.
Click on "refresh test"
- Chrome  (47.0.2526.106 m) : scroll is reseted
- Firefox (43.0.2): scroll stay (as it should be)
- IE (11.20): scroll is reseted

Not a big deal but it is more user friendly if the scroll stay when using refetchEvents.
ps: Thanks for fullcalendar

**Comment by arshaw** [comment]
fixed by this commit in core:
https://github.com/fullcalendar/fullcalendar/commit/88b1ad8f1d1e5ffe8e1ecf6bd769c3dfdf831c6e

tests:
https://github.com/fullcalendar/fullcalendar-scheduler/commit/c971b336a302d1890a4137fd906dfd568a046590

**Comment by arshaw** [comment]
released in scheduler 1.2.0 / core 2.6.0
