### ISSUE TITLE
Event cannot be added into the 'timelineDay' view.

### ISSUE THREAD

**Issue by smartkid77** [fullcalendar/fullcalendar-scheduler#90]
I tried to add an event when clicking on a timeslot, and give a title using a prompt. When I click ok there are no events are displayed in timelineDay view. But its added and displayed into other views. I tried so many things but I didn't get it. Please help me to fix it.

Note :  If I drag an event from and external div, its working.

Regards
Dina

**Comment by arshaw** [comment]
could you please post a JSBin, as described here?
http://fullcalendar.io/support/
