### ISSUE TITLE
How to render resources dynamically after Ajax Response ?

### ISSUE THREAD

**Issue by niloyniloy** [fullcalendar/fullcalendar-scheduler#92]
Anyone please help ?

**Comment by niloyniloy** [comment]
Here is my code to render the calendar

     $('#calendar').fullCalendar({

            dayClick: function(date, jsEvent, view) {

                alert('Clicked on: ' + date.format());

                alert('Coordinates: ' + jsEvent.pageX + ',' + jsEvent.pageY);

                alert('Current view: ' + view.name);




            },

            now: '2015-12-07',
            editable: true,
            aspectRatio: 1.8,
            scrollTime: '00:00',
            header: {
                left: 'today prev,next',
                center: 'title',
                right: ''
            },
            defaultView: 'timelineMonth',
            views: {

            },
            resourceAreaWidth: '25%',
            resourceLabelText: '<?php echo dashboard_lang('_OBJECTS');?>',
            resources: [

                 <?php  $string_index = "a"; foreach($show_only_heftruck_objects as $objects){



               echo  "{ id: '".$string_index++."', title: '".$objects->rev."', eventColor: 'green' },";
                 } ?>

            ],
            events: [
                { id: '1', resourceId: 'b', start: '2015-12-07T02:00:00', end: '2015-12-07T07:00:00', title: 'event 1' },
                { id: '2', resourceId: 'c', start: '2015-12-07T05:00:00', end: '2015-12-07T22:00:00', title: 'event 2' },
                { id: '3', resourceId: 'd', start: '2015-12-06', end: '2015-12-08', title: 'event 3' },
                { id: '4', resourceId: 'e', start: '2015-12-07T03:00:00', end: '2015-12-07T08:00:00', title: 'event 4' },
                { id: '5', resourceId: 'f', start: '2015-12-07T00:30:00', end: '2015-12-07T02:30:00', title: 'event 5' }
            ]
        });

**Comment by arshaw** [comment]
Could you please post a JSBin recreation of your problem?
http://fullcalendar.io/support/
