### ISSUE TITLE
Disabling the resource group title row from adding a events

### ISSUE THREAD

**Issue by smartkid77** [fullcalendar/fullcalendar-scheduler#93]
Hi, 

Here is my question, How to disable resource group title row timeslots from adding an event in it. The title is for only representing the set of item which belongs to those group. So please help me to disable the resource group title row from adding events.

View : timelineDay view.

Regards
Dina

**Comment by arshaw** [comment]
what you mean that the group row is "adding an event in it" ? i don't understand how events could ever get into that row. could you please provide screenshots illustrating what you mean?

**Comment by smartkid77** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/6229719/12083935/0c861532-b2d2-11e5-9372-f7156cc4f9e7.jpg)

Hi sorry I mentioned my all issues in the screenshot. Please give me suggestions to solve it.

**Comment by arshaw** [comment]
I will accept this feature request for implementation at some point, but did you know about resource grouping? might be what you are looking for. http://fullcalendar.io/js/fullcalendar-scheduler-1.2.0/demos/grouping.html

**Comment by smartkid77** [comment]
Thank you so much. Let me try.

Does business hours  is not work on timelineDay? Because I have seen this
demo, so I want to integrate this feature in my calendar but its not
working.

Here is what I need : http://eo14.com/static/fullcalendar/

But in timelinDay view.

Can you help me?

**Comment by arshaw** [comment]
businessHours should work in timeline view. If for some reason you find that it is buggy, please submit a separate ticket, complete with a JSBin recreation. thanks

**Comment by bggJoe** [comment]
Hi...
I find business hour only follow default setting ( 9 am ~ 5 pm) in timeline view
But it won't follow the custom setting...

Could you help to check it?

**Comment by bggJoe** [comment]
Hi...
I made a jsbin for business hour issue in scheduler (timeline view)...
custom config object can't work....it just follow default business hour....

http://jsbin.com/hufekon/edit?js,output

**Comment by arshaw** [comment]
@bggJoe you are writing businessHours as if it accepts multiple definitions. it currently does not. please see [this ticket](https://github.com/fullcalendar/fullcalendar/issues/2686) and subscribe to that feature request.

**Comment by arshaw** [comment]
I'm closing this ticket because this issue can be solved with one or more other existing feature requests:
- [resource grouping](http://fullcalendar.io/js/fullcalendar-scheduler-1.2.0/demos/grouping.html)
- [multiple definitions of business hours](https://github.com/fullcalendar/fullcalendar/issues/2686)
- [multiple definitions of business hours, per resources](https://github.com/fullcalendar/fullcalendar-scheduler/issues/61)
- [eventAllow, callback to restrict events to resources](https://github.com/fullcalendar/fullcalendar-scheduler/issues/50)

**Comment by RuLoP** [comment]
Hi smartkid77 , 


just add folling rows:
            **selectConstraint: 'businessHours',
            eventConstraint: 'businessHours',**


plus for example:

**businessHours:[ 
                {
                    start: '09:00',
                    end: '13:00',
                    dow: [1, 2]
                },
                {
                    start: '14:00',
                    end: '16:00',
                    dow: [1, 2]
                },
                {
                    start: '10:00',
                    end: '19:00',
                    dow: [4]
                }**
