### ISSUE TITLE
Only display resources with events

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar-scheduler#98]
Provide the ability to show/hide a resource row in timeline view based on whether it has events associated with it or not.

Somewhat similar in nature to #12

**Comment by MartijnWelker** [comment]
Is there any milestone set for this ?

**Comment by arshaw** [comment]
Not yet. The upcoming milestones involves making FullCalendar/Scheduler work well with touch devices. This will be sometime after that

**Comment by aburcheri** [comment]
Maybe adding start and end in the resource call, like in events, will sometime solve not showing the empty resources...

**Comment by arshaw** [comment]
implemented and released in [v1.5.0](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.5.0)

https://fullcalendar.io/docs/resource_rendering/filterResourcesWithEvents/

**Comment by raihassen** [comment]
How to use this?

**Comment by saraAshraf99** [comment]
@arshaw this solution can hide unused resources but i need to hide column and just use it's values internally how i can do that ?

**Comment by mahjnalisha** [comment]
@arshaw  
I am using FullCalendar v3.8.0
I am using this feature. When I add  "filterResourcesWithEvents:true", it reloads my events continuously and never stop . I want this features as when filter by date range say for a day 
it doesnot show the midnight shift and when I add 2 days in a row, there are some resources being loaded without having any events. Can you please guide me how to tackle this problem?
