### ISSUE TITLE
Bug in selectConstraint with dow

### ISSUE THREAD

**Issue by sulian** [fullcalendar/fullcalendar-scheduler#99]
Hi, it's me again.

I want limit the creation or manipulation of events between two dates (now and now + 2 years) with selectConstraint, it works well but if I want to limit **also** the events to business days of week and I use the option "dow: [1,2,3,4,5]", it doesnt' work.

In my example, try to move the event to another day or ressource, nothing work : 
http://jsbin.com/tocolosoze/edit?js,output

Remove dow: [1,2,3,4,5], it works well but I can move to sunday or saturday :( .

It is a bug or I don't use correctly this function ?

Best regards

**Comment by sulian** [comment]
In fact, we must specify a period of time **or** a custom time-window not the two options together.

**Comment by arshaw** [comment]
the `eventConstraint` isn't designed to work with dates AND dow. Only designed to work with times (not bound to a specific day) and dow. You're getting unexpected results.

Would you mind creating a new issue on the [main project's issue tracker](https://github.com/fullcalendar/fullcalendar) for this?

**Comment by sulian** [comment]
Thanks you, I'll create a new ticket on the main project
